Test for Shadow bucket in index mode to determine if TAP listener is started
couchbaselabs/sync_gateway pull request #2200
Opened 2016-12-16 13:41 UTC by ajres

fixes #2193

2016-12-16 19:08 UTC, tleyden requested changes

2016-12-16 19:08 UTC, tleyden commented on db/database.go
> +	if options.IndexOptions == nil || options.Shadowing {
Can this be changed to be more consistent?  Eg `!options.IndexOptions || options.Shadowing` or `options.IndexOptions == nil || options.Shadowing != nil`

2016-12-16 19:08 UTC, tleyden commented on db/database.go
> +	AutoImport            bool // Whether autoImport of documents without _sync is enabled
Is `AutoImport` documented more anywhere?  Is `AutoImport` related to bucket shadowing?

2017-01-05 18:34 UTC, adamcfraser commented
I agree with the comments from @tleyden - I need some context on why TrackDocs is getting changed to AutoImport/Shadowing in this PR.

2017-01-09 10:42 UTC, ajres commented on db/database.go
> +	if options.IndexOptions == nil || options.Shadowing {
I've rebased this change against master and created a new PR which just adds a `Shadowing` property to the `DatabaseContextOptions` struct.

see #2213

2017-01-09 10:43 UTC, closed without merging