sgcollect_info new logging config processing to add all rotated log files
couchbaselabs/sync_gateway pull request #2305
Opened 2017-02-09 13:22 UTC by ajres

fixes #2298

2017-02-09 21:00 UTC, raghusarangapani commented
Looks ok to me. Will verify once the code is merged and the build is available.

2017-02-09 22:59 UTC, tleyden requested changes

2017-02-09 22:59 UTC, tleyden commented on tools/sgcollect_info
> +        log_file_name_split = os.path.splitext(log_file_name)
It might be clearer if you change this to:

```
name, ext = os.path.splitext(log_file_name)
```

2017-02-09 22:59 UTC, tleyden commented on tools/sgcollect_info
> +        for log_file_item_name in glob.iglob(rotated_logs_pattern):
This line is a lot to take in .. 

If it's building a path you can use `os.path.join()`

Maybe would be clearer as:


```
log_file_pattern = "{}*{}".format(name, ext)
os.path.join(
   log_file_parent_dir,
   log_file_pattern,
)
```

2017-02-09 22:59 UTC, tleyden commented on tools/sgcollect_info
> +            print('Capturing rotated log file >>> %s' % log_file_item_path)
Can you change this to `format` syntax?  

`'... {}'.format(log_file_item_path)`

2017-02-10 07:38 UTC, ajres commented on tools/sgcollect_info
> +        log_file_name_split = os.path.splitext(log_file_name)
Changed

2017-02-10 07:39 UTC, ajres commented on tools/sgcollect_info
> +        for log_file_item_name in glob.iglob(rotated_logs_pattern):
I wasn't sure if wildcard would be treated as a valid path, but I have changed it and tested OK.

2017-02-10 07:39 UTC, ajres commented on tools/sgcollect_info
> +            print('Capturing rotated log file >>> %s' % log_file_item_path)
Changed

2017-02-13 17:50 UTC, merged