Don’t limit number of changes retrieved if ChannelOptions option.ActiveOnly is set
couchbaselabs/sync_gateway pull request #2447
Opened 2017-03-31 13:49 UTC by ajres

fixes #2238 

Don’t limit the number of changes retrieved if ChaneOptions option.ActiveOnly is set to true, as deleted entries will be skipped so requiring more entries from the feed than the limit value.

I have manually reproduced this scenario, the specific fix for this is [here](https://github.com/couchbase/sync_gateway/blob/master/db/channel_cache.go#L151)

When options.ActiveOnly is true then don't limit the number of entries retrieved from the cache.

There is an additional limit set when retrieving changes from the [ChangesView](https://github.com/couchbase/sync_gateway/blob/master/db/changes_view.go#L83), I have modified this but I'm not sure if this needs to be done.

2017-03-31 23:32 UTC, adamcfraser commented
I'm concerned about the performance impact of this approach to the fix.  Since active-only is typically used for the initial pull replication by Couchbase Lite, it's commonly going to be returning a lot of data.  Ignoring the limit altogether in this scenario seems likely to result in a memory/CPU spike on Sync Gateway, and a slow HTTP response with the potential for client timeout issues.

For Sync Gateway, this is mainly a concern for the view query component.  The no-limit retrieval from the in-memory channel cache should be relatively inexpensive from a processing perspective, even if the cache is full.  There are probably a couple of options:
 - Add an 'active-only' version of the channels view, and use that for active-only views.  Probably simplest, but adds server overhead to maintain the view index.
 - Modify getChangesInChannelFromView issue to multiple view queries, looping until the number of active-only view rows reaches the limit.  This gets a bit tricky, as all results (active or not) still need to get backfilled into the channel cache, but is probably reasonable.


This also needs to be fixed for sg_accel, which is going to be doing channel index retrieval instead of a view query.  The same problem applies - we don't want to just remove the limit, as that will end up doing a (potentially slow) read of the entire channel from the index bucket.

2017-03-31 23:33 UTC, adamcfraser requested changes
Comments added on the PR.

2017-04-28 17:47 UTC, ajres commented
I have reworked the SG fix taking the Modify getChangesInChannelFromView issue to multiple view queries.

I am working on the sg_accel equivalent fix.

2017-08-14 17:26 UTC, ajres commented
This PR has been superceded by #2805

2017-08-14 17:27 UTC, closed without merging