Import of SDK-written documents
couchbaselabs/sync_gateway pull request #2493
Opened 2017-04-21 21:47 UTC by adamcfraser

When auto-import is enabled in the config, triggers import processing for non-SG writes seen on the mutation feed.  Identifies non-SG writes by comparing the document cas w/ the cas stamped on the xattr.

Required passing the feed cas down through DocChanged - refactored to just pass the entire TapEvent, as the signature was getting a bit bloated.

Depends on https://github.com/couchbase/sg-bucket/pull/21.

2017-04-21 21:47 UTC, adamcfraser commented
Manifest change for sg-bucket still pending.

2017-04-21 23:53 UTC, tleyden commented
Is https://github.com/couchbase/sg-bucket/pull/21/files ready to get merged?

2017-04-22 00:20 UTC, tleyden requested changes
See inline

2017-04-22 00:20 UTC, tleyden commented on db/database.go
> +			err = db.Bucket.WriteUpdateWithXattr(key, KSyncXattrName, 0, func(currentValue []byte, currentXattr []byte, cas uint64) (raw []byte, rawXattr []byte, err error) {
This is hard to mentally parse and also getting pretty horizontally wide.  What about pulling out the callback function?

```
callback := func(currentValue []byte, currentXattr []byte, cas uint64) (raw []byte, rawXattr []byte, err error) {
...
}
err = db.Bucket.WriteUpdateWithXattr(key, KSyncXattrName, 0, callback)

```

2017-04-22 00:20 UTC, tleyden commented on db/crud.go
> +		err = db.Bucket.WriteUpdateWithXattr(key, KSyncXattrName, int(expiry), func(currentValue []byte, currentXattr []byte, cas uint64) (raw []byte, rawXattr []byte, err error) {
Same comment on other `WriteUpdateWithXattr` call about pulling it out into a callback function

2017-04-22 05:49 UTC, adamcfraser commented on base/bucket_gocb.go
> +			if err != gocbcore.ErrSubDocBadMulti {
This was residual from before ErrSubDocBadMulti was split into a different case.  You're correct - right now the err check doesn't do anything, and it always executes this case (err is always nil at this point).  Will clean up.

2017-04-22 05:56 UTC, adamcfraser commented on db/database.go
> +			err = db.Bucket.WriteUpdateWithXattr(key, KSyncXattrName, 0, func(currentValue []byte, currentXattr []byte, cas uint64) (raw []byte, rawXattr []byte, err error) {
I'd prefer to leave this as-is.  I agree it's getting a bit wide, but in a standard editor it's still readable, and overall I find the inline function tracks better visually than a separate callback, particularly with the non-xattr usage right below it.

2017-04-22 05:57 UTC, adamcfraser commented on base/bucket_gocb.go
>  			err = res.Content("", rv)
Good idea - I've renamed it for clarity and to ensure there's no scope confusion in future.

2017-04-22 06:00 UTC, adamcfraser commented
Pushed up changes based on PR feedback.  If it looks good, I'll merge sg-bucket/update the manifest/merge.

2017-04-24 15:54 UTC, tleyden commented
Ok LGTM

2017-04-24 20:20 UTC, merged