Store old revisions as non-JSON binary
couchbaselabs/sync_gateway pull request #2559
Opened 2017-05-12 05:33 UTC by adamcfraser

To prevent temporary revision backups appearing in N1QL and view queries without requiring additional work in the query/map function, store the backups as non-JSON binary data.

Requires switching gocbBucket.SetRaw to store as Binary.  Only other non-binary usage was in auth.go - switched that to a simple Set.

Fixes #2558

2017-05-12 22:52 UTC, adamcfraser commented
Note: Setting the binary flag isn't sufficient to make N1QL ignore the doc - the binary flag is only used by the SDKs.  To ensure it's not available via N1QL, need to prefix the raw bytes with non-JSON data.

2017-05-12 23:14 UTC, tleyden requested changes
See inline

2017-05-12 23:14 UTC, tleyden commented on db/revision.go
> +const nonJSONPrefix = byte(1)
Can you add a comment that explains this out a little more?  Or ideally references some docs, if there is any.  As it stands, it feels a bit cryptic.

2017-05-13 01:10 UTC, tleyden commented
Actually it might be good to get this comment somewhere in the code: Note: Setting the binary flag isn't sufficient to make N1QL ignore the doc - the binary flag is only used by the SDKs. To ensure it's not available via N1QL, need to prefix the raw bytes with non-JSON data.

2017-05-13 01:28 UTC, adamcfraser commented
Ok - added that.

2017-05-13 04:46 UTC, merged