Trigger doc import on SG write
couchbaselabs/sync_gateway pull request #2599
Opened 2017-05-26 16:16 UTC by adamcfraser

If a document has been updated by a non-SG author but has not yet been imported, trigger import on an attempt to update the doc via Sync Gateway. Fixes #2554.

Refactored the import processing to return the imported doc, so that on-demand imports can proceed without having to requery the bucket for the document.  Normal cas check will handle the case where the document is updated by someone else after import but before subsequent processing.

This cleans up the on-demand import during a GET (no longer requires loop), and avoids an unnecessary kv operation when on-demand import is triggered by a PUT.

Also fixed handling in change_cache.go when node is running in xattr mode but not importing.  Previously non-SG writes would attempt to get cached, then be rejected based on the stale sequence value.  Instead, we shouldn't even try to cache in the first place.

2017-05-26 16:16 UTC, adamcfraser commented
Need to run the convergence functional tests to validate.

2017-05-30 20:51 UTC, adamcfraser commented
Dependent PRs:
https://github.com/couchbaselabs/walrus/pull/30
https://github.com/couchbase/sg-bucket/pull/24
https://github.com/couchbaselabs/sync-gateway-accel/pull/145

2017-05-30 21:15 UTC, adamcfraser commented
Functional tests look good.
http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc/653/

 - failing ttl/expiry tests are waiting for pending server fix
 - test_view_backfill_for_deletes is test issue (intermittent failure)

2017-05-31 01:04 UTC, tleyden requested changes
See inline

2017-05-31 01:04 UTC, tleyden commented on db/crud.go
> +			docOut, _, shadowerEcho, err = documentUpdateFunc(doc, currentValue != nil)
It's a bit confusing to have a `shadowerEcho` when presumably this code could execute in an XATTR-only scenario w/ no bucket shadowing.  I realize this was already in the master branch, but what do you think about renaming this to something that doesn't sound bucket-shadowing specific?

2017-05-31 01:04 UTC, tleyden commented on db/crud.go
> +			docOut, writeOpts, shadowerEcho, err = documentUpdateFunc(doc, currentValue != nil)
ditto regarding `shadowerEcho`

2017-05-31 20:37 UTC, adamcfraser commented on db/crud.go
> +			docOut, writeOpts, shadowerEcho, err = documentUpdateFunc(doc, currentValue != nil)
I think this is the appropriate usage here (non-xattr flow)

2017-05-31 20:38 UTC, adamcfraser commented on db/crud.go
> +			docOut, _, shadowerEcho, err = documentUpdateFunc(doc, currentValue != nil)
Updated to omit shadowerEcho in this scenario.

2017-05-31 20:38 UTC, adamcfraser commented on base/bucket_gocb.go
> +				return casOut, err
Makes sense.

2017-05-31 21:13 UTC, tleyden approved these changes

2017-05-31 21:57 UTC, merged