Feature/unit test parse revid
couchbaselabs/sync_gateway pull request #2661
Opened 2017-06-20 00:31 UTC by tleyden

2017-06-20 00:32 UTC, tleyden commented
This adds a unit test for ParseRevID.  Currently passing. 

Cherry picked from work in progress: https://github.com/couchbase/sync_gateway/issues/2651

2017-06-20 05:06 UTC, adamcfraser requested changes

2017-06-20 05:06 UTC, adamcfraser commented on db/revision_test.go
> +
A revision's digest is an MD5 checksum in hex (as string), so should only have the characters `[a-fA-F0-9]`.

Our current ParseRevID doesn't enforce that, but it's probably reasonable to limit the tests to those values (i.e. an alternate implementation of ParseRevID doesn't actually need to handle something like 2222-lj-lkjl).

2017-06-20 21:02 UTC, tleyden commented on db/revision_test.go
> +
OK I went ahead and removed that part of the test

2017-06-22 17:47 UTC, tleyden commented
@adamcfraser this one should be ready to merge

2017-06-22 17:55 UTC, merged