Fixes #2651 SG gets killed due to excessive memory usage with continu…
couchbaselabs/sync_gateway pull request #2669
Opened 2017-06-22 21:54 UTC by tleyden

…ous doc update

Fixes #2651

2017-06-23 00:12 UTC, adamcfraser requested changes
Functionally it looks good - some style questions, and then a question about performance.

2017-06-23 00:12 UTC, adamcfraser commented on db/revtree.go
> +func (tree RevTree) GenerationShortestNonTombstonedBranch() int {
The naming of these methods is hard to parse - it's hard to tell whether Generation is supposed to be a noun or a verb. Maybe 'CalculateShortest...' or something?

2017-06-23 00:16 UTC, tleyden commented on db/revtree.go
> +func (tree RevTree) GetTombstonedLeaves() []string {
Yes, it ended up being test-only.  I'll move it.

2017-06-23 00:39 UTC, tleyden commented on db/revtree.go
> +
Agreed, fixed in a32aee915ffc103c98099bafd4126b9a82861a5d

2017-06-23 00:45 UTC, tleyden commented on db/revtree.go
> +func (tree RevTree) GenerationShortestNonTombstonedBranch() int {
Fixed in 29a496103dc8579c512960be41a2895fe68d004c

Renamed to:

```
func (tree RevTree) FindShortestNonTombstonedBranch() (generation int) {
    ...
}
```

2017-06-23 00:45 UTC, tleyden commented on db/revtree.go
> +
Fixed in 29a496103dc8579c512960be41a2895fe68d004c

2017-06-23 06:03 UTC, adamcfraser approved these changes

2017-06-23 21:22 UTC, merged

2017-06-25 18:41 UTC, curiousily commented
Hi @tleyden,

Do you have any idea if this issue affects SG 1.4.1 as well?

Thank you for fixing this.

2017-06-26 17:46 UTC, tleyden commented
@curiousily yes, it definitely affects SG 1.4.1.

2017-06-26 20:26 UTC, curiousily commented
@tleyden any idea if it is going to be in SG 1.4.2 or something? We might be facing this issue (or something similar) in production. Thanks!

2017-06-26 23:33 UTC, tleyden commented
It's still under discussion, but I will update this ticket as soon as I know more.  Also, I'll let folks know that users are looking for a 1.4.x patch.

2017-06-27 15:22 UTC, curiousily commented
Thanks! Will be waiting for updates.