Trap panic in GetIndexEntry and log an ERROR
couchbaselabs/sync_gateway pull request #2785
Opened 2017-08-08 16:50 UTC by ajres

fixes #2777

2017-08-08 16:56 UTC, adamcfraser requested changes

2017-08-08 16:56 UTC, adamcfraser commented on db/kv_dense_block.go
> +		base.LogError(errors.New(fmt.Sprintf("Unable to GetIndexEntry from DensBlockIndexEntry, key: %v, cas: %v, startClock: %v, clock: %v",d.Key, d.cas, d.startClock, d.clock)))
I think it's useful to include the Key here, and possibly the cas.  The clocks aren't going to be logged as anything useful, I don't think (just pointers), and I think it's critical to log the error text that's being returned from SafeSlice.

2017-08-08 16:59 UTC, adamcfraser commented on db/kv_dense_block.go
> +	indexEntry, err := base.SafeSlice(d.value, int(position), int(position+INDEX_ENTRY_LEN))
I think there are a couple more places where we do slice targeting in dense_block - it feels like we should at least switch over GetEntry at the same time.

2017-08-09 16:15 UTC, ajres commented on db/kv_dense_block.go
> +	indexEntry, err := base.SafeSlice(d.value, int(position), int(position+INDEX_ENTRY_LEN))
Added SafeSlice to GetEntry

2017-08-09 16:16 UTC, ajres commented on db/kv_dense_block.go
> +	indexEntry, err := base.SafeSlice(d.value, int(position), int(position+INDEX_ENTRY_LEN))
Updated log message format to remove clocks and add SafeSlice error message

2017-08-10 19:38 UTC, ajres commented
Commented out the block in rollbackEntries that checks for a nil indexEntry and re-ran the unit tests. The new emty block rollback test failed:

```
2017-08-10T20:35:25.811+01:00 ERROR: Unable to GetIndexEntry from DensBlock, key: block2, cas: 0, error: Invalid slice [786422:786434] of []byte with len 2 -- db.(*DenseBlock).GetIndexEntry() at kv_dense_block.go:604
--- FAIL: TestDenseBlockRollbackTo (0.00s)
panic: runtime error: slice bounds out of range [recovered]
	panic: runtime error: slice bounds out of range

goroutine 2029 [running]:
panic(0x56f3a0, 0xc420012100)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc420da4240)
	/usr/local/go/src/testing/testing.go:579 +0x25d
panic(0x56f3a0, 0xc420012100)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/couchbase/sync_gateway/db.(*DenseBlock).rollbackEntries(0xc421f37df8, 0xc420da0001, 0x1, 0x0, 0x2b)
	/Users/andy/Projects/sync_gateway-2777/godeps/src/github.com/couchbase/sync_gateway/db/kv_dense_block.go:376 +0x1c5
github.com/couchbase/sync_gateway/db.(*DenseBlock).RollbackTo(0xc421f37df8, 0xc420da0001, 0x1, 0x8dc880, 0xc42093a880, 0xc4213bd200, 0x0, 0x0)
	/Users/andy/Projects/sync_gateway-2777/godeps/src/github.com/couchbase/sync_gateway/db/kv_dense_block.go:303 +0x6e
github.com/couchbase/sync_gateway/db.TestDenseBlockRollbackTo(0xc420da4240)
	/Users/andy/Projects/sync_gateway-2777/godeps/src/github.com/couchbase/sync_gateway/db/kv_dense_channel_storage_test.go:387 +0x1f87
testing.tRunner(0xc420da4240, 0x6b65b0)
	/usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x2ec
FAIL	github.com/couchbase/sync_gateway/db	17.303s
```

2017-08-10 23:01 UTC, adamcfraser approved these changes

2017-08-10 23:02 UTC, adamcfraser commented
Looks good.  @ajres Can you rebase to address the conflicts, and then we can merge?

2017-08-11 16:27 UTC, merged