Add configurable stderr log path to service wrapper
couchbaselabs/sync_gateway pull request #3038
Opened 2017-11-07 14:27 UTC by ajres

fixes https://github.com/couchbaselabs/sync-gateway-accel/issues/116

2017-11-07 17:24 UTC, ajres commented
Testing so far has been by replacing the service wrapper .exes on a Windows 10 VM and stopping and starting the services manually.

No packaged installer testing has been carried out so far

2017-11-13 19:28 UTC, tleyden requested changes

2017-11-13 19:28 UTC, tleyden commented on service/sg-windows/sg-accel-service/sg-accel-service.go
> +		svcConfig.Arguments = []string{"start", stderrPath}                      // Uses the default config
`stderrPath` should be pulled out into a single constant rather than being duplicated several times.

2017-11-13 19:28 UTC, tleyden commented on service/sg-windows/sg-service/sg-service.go
> +		stderrPath = os.Args[4]
If these are going to be using positional (as opposed to named) arguments, is the usage documented anywhere?  

Or is this usage always strictly internal by a service script?  In that case, maybe it's less important to document.  Do Windows users typically start Sync Gateway on the Command Prompt?

2017-12-15 23:16 UTC, merged