Fixes #3165
couchbaselabs/sync_gateway pull request #3183
Opened 2018-01-10 02:05 UTC by tleyden

Fixes #3165

Verified by manual testing with SG in reader mode + SG Accel, using the Todo iOS sample app on the `feature/2.0` branch for replication.

Adding a unit test to repro is a fair amount of work, so that might be better done as a separate issue.

2018-01-10 17:15 UTC, adamcfraser requested changes

2018-01-10 17:15 UTC, adamcfraser commented on rest/blip_sync.go
> +
It feels like we should pull the code: https://github.com/couchbase/sync_gateway/blob/4c6bd7044a31a82fcf8a44f02df9a52ecdd07ad5/rest/changes_api.go#L800-L804

into a helper method that could be called from changes_api and here - what do you think?

2018-01-10 18:32 UTC, tleyden commented
@adamcfraser ok I've implemented that change.  Ready for another review.

2018-01-12 18:51 UTC, adamcfraser approved these changes

2018-01-12 18:52 UTC, merged