#3255 Add recover in blipHandler sendRevision goroutine
couchbaselabs/sync_gateway pull request #3282
Opened 2018-02-07 15:14 UTC by bbrks

#3255 Recover from panic inside blipHandler sendRevision goroutine

2018-02-07 17:40 UTC, adamcfraser commented
@tleyden Similar to https://github.com/couchbase/go-blip/pull/21 - would like to discuss correct failure handling.

2018-02-07 18:30 UTC, adamcfraser requested changes

2018-02-07 18:30 UTC, adamcfraser commented on rest/blip_sync.go
> +				}
Close the bh on panic.

2018-02-08 18:14 UTC, bbrks commented
## Integration Tests
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/387/
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/388/

2018-02-08 22:59 UTC, tleyden approved these changes

2018-02-09 17:28 UTC, adamcfraser approved these changes

2018-02-09 17:29 UTC, merged