Use deferred build when initializing Sync Gateway indexes
couchbaselabs/sync_gateway pull request #3476
Opened 2018-04-19 05:43 UTC by adamcfraser

When creating multiple indexes, deferring building of those indexes allows more efficient indexing.

Modify index creation to always defer, then issue a BUILD INDEX for any created indexes.  Also checks for already existing deferred SG indexes and builds those (from previous startup failure, for example).

Fixes #3415

2018-04-19 17:48 UTC, tleyden commented
This seems like a good candidate for an integration test run to make sure nothing blows up

2018-04-19 17:52 UTC, adamcfraser commented
Integration test:
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/518/

2018-04-19 18:09 UTC, tleyden requested changes
A few minor inline comments, one param that looks like it's unused

2018-04-19 18:13 UTC, adamcfraser commented on base/bucket_n1ql.go
> +	createStatement := fmt.Sprintf("CREATE PRIMARY INDEX `%s` ON `%s`", indexName, bucket.GetName())
That's correct.

2018-04-19 18:15 UTC, adamcfraser commented on db/indexes.go
>  	base.Infof(base.KeyAll, "Initializing indexes with numReplicas: %d", numReplicas)
I'll file a separate ticket for that.  I think we can rip out the numHousekeepingReplicas altogether (including the config), and just use numReplicas.

2018-04-19 18:28 UTC, adamcfraser commented on db/indexes.go
>  	base.Infof(base.KeyAll, "Initializing indexes with numReplicas: %d", numReplicas)
https://github.com/couchbase/sync_gateway/issues/3479

2018-04-19 18:34 UTC, adamcfraser commented
Integration test failed w/ error:
--- FAIL: TestDeferredCreateIndex (7.67s)
	set_test.go:114: Error building indexes: [5000] BuildIndexes - cause: Build index fails.  %vIndex testIndexDeferred will retry building in the background for reason: Build Already In Progress. Bucket test_data_bucket.

Need to detect and handle this error.

2018-04-19 22:39 UTC, adamcfraser commented
Updated, rerunning integration:
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/525/

2018-04-19 23:58 UTC, adamcfraser commented
Latest integration test (with improved indexer error handling) doesn't show the same failure in TestDeferredCreateIndex.  @tleyden Should be good to re-review.

2018-04-20 00:17 UTC, tleyden approved these changes

2018-04-20 00:17 UTC, tleyden commented
LGTM

2018-04-20 16:13 UTC, merged