Only retry a bucket Update/WriteUpdate with a CAS failure
couchbaselabs/sync_gateway pull request #3691
Opened 2018-08-03 14:54 UTC by bbrks

Closes #3690 
Fixes #3689 

- `Update` and `WriteUpdate` used to go into an unlimited retry loop on every error until it succeeded. Now we only retry on an explicit CAS failure.
- Minor improvement to error message in DCP `initFeed`.

2018-08-03 16:13 UTC, adamcfraser commented
Do we already have unit tests that validate the gocb cas failure error codes for all the scenarios covered here (update/delete/replace)?  If not, we should add them along with this change.

2018-08-03 16:14 UTC, adamcfraser requested changes
Based on the coverage report, it looks like we may not have unit tests for the cas failure scenarios being modified here.  We should add those before making this change.

2018-08-15 16:28 UTC, bbrks commented
Awaiting coverage run through integration tests

2018-08-20 17:28 UTC, adamcfraser commented
Waiting on https://github.com/couchbase/sync_gateway/issues/3701

2018-09-03 16:04 UTC, bbrks commented
Unit test and integration test coverage report can be found here: http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-coverage/33/Code_Coverage/

Spotted a seemingly sporadic data race in the last run of the branch build, filled #3726 and re-run.

2018-09-05 16:38 UTC, adamcfraser approved these changes

2018-09-05 16:38 UTC, merged