Avoid error when processing documents impacted by #3692
couchbaselabs/sync_gateway pull request #3769
Opened 2018-09-27 23:42 UTC by adamcfraser

Fixes #3700.

2018-09-27 23:42 UTC, adamcfraser commented
Currently includes commit from https://github.com/couchbase/sync_gateway/pull/3768 - need to rebase once that's merged.

2018-09-28 16:14 UTC, bbrks requested changes
Couple of test teardown issues that need adding after rebasing

2018-09-28 16:14 UTC, bbrks commented on db/crud_test.go
> +	db, _ := setupTestDBWithCacheOptions(t, CacheOptions{})
We'll need to defer `Close()` on the returned bucket to avoid test issues. I missed this in #3768

2018-09-28 16:14 UTC, bbrks commented on db/crud_test.go
> +	db, _ := setupTestDBWithCacheOptions(t, CacheOptions{})
Again, need to defer `Close()` on the returned bucket

2018-09-28 17:28 UTC, bbrks approved these changes

2018-09-28 17:29 UTC, merged