Refactoring for testify/asserts
couchbaselabs/sync_gateway pull request #3810
Opened 2018-10-29 23:09 UTC by adamcfraser

Use testify asserts for utility asserts previously cloned across packages.  Refactors go.assert usages to goassert - plan is to phase these usages out opportunistically.

Manifest change depends on https://issues.couchbase.com/browse/MB-31790

2018-10-30 12:02 UTC, bbrks commented
Testify now mirrored in couchbasedeps, re-running Jenkins job.

2018-10-30 13:00 UTC, bbrks requested changes

2018-10-30 21:28 UTC, adamcfraser commented
Build appears to be failing due to data race in TestMissingNoRev, with the race occuring in the test blip handler (shared map writes).  Doesn't look new to this PR, but investigating to see if there's an obvious fix.

2018-10-31 11:48 UTC, bbrks approved these changes

2018-10-31 11:48 UTC, merged