Modify Update, WriteUpdate to return cas
couchbaselabs/sync_gateway pull request #3811
Opened 2018-10-30 23:27 UTC by adamcfraser

Update and WriteUpdate perform a cas-safe update using a callback function.  However, they don't return the final cas value of the updated document - this is useful in cases where Update/WriteUpdate are used to perform additional processing during Get (e.g. getPrincipal).

The equivalent functionality already exists for the xattr version of the operation.

Prerequisite for #3414.

2018-10-30 23:37 UTC, adamcfraser commented
- [ ] http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/845/
- [ ] http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/846/

2018-10-31 12:06 UTC, bbrks requested changes
LGTM, just need to update the manifest hashes for walrus and sg-bucket

2018-10-31 17:59 UTC, adamcfraser commented
Manifest has been updated.  Integration test failures look to be related to a prior merge issue - will handle in a separate PR.

2018-10-31 18:01 UTC, bbrks approved these changes

2018-10-31 18:02 UTC, merged