Prepend database-level logging with database name
couchbaselabs/sync_gateway pull request #3816
Opened 2018-11-06 00:41 UTC by adamcfraser

Fixes #3815

2018-11-06 00:42 UTC, adamcfraser commented
@bbrks Would like your review on this when you're back - not urgent.

2018-11-07 23:51 UTC, JFlath commented on db/repair_bucket.go
> +* For the next pageo, it uses the last key processed as the new start key
Unrelated change/typo?

2018-11-07 23:51 UTC, JFlath commented on db/repair_bucket.go
> +* For the next pageo, it uses the last key processed as the new start key
Ooh, let me try this thing...

```suggestion
* For the next page, it uses the last key processed as the new start key
```

2018-11-12 15:25 UTC, bbrks requested changes
Missing a necessary return in the if `context == nil` blocks to prevent panics/double logging.

See what you think about the other comments around exiting early too.

2018-11-14 11:08 UTC, bbrks commented
Closing this PR in favour of a more generic approach to contextual logging. See last update on #3815

2018-11-14 11:08 UTC, closed without merging