Store attachment and expiry metadata in rev cache
couchbaselabs/sync_gateway pull request #3831
Opened 2018-11-19 06:30 UTC by adamcfraser

Avoids additional bucket GET when retrieving attachment or expiry data when document is resident in the rev cache.

Includes refactoring to standardize interaction with _attachments.

Fixes #3688

2018-11-19 06:31 UTC, adamcfraser commented
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/853/
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/854/

2018-11-20 14:22 UTC, bbrks requested changes
The main bulk of this looks OK. I have left some comments on the new test.

No need to re-run integration tests if this is the only update to make.

2018-11-20 23:52 UTC, adamcfraser commented on db/attachment_test.go
> +	log.Printf("Create rev 1...")
Since it's log and not fmt the `\n` isn't needed, but this is dev-time diagnostic logging that doesn't need to be kept - will remove.

2018-11-21 00:29 UTC, adamcfraser commented on db/attachment_test.go
> +	json.Unmarshal([]byte(rev1input), &body)
Fixed.

2018-11-21 00:29 UTC, adamcfraser commented on db/attachment_test.go
> +	goassert.Equals(t, tojson(gotbody), rev1output)
Switched throughout attachment_test.go.

2018-11-21 12:31 UTC, bbrks requested changes

2018-11-21 12:31 UTC, bbrks commented on db/attachment_test.go
> +	assert.Equal(t, 0, getCount)
This works OK in isolation, but when this test runs as part of a suite, expvars are carried over between tests.
Should we consider resetting then via expvarMap.Init() when a test database is created?

2018-11-22 03:10 UTC, adamcfraser commented
Latest CI build failure looks like a test race related to the sleep here: 
https://github.com/couchbaselabs/sync-gateway-accel/blob/master/indexwriter/kv_change_index_test.go#L76.  Appears unrelated to this change.

2018-11-22 10:45 UTC, bbrks approved these changes

2018-11-22 10:45 UTC, merged