New database, push, pull replication stats
couchbaselabs/sync_gateway pull request #3858
Opened 2018-12-08 00:44 UTC by adamcfraser

2018-12-10 21:57 UTC, tleyden commented
@adamcfraser the build failed with:

```

godeps/src/github.com/couchbase/sync_gateway/base/dcp_feed.go:191:3: unknown field 'TimeReceived' in struct literal of type sgbucket.FeedEvent

script returned exit code 2
```

2018-12-10 22:03 UTC, adamcfraser commented
@tleyden I'd forgotten about the sg-bucket change.  Pushed up a PR on sg-bucket (linked above), and bumped the manifest here to point to the PR commit.

2018-12-10 23:34 UTC, tleyden commented
Looks like it failed again, this time due to:

```
018-12-10T15:24:12.933-08:00 [INF] rest.TestContinuousChangesSubscription: Reset logging
--- FAIL: TestContinuousChangesSubscription (5.72s)
    blip_api_test.go:247: 
        	Error Trace:	blip_api_test.go:247
        	Error:      	Received unexpected error:
        	            	Timed out waiting after 5s
        	Test:       	TestContinuousChangesSubscription
        	Messages:   	Timed out waiting for all changes.
2018-12-10T15:24:12.933-08:00 [INF] rest.TestBlipOneShotChangesSubscription: Setup logging: level: info - keys: HTTP, Sync, SyncMsg
2018-12-10T15:24:12.933-08:00 [INF] Opening Walrus database test_data_bucket-97e09cdf50ce3e68fc3d9a58133246ef on <walrus:>
```

I'm assuming this is safe to ignore?

2018-12-11 00:26 UTC, tleyden requested changes
See inline

2018-12-12 01:31 UTC, adamcfraser commented on db/changes.go
>  				waitResponse := changeWaiter.Wait()
I think it's cleaner here, and avoids needing to pass a dbcontext down into changeWaiter.

2018-12-12 01:32 UTC, adamcfraser commented on db/crud.go
> +		db.DbStats.CblReplicationPush().Add(base.StatKeySyncFunctionCount, 1)
ChannelMapper doesn't have any db context awareness - I think it makes sense to keep it that way.

2018-12-12 01:34 UTC, adamcfraser commented on db/database_stats.go
> +
Looks like it didn't get cleaned up after reads were split to REST/Blip.  Will remove.

2018-12-12 01:36 UTC, adamcfraser commented on rest/blip_sync.go
> +		bh.db.DbStats.CblReplicationPush().Add(base.StatKeyProposeChangeCount, time.Since(startTime).Nanoseconds())
Fixed

2018-12-12 01:36 UTC, adamcfraser commented on rest/blip_sync.go
> +		bh.db.DbStats.CblReplicationPush().Add(base.StatKeyProposeChangeCount, time.Since(startTime).Nanoseconds())
Fixed.

2018-12-12 01:47 UTC, adamcfraser commented on db/change_cache.go
> +		c.context.DbStats.StatsCblReplicationPull().Get(base.StatKeyMaxPending).(*base.IntMax).SetIfMax(int64(numPending))
Seems reasonable - I'll add.

2018-12-12 21:16 UTC, adamcfraser commented
Rebased on master, re-running PR build.

2018-12-12 23:39 UTC, tleyden approved these changes

2018-12-12 23:39 UTC, merged