Improve cache validFrom handling
couchbaselabs/sync_gateway pull request #3895
Opened 2019-01-09 06:26 UTC by adamcfraser

Fixes #3872.

Avoids scenarios where query range and cache validFrom result in query results not being prepended to the cache, or redundant queries being issued because cache validFrom isn't associated with a sequence in the cache.  

Replaces 'one entry overlap' prepend approach with comparison of query range vs. cache validFrom/validTo at prepend time.  Adds several tests for scenarios that were previously generating unnecessary queries.

Refactors some cache-related APIs to make it clearer what sequence ranges are being requested/served (previously depended on relatively opaque changes.Options processing.

2019-01-09 18:01 UTC, adamcfraser commented
Rebased on master to pick up test timeout change.

2019-01-10 05:34 UTC, adamcfraser commented
http://uberjenkins.sc.couchbase.com:8080/view/Build/job/sync-gateway-integration-master/949/

2019-01-10 14:24 UTC, bbrks commented
Rebased onto master to pick up #3899 #3900

2019-01-10 16:40 UTC, bbrks requested changes
Minor comments left, but want to walk through one of the tests to understand a question I had.

2019-01-10 16:40 UTC, bbrks commented on rest/changes_api_test.go
> +	// Issue a since=0 changes request.  Validate that there is not another a view-based backfill
```suggestion
	// Issue a since=0 changes request.  Validate that there is another a view-based backfill
```

2019-01-10 16:40 UTC, bbrks commented on rest/changes_api_test.go
> +	goassert.Equals(t, secondQueryCount, queryCount+1)
I'm not sure why we're issuing 2 view backfills for the same request here. Shouldn't the cache only need to be backfilled once? Could perhaps do with walking through what's going on here.

2019-01-10 16:40 UTC, bbrks commented on db/channel_cache.go
> +	// limit = options.Limit
```suggestion
```

2019-01-10 16:40 UTC, bbrks commented on db/changes_view.go
> +
looks like some leftover code

2019-01-10 17:31 UTC, bbrks approved these changes

2019-01-10 17:33 UTC, adamcfraser commented
Failing test from integration run (TestViewQueryMultipleViews) passes locally against CBS - looks like it's related to #3829.

2019-01-10 21:35 UTC, merged