CBG-220 again
couchbaselabs/sync_gateway pull request #3977
Opened 2019-02-20 17:23 UTC by adamcfraser

2019-02-20 17:41 UTC, adamcfraser commented on base/logger.go
> +// logDirectory is the supplied directory where the logs are stored.
Add unit tests for runLogDeletion to verify handling for scenarios:
- standard case
- hit low watermark but not high watermark
- single file triggering low + high watermark
- no deletion required (didn't hit low watermark)
- file datetime boundary conditions (end of month, end of year, etc)

2019-02-20 17:41 UTC, adamcfraser commented on base/logger_file.go
> +	defaultCumulativeMaxSizeBeforeDeletion = 300  // 300 MB
Compare this to the 2.0 defaults (max age + max num) to evaluate whether this is sufficient.

2019-02-21 11:15 UTC, bbrks requested changes

2019-02-21 17:15 UTC, bbrks approved these changes

2019-02-21 17:16 UTC, merged