CBG-239: Removed pprof headers and removed formats
couchbaselabs/sync_gateway pull request #3998
Opened 2019-03-05 11:51 UTC by JRascagneres

- Removed pprof headers
- Added new profiles; block & mutex
- Renamed pprof output to [profile_type].profile
- Prevented generation of the readable formats; dot, pdf, text & raw

2019-03-05 12:59 UTC, bbrks requested changes
Looks good, one suggestion I have is to prefix the profiles so they're grouped together, and switch to `.pg.gz` extension like in the [pprof examples](https://github.com/google/pprof#generate-a-graph-in-an-svg-file-and-open-it-with-a-web-browser) (e.g. pprof_block.pb.gz)

2019-03-05 19:30 UTC, JRascagneres commented
Add new file names to blacklist and remove formats from blacklist.

2019-03-06 15:12 UTC, bbrks approved these changes
Looks good to me. I'll let Adam give it a pass before merging.

2019-03-06 16:56 UTC, adamcfraser approved these changes

2019-03-06 16:56 UTC, merged