CBG-255: Created new constructor to avoid RestTester panic
couchbaselabs/sync_gateway pull request #4004
Opened 2019-03-07 17:50 UTC by JRascagneres

- [ ] Merge CBG-256 
- [ ] Rebase dev first 

This is to avoid possible conflicts

2019-03-07 18:14 UTC, adamcfraser requested changes

2019-03-07 18:14 UTC, adamcfraser commented on rest/utilities_testing.go
> +type RestTesterConfig struct {
I think this approach makes sense, but only for config-style properties.  That looks like SyncFn, DatabaseConfig at minimum - could review usages to see if there's anything else.  

If there's a use case to initialize a RestTester for an existing bucket or server context, I think a separate constructor makes more sense.

2019-03-07 18:14 UTC, adamcfraser commented on rest/utilities_testing.go
> +					rt.Testing.Error(fmt.Sprintf("Error initializing %s in test bucket: %v", db.SyncSeqKey, incrErr))
Fatalf makes more sense here and below.

2019-03-07 18:33 UTC, bbrks requested changes

2019-03-07 18:33 UTC, bbrks commented on base/bucket_gocb_test.go
> +	t.Skip()
Not required for this PR

2019-03-07 18:33 UTC, bbrks commented on rest/utilities_testing.go
> +func NewRestTester(Tester testing.TB, RestConfig *RestTesterConfig) *RestTester {
Parameters in functions usually start with lowercase by convention.

```suggestion
func NewRestTester(tester testing.TB, restConfig *RestTesterConfig) *RestTester {
```

2019-03-07 18:33 UTC, bbrks commented on rest/utilities_testing.go
> +	rt.Testing = Tester
We probably want to check that tester isn't `nil` to prevent `NewRestTester(nil, nil)`

2019-03-07 18:33 UTC, bbrks commented on rest/utilities_testing.go
> +	return NewBlipTesterFromSpec(tester, defaultSpec)
If we've changed `NewBlipTesterFromSpec` to take a tester explicitly, do we still need to create a new RestTester here just for defaultSpec?

2019-03-07 18:33 UTC, bbrks commented on rest/utilities_testing.go
> +		var rt = NewRestTester(tester, &rtConfig)
See above comment with respect to `NewRestTester`. We're doing this work twice.

2019-03-08 17:12 UTC, adamcfraser approved these changes

2019-03-08 17:13 UTC, merged