CBG-287: Remove unnecessary log line and fixed multiple writeheader
couchbaselabs/sync_gateway pull request #4061
Opened 2019-04-08 14:15 UTC by JRascagneres

2019-04-08 16:19 UTC, bbrks requested changes

2019-04-08 16:20 UTC, adamcfraser commented on rest/encoded_response_writer.go
> +	statusSet bool
Change to headerWritten (or something along those lines)

2019-04-08 16:22 UTC, adamcfraser commented on rest/bulk_api.go
> +	h.writeStatus(http.StatusOK, http.StatusText(http.StatusOK))
Stick a comment in here explaining why we're setting the status here, even though the request might subsequently fail. (i.e. response.Write is setting implicitly, doc-level errors are handled in the response, broken pipe doesn't require header)

2019-04-09 16:13 UTC, adamcfraser approved these changes

2019-04-09 16:14 UTC, bbrks approved these changes

2019-04-09 16:14 UTC, merged