CBG-297: Backport of CBG-286
couchbaselabs/sync_gateway pull request #4064
Opened 2019-04-09 12:04 UTC by JRascagneres

2019-04-10 13:52 UTC, JFlath requested changes
Could you update the commit message to actually say what it does (if possible without making it too long? As it stands, this would make it really awkward to work out what this does when reading a git log or looking at what's in 2.1.4...

2019-04-10 15:22 UTC, JRascagneres commented
> Could you update the commit message to actually say what it does (if possible without making it too long? As it stands, this would make it really awkward to work out what this does when reading a git log or looking at what's in 2.1.4...

Would probably be too long for title so put it in the description

2019-04-11 10:45 UTC, bbrks requested changes

2019-04-11 10:45 UTC, bbrks commented on base/bucket.go
> +func IsXattrSupported(bucket Bucket) bool {
As discussed, let's add a nil check here for bucket to be defensive

2019-04-11 10:55 UTC, bbrks approved these changes

2019-04-11 11:46 UTC, merged