CBG-299: Backport CBG-287 to 2.5.1
couchbaselabs/sync_gateway pull request #4073
Opened 2019-04-10 11:13 UTC by JRascagneres

2019-04-10 13:50 UTC, JFlath requested changes
Could you update the commit message to actually say what it does (if possible without making it too long? As it stands, this would make it really awkward to work out *what* this does when reading a git log or looking at what's in 2.5.1...

2019-04-10 15:15 UTC, JRascagneres commented
> Could you update the commit message to actually say what it does (if possible without making it too long? As it stands, this would make it really awkward to work out _what_ this does when reading a git log or looking at what's in 2.5.1...

Would probably be too long for title so put it in the description

2019-04-11 10:43 UTC, bbrks approved these changes

2019-04-11 10:44 UTC, merged

2019-04-11 10:44 UTC, JFlath approved these changes