CBG-307:Continue on error when removing obsolete indexes
couchbaselabs/sync_gateway pull request #4085
Opened 2019-04-17 20:02 UTC by JRascagneres

2019-04-18 10:12 UTC, bbrks requested changes

2019-04-18 10:12 UTC, bbrks commented on db/indexes_test.go
> +	gocbBucket, ok := base.AsGoCBBucket(testBucket.Bucket)
not checking `ok` here

2019-04-18 10:12 UTC, bbrks commented on db/indexes_test.go
> +func TestRemoveObsoleteIndexOnFail(t *testing.T) {
probably only want to run for non-walrus tests

2019-04-18 10:12 UTC, bbrks commented on db/indexes_test.go
> +	if removeError != nil {
`assert.NoError` instead?

2019-04-18 10:12 UTC, bbrks commented on base/leaky_bucket.go
> +	gocbBucket, ok := AsGoCBBucket(b.bucket)
Perhaps do the bucket type check first, before we do the artificial error stuff.

2019-04-18 10:12 UTC, bbrks commented on db/database.go
> +		return nil, errors.New("Must be gocbBucket")
This is changing the behaviour of the function.
Previously we just warned and skipped over when it was a non-gocb bucket (from `removeObsoleteIndexes`)

```go
	gocbBucket, ok := base.AsGoCBBucket(bucket)
	if !ok {
		base.Warnf(base.KeyAll, "Cannot remove obsolete indexes for non-gocb bucket - skipping.")
		return removedIndexes, nil
	} 
```

2019-04-18 10:12 UTC, bbrks commented on db/indexes.go
> +	fmt.Println(removalCandidates)
debug stuff left in

2019-04-18 10:38 UTC, bbrks requested changes

2019-04-18 10:38 UTC, bbrks commented on db/indexes_test.go
> +	assert.NoError(t, err)
wrong error variable name

2019-04-18 10:38 UTC, bbrks commented on db/database.go
> +		return removedIndexes, nil
Do we need to create the zero-length slice to prevent it being null like `removeObsoleteIndexes` did?

2019-04-18 10:38 UTC, bbrks commented on db/indexes_test.go
> +	assert.True(t, len(indexNames) == len(removedIndexes)+1)
assert.Equal might give us a bit more information if this ever starts to fail

2019-04-18 11:10 UTC, bbrks approved these changes

2019-04-18 16:21 UTC, adamcfraser requested changes
Generally looks good, couple of comments.

2019-04-18 16:21 UTC, adamcfraser commented on db/indexes.go
> +		removed, _ := removeObsoleteIndex(bucket, indexName, previewOnly)
Review whether we should be logging error here.  We could optionally fail silently on the case where the error was 'index does not exist', but should log any other errors.

2019-04-18 16:21 UTC, adamcfraser commented on db/indexes_test.go
> +func TestRemoveObsoleteIndexOnFail(t *testing.T) {
As discussed, can follow pattern in TestPostUpgradeIndexesVersionChange

2019-04-23 16:40 UTC, adamcfraser requested changes
Looks good pending additional comments for the test.

2019-04-24 17:09 UTC, adamcfraser requested changes
Looks ok, just init indexPreviousVersions empty

2019-04-25 10:06 UTC, bbrks commented on db/indexes.go
> +	// Index versions - must be incremented when index definition changes
```suggestion
	// Previous index versions - must be appended when index definition changes
```

2019-04-25 12:50 UTC, bbrks requested changes
added suggestion for changing comment, but also the debug println seems to have been re-added

2019-04-25 12:50 UTC, bbrks commented on db/indexes.go
> +	fmt.Println(removalCandidates)
this println has appeared again

2019-04-26 13:31 UTC, bbrks approved these changes
Changes LGTM 👍

2019-04-26 16:40 UTC, adamcfraser approved these changes

2019-04-26 16:40 UTC, merged