CBG-306: Function rename and removal of panic
couchbaselabs/sync_gateway pull request #4092
Opened 2019-04-24 12:37 UTC by JRascagneres

2019-04-24 12:48 UTC, bbrks requested changes

2019-04-24 12:48 UTC, bbrks commented on db/revision.go
> +		return nil, errors.New(fmt.Sprintf("Couldn't encode body %v", body))
```suggestion
		return nil, fmt.Errorf("Couldn't encode body %v", body)
```

2019-04-24 17:05 UTC, adamcfraser reviewed
For channels.SetOf, we should:
- review non-test usage and switch to SetFromArray where appropriate (and handle the error)
- identify non-test use cases that aren't a good fit for SetFromArray, review how they can handle error
- for test usage, add a test-only API that logs a warning and returns an empty set on invalid channel names (for ease of use by tests).  Could potentially pass in testing.T and raise Fatalf on invalid channels to help clarify it's test-only.

2019-04-29 14:07 UTC, bbrks requested changes

2019-04-29 14:07 UTC, bbrks commented on db/document.go
> +		//panic("HAI")
ohai

2019-04-29 14:07 UTC, bbrks commented on rest/blip_sync.go
> +			//panic("HAI")
ohai

2019-04-29 16:17 UTC, adamcfraser requested changes
A few changes - the accel PR is merged and so can also bump the manifest.

2019-04-29 16:17 UTC, adamcfraser commented on channels/set.go
> +func SetOf(tb testing.TB, names ...string) base.Set {
Move to a new util_testing.go inside channels package.

2019-04-29 16:17 UTC, adamcfraser commented on db/changes.go
> +
Remove whitespace

2019-04-29 16:17 UTC, adamcfraser commented on rest/blip_sync.go
> +		channelSetReturn, err := channels.SetFromArray([]string{channels.AllChannelWildcard}, channels.KeepStar)
Can switch to base.SetOf and avoid error handling.

2019-04-29 16:17 UTC, adamcfraser commented on rest/changes_api.go
> +	userChannels, err := ch.SetFromArray([]string{ch.AllChannelWildcard}, ch.KeepStar)
As above - base.SetOf

2019-04-30 16:03 UTC, adamcfraser approved these changes

2019-04-30 16:04 UTC, merged