CBG-359: Return multiple warnings and move to validate()
couchbaselabs/sync_gateway pull request #4128
Opened 2019-05-23 12:56 UTC by JRascagneres

2019-05-23 16:21 UTC, bbrks requested changes

2019-05-23 16:27 UTC, adamcfraser commented on rest/config.go
> +			base.Errorf(base.KeyAll, "An error %v", err)
Improve this to "Config file validation error:"

2019-05-24 12:44 UTC, bbrks requested changes
Looks good - Might just need to re-add the `skipRunModeValidation` handling

2019-05-24 12:44 UTC, bbrks commented on rest/config.go
> +		if config.HasAnyIndexWriterConfiguredDatabases() {
Need to re-add `skipRunModeValidation` handling here

2019-05-24 13:34 UTC, bbrks commented on rest/config.go
> +		if config.HasAnyIndexReaderConfiguredDatabases() && !config.SkipRunmodeValidation {
```suggestion
		if !config.SkipRunmodeValidation && config.HasAnyIndexReaderConfiguredDatabases() {
```

2019-05-24 13:34 UTC, bbrks commented on rest/config.go
> +		if config.HasAnyIndexWriterConfiguredDatabases() && !config.SkipRunmodeValidation {
```suggestion
		if !config.SkipRunmodeValidation && config.HasAnyIndexWriterConfiguredDatabases() {
```

2019-05-24 15:13 UTC, bbrks approved these changes

2019-05-24 16:17 UTC, merged