CBG-402: Include non-epoch time in sg_stats
couchbaselabs/sync_gateway pull request #4151
Opened 2019-06-12 16:06 UTC by JRascagneres

2019-06-12 16:30 UTC, bbrks requested changes

2019-06-12 16:30 UTC, bbrks commented on rest/server_context.go
> +		RFC3339:              time.Now().Format(time.RFC3339),
Let's move the `time.Now()` call out so we do it once (it's issuing a syscall for each one), and format the result of it separately.

2019-06-12 16:30 UTC, bbrks commented on rest/server_context.go
> +		RFC3339              string          `json:"RFC3339"`
lowercase the json field for consistency: `rfc3339_timestamp`

2019-06-13 11:29 UTC, bbrks approved these changes

2019-06-13 16:34 UTC, adamcfraser requested changes

2019-06-13 16:34 UTC, adamcfraser commented on rest/server_context.go
> +		UnixEpocTimestamp int64           `json:"unix_epoch_timestamp"`
Fix typo, and maybe pull struct out.

2019-06-14 16:33 UTC, adamcfraser approved these changes

2019-06-14 16:34 UTC, merged