CBG-409: Reduce per-doc import logging
couchbaselabs/sync_gateway pull request #4154
Opened 2019-06-14 11:18 UTC by JRascagneres

2019-06-14 16:32 UTC, adamcfraser requested changes

2019-06-14 16:32 UTC, adamcfraser commented on db/import.go
> +		db.DbStats.SharedBucketImport().Set(base.StatKeyImportHighSeq, base.ExpvarUInt64Val(docOut.syncData.Sequence))
Switch to int64(docOut.syncData.Sequence) for reduced overhead, and probably improved visibility in the event we hit a bug that caused sequence to overflow int64.

2019-06-17 11:25 UTC, bbrks approved these changes

2019-06-17 16:05 UTC, adamcfraser approved these changes

2019-06-17 16:05 UTC, merged