CBG-407: Fix chan_cache_active_revs stat
couchbaselabs/sync_gateway pull request #4155
Opened 2019-06-14 12:52 UTC by JRascagneres

2019-06-14 16:26 UTC, adamcfraser requested changes

2019-06-14 16:26 UTC, adamcfraser commented on db/channel_cache_single.go
> +		c.statsMap.Add(base.StatKeyChannelCacheRevsActive, int64(len(changes)))
```suggestion
	for _, change := range changes {
		c.cachedDocIDs[change.DocID] = struct{}{}
		c.UpdateCacheUtilization(change, 1)
	}
```

2019-06-14 16:26 UTC, adamcfraser commented on db/channel_cache_single.go
> +		c.statsMap.Add(base.StatKeyChannelCacheRevsActive, int64(len(changes)))
To minimize the number of iterations through the set, group these together and remove the call to c.addDocIDs (and remove the unused addDocIDs helper altogether).

2019-06-17 11:29 UTC, bbrks approved these changes

2019-06-17 16:06 UTC, adamcfraser approved these changes

2019-06-17 16:06 UTC, merged