Update Dockerfile base image
couchbaselabs/sync_gateway pull request #4163
Opened 2019-06-19 13:36 UTC by hubgit

The Sync Gateway code uses `math.Round` which was only added in Go 1.10, so the base image for the Dockerfile needs to be at least `golang:1.10-stretch`. 

https://github.com/couchbase/sync_gateway/blob/e19d433f07165b468cee177081380d34923e03ef/db/channel_cache.go#L97-L98

This sets it to the latest image, `golang:1.12-stretch`.

Without this, building the Docker image fails with this error:

```
godeps/src/github.com/couchbase/sync_gateway/db/channel_cache.go:97: undefined: math.Round
```

2019-06-19 13:47 UTC, bbrks requested changes

2019-06-19 13:47 UTC, bbrks commented on Dockerfile
> +FROM golang:1.12-stretch as builder
We've not tested Sync Gateway with this version of Go yet, both in terms of QE but also performance testing. Let's stick with the latest version we've ran through QE/Perf, defined in `product-config.json`

https://github.com/couchbase/sync_gateway/blob/de03c305e8340a1c04db9216c2c70c1c67590c3f/manifest/product-config.json#L9

```suggestion
FROM golang:1.11.5-stretch as builder
```

2019-06-19 16:59 UTC, bbrks approved these changes
Thanks for the contribution @hubgit!

In order to merge your PR, you will need to sign the Couchbase CLA, and we can get it merged.

https://developer.couchbase.com/open-source-projects#how-to-contribute-code

2019-06-20 08:41 UTC, hubgit commented
Thanks @bbrks - I've signed the CLA now.

2019-06-20 10:51 UTC, merged