CBG-415: Improve raw endpoint for support utility
couchbaselabs/sync_gateway pull request #4183
Opened 2019-06-27 13:26 UTC by JRascagneres

2019-06-27 14:14 UTC, bbrks requested changes

2019-06-27 14:14 UTC, bbrks commented on db/change_cache.go
> +				// If SyncData is nil, or if this was not an SG write, attempt to import
```suggestion
				// If syncData is nil, or if this was not an SG write, attempt to import
```

2019-06-27 14:14 UTC, bbrks commented on db/design_doc.go
> +	// SyncData specifies the path to Sync Gateway sync metadata used in the map function -
```suggestion
	// syncData specifies the path to Sync Gateway sync metadata used in the map function -
```

2019-06-27 14:14 UTC, bbrks commented on rest/admin_api.go
> +	salt := h.getQuery("salt")
Should the default salt be randomised on each call? I think that's how sgcollect_info does it for an undefined salt.

2019-06-27 14:14 UTC, bbrks commented on rest/admin_api.go
> +		h.response.Write([]byte(`, "doc":`))
Nesting the doc body under `"doc"` feels a little wrong to do here, given the raw document is typically at the root. Perhaps we could iterate over each element in doc.Body() and append it to the JSON instead?

2019-06-27 14:14 UTC, bbrks commented on base/util.go
> +	h.Write([]byte(string + salt))
The sgcollect_info version has the salt as the first element, and then the data. We'll need to try and make sure these things hash the same way.

```suggestion
	h.Write([]byte(salt + str))
```

2019-06-27 14:14 UTC, bbrks commented on base/util.go
> +func Sha1HashString(string string, salt string) string {
```suggestion
func Sha1HashString(str string, salt string) string {
```

2019-06-27 18:13 UTC, bbrks requested changes

2019-06-27 18:13 UTC, bbrks commented on db/document.go
> +		Attachments:     doc.Attachments,
Attachment names are probably considered UserData actually after reviewing this list.

2019-06-28 16:47 UTC, adamcfraser requested changes

2019-06-28 16:47 UTC, adamcfraser commented on rest/doc_api_test.go
> +			getRawResponse := rt.SendAdminRequest("GET", fmt.Sprintf("/db/_raw/%s?redact=false", test.name), "")
Add some tests for the new functionality.

2019-06-28 16:47 UTC, adamcfraser commented on db/document.go
> +		syncData.Access[base.Sha1HashString(k, salt)] = v
I think 'v' is a channel name here, which would need to get hashed as well. (same in the RoleAccess case below)

2019-06-28 16:47 UTC, adamcfraser commented on db/document.go
> +	syncData := SyncData{
Maybe just stick a comment above this describing what's being copied and why.

2019-06-28 16:47 UTC, adamcfraser commented on db/document.go
> +func (doc *SyncData) HashRedact(salt string) SyncData {
Using 'doc' for *SyncData as it's usually used for 'document' in the code - would make it clearer to just use 'sd' or something.

2019-06-28 16:47 UTC, adamcfraser commented on db/document.go
> +func (doc *document) GetSyncData() SyncData {
Is this accessor needed, now that the struct is public?

2019-07-04 16:23 UTC, adamcfraser approved these changes

2019-07-04 16:23 UTC, merged