CBG-474: Write Benchmark for GetRev and Patching
couchbaselabs/sync_gateway pull request #4280
Opened 2019-10-19 17:56 UTC by JRascagneres

2019-10-21 13:11 UTC, bbrks requested changes
As discussed I think this set of tests are good. They show areas we might want to improve in the future (specifically around the cost of large documents).

Some minor comments left for tidy up.

2019-10-22 16:27 UTC, adamcfraser commented
@JRascagneres Can you post the benchmark output on the PR for reference?

2019-10-22 16:29 UTC, bbrks approved these changes

2019-10-22 16:29 UTC, merged

2019-10-24 15:24 UTC, bbrks commented
> @JRascagneres Can you post the benchmark output on the PR for reference?

Updated original description with benchmark runs from my macbook.