CBG-566: Fail early if revid missing replicator2
couchbaselabs/sync_gateway pull request #4302
Opened 2019-10-30 17:22 UTC by JRascagneres

2019-10-30 21:13 UTC, adamcfraser requested changes

2019-10-30 21:13 UTC, adamcfraser commented on rest/doc_api.go
> +	generation++
Could you leave this as it was, and just make the change suggested below?  Feels a bit more straightforward.

2019-10-30 21:13 UTC, adamcfraser commented on rest/doc_api.go
> +	history = append([]string{newDoc.RevID}, history...)
```suggestion
	history := []string{newDoc.RevID}
	if parentRev != "" {
	   history = append(history, parentRev)
	}
```

2019-10-31 20:24 UTC, JRascagneres commented
Not entirely sure how I missed the much more straight forward option but done!

2019-10-31 20:39 UTC, adamcfraser approved these changes

2019-10-31 20:58 UTC, merged