CBG-557: Increment REST read stat on replicator2
couchbaselabs/sync_gateway pull request #4312
Opened 2019-11-01 21:05 UTC by JRascagneres

READ was already satisfied

2019-11-05 13:32 UTC, bbrks approved these changes
LGTM

2019-11-05 17:14 UTC, adamcfraser requested changes

2019-11-05 17:14 UTC, adamcfraser commented on rest/doc_api.go
> +	h.db.DbStats.StatsDatabase().Add(base.StatKeyNumDocReadsRest, 1)
Incrementing the stat after response.Write for consistency with handleGetDoc would be preferable, I think.

2019-11-06 17:03 UTC, adamcfraser approved these changes

2019-11-06 17:04 UTC, merged