CBG-508 processEntry benchmarks and optimizations
couchbaselabs/sync_gateway pull request #4321
Opened 2019-11-06 16:33 UTC by adamcfraser

Optimizations to minimize time spent inside processEntry, the locking component of cache DCP processing.
 - Remove info-level logging inside lock
 - Switch expvar updates to internal stat updates, pushed to expvars at calculation time
 - Avoid unbounded growth of receivedSequences by deleting from set when sequence has been processed, and recognizing already processed as received.  receivedSequences continues to identify received, pending sequences

Includes benchmarks for processEntry/DocChanged.

Pending review of final toy build: http://perf.jenkins.couchbase.com/job/syncgteway-hebe-new/1482/

2019-11-08 07:42 UTC, adamcfraser commented
Toy build run with additional diagnostics for processEntry timing show the following improvements (200k channels):

|Step|Before|After|
|---|---|---|
| ProcessEntry, acquire mutex| 55525 ns | 16367 ns | 
| ProcessEntry, post-mutex | 36572 ns | 3723 ns |
| ProcessEntry, total | 92097 ns | 20090 ns |

At this point, processEntry is no longer a major contributor to the mutex profile.  Additional work may be needed to further reduce mutex contention (for non-processEntry functionality that acquires the lock).

2019-11-08 21:35 UTC, bbrks requested changes
Haven't had time to read through benchmarks - but read through rest - spotted one thing.

2019-11-08 21:35 UTC, bbrks commented on db/change_cache.go
> +	}
This doesn't seem to be doing anything. `oldestPendingSequence` is never used after this.

2019-11-09 15:14 UTC, bbrks approved these changes

2019-11-11 03:53 UTC, adamcfraser commented
Rebased on master.

2019-11-11 13:07 UTC, bbrks approved these changes

2019-11-12 17:41 UTC, merged