CBG-549: SGCollect collects stderr and stdout Linux
couchbaselabs/sync_gateway pull request #4329
Opened 2019-11-11 22:40 UTC by JRascagneres

This should allow stderr and stdout errors to be collected on Linux systems.

I wasn't able to find a windows equivalent after searching through the CBCollect info source code.

2019-11-12 11:34 UTC, bbrks commented
@JRascagneres this is what I found when I was looking for a Windows equivalent:

https://github.com/couchbase/ns_server/blob/f94b3e0d2e2015a179ead414cdcac17f6b2baa7c/cbcollect_info#L776-L793

2019-11-12 12:39 UTC, bbrks requested changes
See comment above ^ for Windows logs

2019-11-12 23:22 UTC, JRascagneres commented
@bbrks Yeah, sure, that appears to be already present in SGCollect though. I'll make a build a give it a test on windows.

2019-11-13 09:30 UTC, bbrks approved these changes
The change looks good.

Can you post which distros/OSes you tested on?

2019-11-14 13:09 UTC, bbrks commented
I think we need to verify Windows is capturing console logging as part of this ticket.

There's a lot of special handling around the Windows service, and none of us are overly familar with Windows either.
I'm not fully confident we're doing the right thing to get console logging output to the Windows event log.

https://github.com/couchbase/sync_gateway/tree/master/service/sg-windows

2019-11-15 01:13 UTC, JRascagneres commented
@bbrks I might be missing something but I've had a google around and a lot of people are saying its not possible to capture the stdout and stderr output of a windows service unless the service itself redirects the output. I might be missing something though.

2019-11-18 23:22 UTC, bbrks commented
It looks like the library we're using for the Windows service script [has the ability to log to the event log](https://github.com/kardianos/service/blob/4df36c9fc1c6ac86231851ad6fa5627e184c94e5/service_windows.go#L430-L436), and I'm fairly sure that when we run the service via `exec`, we have the ability to set cmd.Stdout/cmd.Stderr to something else. A small wrapper around the event log stuff to get an `io.Writer` compatible method seems doable.

https://github.com/couchbase/sync_gateway/blob/05d512648bc96b3721ca4c3f183d615406b168d6/service/sg-windows/sg-service/sg-service.go#L22

2019-11-20 01:21 UTC, JRascagneres commented
Okay. Opted to pipe `stderr` and `stdout` to Event Log at info level on Windows. As `SGCollect` only reads Event Log info at above info level non-inclusive and so these won't show up.
Added a new `SGCollect` query where it will pull all levels where the service is called `SyncGateway`

2019-11-20 11:19 UTC, bbrks approved these changes
Looks good

2019-11-20 17:39 UTC, merged