CBG-558: Integrate go benchmarks into jenkins [Using To Trigger Jenkins Job]
couchbaselabs/sync_gateway pull request #4335
Opened 2019-11-13 01:02 UTC by JRascagneres

2019-11-14 16:43 UTC, bbrks commented
I've not had much chance to think about what graphs we'd like to see like we'd talked about.

Maybe the Plot plugin is the wrong approach for large sets of benchmarks, and something more interactive like the links I sent may be a better solution, but likely requires writing some kind of tool to parse Go benchmark output into a format these tools can understand.

https://plugins.jenkins.io/benchmark
https://plugins.jenkins.io/performance

2019-11-14 19:53 UTC, bbrks commented
Just to clarify my above comment - if we don't think Plot is the right approach, lets restrict this particlar issue to only running benchmarks and logging results to the Jenkins console output. We can plan what to do with the results later if there's more work involved.

2019-11-15 01:21 UTC, JRascagneres commented
@bbrks Okay yeah sounds good. I'll get on that. To be honest without some form of interactivity I think the plots would become a real mess to the point where they'd probably be pretty useless

2019-11-15 11:40 UTC, bbrks commented
From Slack:
Turns out the tool we use to parse test output also now supports benchmarks!
https://github.com/jstemmer/go-junit-report

So I think we need:
a) Another stage in the pipeline to run only benchmarks (no tests) and emit a benchmark output file
b) Pipe that file into go-junit-report like we do for tests to get a JUnit XML report for the benchmarks
c) Feed that outputted JUnit xml report into the Performance plugin https://plugins.jenkins.io/performance

2019-11-15 23:58 UTC, bbrks commented
Just FYI, we can use the `perfReport` command to publish, as per the docs: https://jenkinsci.github.io/performance-plugin/Reporting.html

The junit pipeline command AFAIK only deals with tests.

2019-11-16 00:06 UTC, JRascagneres commented
> Just FYI, we can use the `perfReport` command to publish, as per the docs: https://jenkinsci.github.io/performance-plugin/Reporting.html
> 
> The junit pipeline command AFAIK only deals with tests.

Thanks!

2019-11-19 21:00 UTC, JRascagneres commented
As per slack opted to just print benchmarks to the console for now. Issue is I'm piping to a file so that we can archive it, however, it appears we're having issues due to the logging benchmark I think the logging is overflowing. I think we need to look at limiting that. This would also explain why less stats showed up with the graphs

2019-11-19 23:45 UTC, bbrks commented
Did you have a separate branch for those benchmark speedups we talked about? I have a Git stash that already fixes the logging benchmark issues

2019-11-20 00:42 UTC, JRascagneres commented
@bbrks Just pushed up the changes made to `BenchmarkUnmarshalBody` but haven't made changes to the logging? What changes did you make there?

2019-11-20 11:13 UTC, bbrks commented
I wrote a `SetUpBenchmarkLogging` function to use that still makes the logging functions run, but just doesn't output it anywhere.

```diff
diff --git a/base/util_testing.go b/base/util_testing.go
index f14bab77..b2bcac27 100644
--- a/base/util_testing.go
+++ b/base/util_testing.go
@@ -3,6 +3,7 @@ package base
 import (
        "bytes"
        "fmt"
+       "io/ioutil"
        "log"
        "math/rand"
        "os"
@@ -549,6 +550,21 @@ func DisableTestLogging() (teardownFn func()) {
        return setTestLogging(LevelNone, KeyNone, caller)
 }

+// SetUpBenchmarkLogging will set the given log level and key, and do log processing for that configuration,
+// but discards the output, instead of writing it to console.
+func SetUpBenchmarkLogging(logLevel LogLevel, logKeys LogKey) (teardownFn func()) {
+       teardownFnOrig := setTestLogging(logLevel, logKeys, "")
+
+       // discard all logging output for benchmarking (but still execute logging as normal)
+       consoleLogger.logger.SetOutput(ioutil.Discard)
+
+       return func() {
+               // revert back to original output
+               consoleLogger.logger.SetOutput(consoleLogger.output)
+               teardownFnOrig()
+       }
+}
+
 func setTestLogging(logLevel LogLevel, logKeys LogKey, caller string) (teardownFn func()) {
        initialLogLevel := LevelInfo
        initialLogKey := KeyHTTP
```

2019-11-20 11:21 UTC, bbrks requested changes
Latest comment update suggests we'll just log benchmark results to job console output, which is fine by me, but can't see that update in the Jenkinsfile.

2019-11-20 17:52 UTC, bbrks requested changes

2019-11-20 17:52 UTC, bbrks commented on base/logging_test.go
> +	defer SetUpBenchmarkLogging(LevelInfo, KeyAll)()
Set default+CRUD log key at the start

```suggestion
	defer SetUpBenchmarkLogging(LevelInfo, KeyHTTP|KeyCRUD)()
```

and remove `consoleLogger.LogKey.Enable` line below

2019-11-20 17:52 UTC, bbrks commented on rest/api_test.go
> +	defer base.SetUpBenchmarkLogging(base.LevelInfo, base.KeyAll)()
Use default logkey:

```suggestion
	defer base.SetUpBenchmarkLogging(base.LevelInfo, base.KeyHTTP)()
```

2019-11-20 17:52 UTC, bbrks commented on rest/api_test.go
> +	defer base.SetUpBenchmarkLogging(base.LevelInfo, base.KeyAll)()
Use default logkey:

```suggestion
	defer base.SetUpBenchmarkLogging(base.LevelInfo, base.KeyHTTP)()
```

2019-11-20 17:52 UTC, bbrks commented on Jenkinsfile
> +                    sh "go test -timeout=20m -count=1 -run='^\044' -bench=Benchmark -test.benchmem -v ${SGW_REPO}/... > reports/benchmark.out || true"
The "standard" 'skip tests' flag I've seen is `-`
The "standard" 'all' flag I've seen is `.`
Don't need `test` prefix on benchmem flag

```suggestion
                    sh "go test -timeout=20m -count=1 -run=- -bench='.' -benchmem -v ${SGW_REPO}/... > reports/benchmark.out || true"
```

2019-11-21 12:23 UTC, bbrks requested changes
Looks pretty good. Almost there.

Just a couple more benchmarks that are explicitly doing logging stuff, which we might want to fix while we're here:

- `BenchmarkProcessEntry`
- `BenchmarkDocChanged`

2019-11-21 12:23 UTC, bbrks commented on Jenkinsfile
> +                        sh "go test -timeout=20m -count=1 -run=- -bench=. -benchmem -v ${SGW_REPO}/... | tee benchmark.out || true"
We want this to return a non-zero exit code in the case of a failure for the `warnError` wrapper to pick up.

```suggestion
                        sh "go test -timeout=20m -count=1 -run=- -bench=. -benchmem -v ${SGW_REPO}/... | tee benchmark.out"
```

2019-11-21 15:37 UTC, bbrks approved these changes
This all looks good 👍

2019-11-21 22:33 UTC, merged