CBG-591: Code coverage for rest package (admin_api.go) [WIP]
couchbaselabs/sync_gateway pull request #4337
Opened 2019-11-14 01:03 UTC by sarathkumarsivan

- Add new tests for endpoints/handlers that don't have coverage:
  handleCreateDB
  handleGetConfig
  handlePutDbConfig

2019-11-18 12:30 UTC, bbrks requested changes
Left comments on some things in the PR.

But also as mentioned in Slack - the race detector is crashing when trying to run tests on the `rest` package. I can reproduce the issue locally, but I'm not sure why it's happening.

```
2019-11-18T12:15:06.757Z [INF] Sync: c:[3be06dbe] Sent 4 changes to client, from seq 101
2019-11-18T12:15:06.757Z [INF] Sync: c:[3be06dbe] Sent all changes to client
ThreadSanitizer: sync allocator overflow (65536*1024). Dying.
FAIL	github.com/couchbase/sync_gateway/rest	198.153s
FAIL
```

2019-11-18 18:45 UTC, sarathkumarsivan commented on rest/admin_api_test.go
> +	assert.Contains(t, resp.Body.String(), "1-123")
Makes sense; this has been added to the latest revision.

2019-11-18 20:16 UTC, sarathkumarsivan commented on rest/admin_api_test.go
> +	assert.Empty(t, respBody["kv_tls_port"])
Yeah, this is not adding any value and these assertions are obsolete; let's remove this.

2019-11-18 20:16 UTC, sarathkumarsivan commented on rest/admin_api_test.go
> +	fakeConfigURL := "http://couchbase.xdcr.com:4985"
Yeah; this is doable, I will keep it as localhost.

2019-11-18 20:40 UTC, sarathkumarsivan commented on rest/admin_api_test.go
> +	respBody := db.Body{}
The body is instantiated to get rid of the warning nil from IDE; but this is really not required. This will be fixed in the latest commit;

2019-11-18 20:41 UTC, sarathkumarsivan commented on rest/admin_api_test.go
> +	assert.False(t, facebook["Register"].(bool))
Yeah, that would be a better choice; and we can check the sync function value from the response body; It is committed to the latest revision.

2019-11-18 20:49 UTC, sarathkumarsivan commented on rest/sgcollect.go
> +	err           error
This is changed to pathError.

2019-11-19 17:27 UTC, adamcfraser approved these changes

2019-11-19 17:27 UTC, merged