Add test to verify DCP feed names do not exceed 200 chars
couchbaselabs/sync_gateway pull request #4470
Opened 2020-01-17 18:33 UTC by bbrks

Seems we're well off the limit, even with cbgt names prepended to our feed IDs.

```
=== RUN   TestGenerateDcpStreamName/SG
    --- PASS: TestGenerateDcpStreamName/SG (0.00s)
        dcp_common_test.go:25: generated name of length 65: SG-v-2.8-commit-1e72cde-uuid-6606e6e4-3957-11ea-9835-acde48001122
=== RUN   TestGenerateDcpStreamName/cbgtSG
    --- PASS: TestGenerateDcpStreamName/cbgtSG (0.00s)
        dcp_common_test.go:36: generated name of length 76: sg:SG-v-2.8-commit-1e72cde-uuid-6606f1b6-3957-11ea-9835-acde48001122-a310e77
=== RUN   TestGenerateDcpStreamName/SGI
    --- PASS: TestGenerateDcpStreamName/SGI (0.00s)
        dcp_common_test.go:25: generated name of length 66: SGI-v-2.8-commit-1e72cde-uuid-6606f3fa-3957-11ea-9835-acde48001122
=== RUN   TestGenerateDcpStreamName/cbgtSGI
    --- PASS: TestGenerateDcpStreamName/cbgtSGI (0.00s)
        dcp_common_test.go:36: generated name of length 78: sg:SGI-v-2.8-commit-1e72cde-uuid-6606f5d0-3957-11ea-9835-acde48001122-7e80ffa9
```

2020-01-23 18:32 UTC, adamcfraser commented
That looks like the naming for the non-sharded DCP import feed (which is used when running in CE).  

The name for the sharded DCP import feed is based on the index name, which is currently including the database name:
https://github.com/couchbase/sync_gateway/blob/master/base/dcp_sharded.go#L119

Resulting in DCP stream names like:
sg:dbname_import_741a51a3df6792a9_3a2c2268-6bfb5b0e

ValidateDatabaseName doesn't apply any length restrictions, so there's a potential issue here I think.

I believe a db-scoped index name is still required to avoid cbgt collisions when running multiple databases on a single node.  However, I don't believe we're using the index name to do a lookup of the database instance any more.  If that's correct, we could switch from using the db name to something unique and fixed length.

2020-01-23 18:33 UTC, adamcfraser requested changes
Added a comment on PR - I don't think this covers the sharded index case.

2020-01-27 14:46 UTC, bbrks commented
Hmm, thanks for catching that. There's no obvious single place to use the same logic that CBGT is using to build up their index DCP names, but hopefully this update is sufficient.

I've ran our dbNames through a crc32c hash, instead of using another UUID.
This also catches a gap between valid db names, but invalid index names (containing a dollar sign) that I've included a test for.


## Before
```
=== RUN   TestDCPNameLength/cbgt-index-db1
    --- PASS: TestDCPNameLength/cbgt-index-db1 (0.00s)
        dcp_common_test.go:68: generated name of length 38: db1_167dfc5a122bde31_f47365c5-2e5220ce
=== RUN   TestDCPNameLength/cbgt-index-db1$a
    --- FAIL: TestDCPNameLength/cbgt-index-db1$a (0.00s)
        dcp_common_test.go:62: 
            	Error Trace:	dcp_common_test.go:62
            	Error:      	Should be true
            	Test:       	TestDCPNameLength/cbgt-index-db1$a
            	Messages:   	index name is not a valid cbgt index name
        dcp_common_test.go:68: generated name of length 40: db1$a_167dfc5a122bde31_f47365c5-2e5220ce
=== RUN   TestDCPNameLength/cbgt-index-123
    --- FAIL: TestDCPNameLength/cbgt-index-123 (0.00s)
        dcp_common_test.go:62: 
            	Error Trace:	dcp_common_test.go:62
            	Error:      	Should be true
            	Test:       	TestDCPNameLength/cbgt-index-123
            	Messages:   	index name is not a valid cbgt index name
        dcp_common_test.go:68: generated name of length 38: 123_167dfc5a122bde31_f47365c5-2e5220ce
=== RUN   TestDCPNameLength/cbgt-index-db1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    --- FAIL: TestDCPNameLength/cbgt-index-db1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa (0.00s)
        dcp_common_test.go:68: generated name of length 245: db1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_167dfc5a122bde31_f47365c5-2e5220ce
        dcp_common_test.go:70: 
            	Error Trace:	dcp_common_test.go:70
            	Error:      	Should be true
            	Test:       	TestDCPNameLength/cbgt-index-db1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
            	Messages:   	len(cbgtIndexDCPName)=245 is exceeds max allowed 200 chars: db1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_167dfc5a122bde31_f47365c5-2e5220ce
```

## After
```
=== RUN   TestDCPNameLength/cbgt-index-db1
    --- PASS: TestDCPNameLength/cbgt-index-db1 (0.00s)
        dcp_common_test.go:68: generated name of length 53: db0xbdcaa3f7_index_167dfc5a122bde31_f47365c5-2e5220ce
=== RUN   TestDCPNameLength/cbgt-index-db1$a
    --- PASS: TestDCPNameLength/cbgt-index-db1$a (0.00s)
        dcp_common_test.go:68: generated name of length 53: db0xdc21f9ce_index_167dfc5a122bde31_f47365c5-2e5220ce
=== RUN   TestDCPNameLength/cbgt-index-123
    --- PASS: TestDCPNameLength/cbgt-index-123 (0.00s)
        dcp_common_test.go:68: generated name of length 53: db0x107b2fb2_index_167dfc5a122bde31_f47365c5-2e5220ce
=== RUN   TestDCPNameLength/cbgt-index-db1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    --- PASS: TestDCPNameLength/cbgt-index-db1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa (0.00s)
        dcp_common_test.go:68: generated name of length 53: db0x9df8b49f_index_167dfc5a122bde31_f47365c5-2e5220ce
```

2020-02-03 18:05 UTC, adamcfraser requested changes

2020-02-03 18:05 UTC, adamcfraser commented on base/dcp_sharded.go
> +	indexName := GenerateIndexName(dbName)
Add some logging to allow support to determine dbname from indexName.

2020-02-05 17:34 UTC, adamcfraser approved these changes

2020-02-05 17:34 UTC, merged