CBG-728 - Backport CBG-727 to 2.7.1
couchbaselabs/sync_gateway pull request #4500
Opened 2020-02-18 20:17 UTC by bbrks

CBG-727 - Uptake fix for non-standard port using couchbase(s) scheme (#4496)

2020-02-18 22:54 UTC, adamcfraser submitted a review, later dismissed

2020-02-18 22:57 UTC, adamcfraser requested changes
Doesn't this change need to go into the 2.7.1 manifest on master, as opposed to the default manifest on the 2.7.1 branch?

2020-02-18 23:02 UTC, bbrks commented
> Doesn't this change need to go into the 2.7.1 manifest on master, as opposed to the default manifest on the 2.7.1 branch?

Oops! Yes it does :) That serves me right for cherry-picking everything in a rush :D

2020-02-19 16:52 UTC, adamcfraser approved these changes

2020-02-19 16:52 UTC, merged