CBG-741
couchbaselabs/sync_gateway pull request #4528
Opened 2020-03-12 14:49 UTC by bbrks

Draft PR for initial read-only/in-memory portion of pre-2.5 _attachment migration.

Some tests are currently failing because they expect the write-upgrade to happen for GetActive requests (fetch active, write an update, and return that update).

2020-03-16 16:22 UTC, adamcfraser requested changes

2020-03-16 16:22 UTC, adamcfraser commented on db/revision_cache_interface.go
> +		attachments = pre25Atts
If attachments are already non-empty (from doc.Attachments), should do a merge to be defensive.  

In the case that an attachment exists in both, use the one with higher revpos.

2020-03-17 20:28 UTC, adamcfraser requested changes

2020-03-18 14:56 UTC, bbrks commented
Tweaked the approach based on discussion yesterday, and evaluating usages of getRevision to avoid processing _attachments over and over, and doing it in many places.

**Black arrows** are all calls down into getRevision.
**Red underlines** are where we're injecting a merged (pre2.5/backup rev "_attachments", and docRev attachments) back in.
**Blue arrows** are sending merged attachment metadata separately (with cleaned bodies).
**Red square** is where we're unmarshalling if inline attachments present, and remarshalling a clean body.

![IMG_20200318_141819](https://user-images.githubusercontent.com/1525809/76973562-0616fe80-6928-11ea-8e9d-35fc6f983f2e.jpg)

2020-03-18 16:18 UTC, adamcfraser approved these changes

2020-03-18 16:53 UTC, merged