CBG-803: Support for OIDC provider config refresh
couchbaselabs/sync_gateway pull request #4563
Opened 2020-05-05 05:27 UTC by sarathkumarsivan

Changes to support OpenID Connect Provider Metadata

2020-05-12 11:50 UTC, bbrks requested changes

2020-05-12 11:50 UTC, bbrks commented on auth/oidc.go
> +	mux sync.Mutex
Typically name locks after the resource they affect, i.e.:

```suggestion
	providerLock sync.Mutex
```

2020-05-12 11:50 UTC, bbrks commented on auth/oidc.go
> +					provider, err = oidc.NewProvider(context.Background(), issuer)
Haven't we already done this work on line 489?

2020-05-12 11:50 UTC, bbrks commented on auth/oidc.go
> +	providerConfigSyncInterval = time.NewTicker(1 * time.Second)
Refreshing each provider once per second seems SUPER aggressive...

For comparison, the old library had a lower bound of 1 minute, and an upper bound of 24 hours, and used them like this:

https://github.com/coreos/go-oidc/blob/e860bd55bfa7d7cb35d30d26a167982584f616b0/oidc/provider.go#L591-L604

2020-05-12 11:50 UTC, bbrks commented on auth/oidc.go
> +			return nil, nil, shouldSync, err
```suggestion
			return nil, nil, false, err
```

2020-05-12 11:50 UTC, bbrks commented on auth/oidc.go
> +	return
Why do we need to loop whilst locking/unlocking to check? Can we not use an RWMutex for synchronization? (i.e. many readers blocked waiting for one writer to unlock)

2020-05-12 11:50 UTC, bbrks commented on auth/oidc.go
> +func (client *OIDCClient) SyncProviderConfig(issuer string) {
Do we have an approach to test the provider sync/refresh mechanism?

I think it should be feasible to write a test provider that changes configuration and override the sync time for testing purposes.

2020-06-02 01:27 UTC, sarathkumarsivan commented
Closing this pul request; the changes can be tracked under the new PR.

2020-06-02 01:27 UTC, closed without merging