CBG-876: Include Bearer prefix when sending token base authentication…
couchbaselabs/sync_gateway pull request #4586
Opened 2020-05-21 16:21 UTC by sarathkumarsivan

- Move getRSASigner() from util_testing.go to oidc_test.go.
- Include Bearer prefix when sending token base authentication request in OIDC E2E tests.
- Attach public keys and signer to the mockAuthServer.
- Add keysHandler to expose the public keys to validate a JSON Web Token (JWT) issued.
- Include makeToken method on mockAuthServer to creates a default token.
- E2E test that checks OpenID Connect Implicit Flow.

2020-05-21 22:04 UTC, adamcfraser requested changes

2020-05-21 22:04 UTC, adamcfraser commented on rest/oidc_api_test.go
> +			assert.True(t, 86395 <= sessionExpiry && 86400 >= sessionExpiry, "session expiry is not within 5 seconds of 24 hours")
24h is the default SG session timeout (kDefaultSessionTTL).   Is that what we want to be testing here?  It's a bit unexpected in  what appears to be an OIDC test.

2020-05-22 19:59 UTC, sarathkumarsivan reviewed
- Added comments against BearerToken stating that it is used for setting JWT token type as well as the prefix for the Authorization HTTP header.
- Refactored makeToken method to keep one property per line while building the claims for making auth token.
- Refactored getCookie function to use enhanced for loop.
- Since we're already checking whether the DefaultCookieName exists, skip the check for kDefaultSessionTTL and make sure the response body has the expected details like username, channels, authentication_handlers etc.
- Refactored makeToken method to accept claimSet which contains both primary and secondary claims to make it convenient to adjust claims from the caller for specific use cases. 
- Included additional unit test cases to cover the edge cases.

2020-05-22 19:59 UTC, sarathkumarsivan commented on rest/oidc_api_test.go
> +func (s *mockAuthServer) makeToken() (string, error) {
Makes sense. The makeToken method has been refactored to accept claimSet which contains both primary and secondary claims. Now it is convenient to adjust claims from the caller for specific use cases. Also included additional unit test cases to cover the edge cases.

2020-05-22 21:49 UTC, adamcfraser commented on rest/oidc_api_test.go
> +			request.Header.Add("Authorization", BearerToken+" "+authResponseActual.IDToken)
I was wondering if that's what was going on.  Filed CBG-879 to force tests to opt-in to GUEST usage.

2020-05-22 21:53 UTC, adamcfraser approved these changes

2020-05-22 21:53 UTC, merged