CBG-1053: Adhoc replicationStatus panic fix
couchbaselabs/sync_gateway pull request #4757
Opened 2020-09-07 12:17 UTC by JRascagneres

2020-09-07 16:03 UTC, bbrks approved these changes, later dismissed
LGTM

2020-09-08 03:40 UTC, adamcfraser requested changes

2020-09-08 03:40 UTC, adamcfraser commented on db/active_replicator.go
> +	if pullCheckpoint != nil && pullCheckpoint.Status != nil {
This fix looks good, but I think we should also be setting LastSeqPull and LastSeqPush based on checkpoint.LastSeq when using LoadReplicationStatus, in the case where the unmarshalled status is nil.

2020-09-08 17:11 UTC, adamcfraser approved these changes

2020-09-08 17:11 UTC, merged