CBG-1074: Grafana README updates
couchbaselabs/sync_gateway pull request #4773
Opened 2020-09-14 18:23 UTC by JRascagneres

Grafana updates to change the name of the SGR2 row to the customer facing name and to add troubleshooting steps for jb install issues.

2020-09-14 19:30 UTC, rajagp requested changes
Minor suggestion.

2020-09-14 19:30 UTC, rajagp commented on examples/grafana/README.md
> +The GOPATH or installation directory can be found with `echo $(go env GOPATH)`. Ensure that this directory is present in the PATH variable.
```suggestion
The GOPATH or installation directory can be found with `echo $(go env GOPATH)`. This is where `jb` will be installed. Ensure that this directory is present in the PATH variable. 
```

2020-09-15 10:52 UTC, JRascagneres commented on examples/grafana/README.md
> +The GOPATH or installation directory can be found with `echo $(go env GOPATH)`. Ensure that this directory is present in the PATH variable.
Thanks. Done

2020-09-15 16:03 UTC, adamcfraser approved these changes

2020-09-15 16:04 UTC, merged