Fix Resync RT close
couchbaselabs/sync_gateway pull request #4890
Opened 2020-12-17 17:18 UTC by JRascagneres

2020-12-17 17:45 UTC, bbrks submitted a review, later dismissed

2020-12-18 16:55 UTC, bbrks approved these changes, later dismissed

2020-12-18 17:09 UTC, adamcfraser requested changes

2020-12-18 17:09 UTC, adamcfraser commented on rest/admin_api_test.go
> +	if base.TestsDisableGSI() {
As discussed, looks like these should be getting set before running the resync on line 1331 to avoid race.

2020-12-20 20:48 UTC, adamcfraser approved these changes

2020-12-20 20:48 UTC, merged