CBG-1387 / CBG-1411: Channel Access Revocation for ISGR
couchbaselabs/sync_gateway pull request #5008
Opened 2021-05-26 15:32 UTC by JRascagneres

- Removed enable_auto_purge config option and use the existing purge on removal option
- Utilize changes response

Tested with small unit test

TODO: 
 - Waiting on a couple of additional bits to go in with CBG-1426 and CBG-1435

2021-05-27 22:31 UTC, bbrks requested changes

2021-05-28 14:14 UTC, JRascagneres commented on db/blip_handler.go
> +			deletedFlags = changesDeletedFlag(deletedIntFlag)
Yeah, thats a good plan, will implement this. I don't think we want to return an error though in the error case. I think we want to 'continue' so we continue iterating over the other changes messages.

2021-06-02 10:14 UTC, bbrks requested changes

2021-06-02 10:14 UTC, bbrks commented on rest/replicator_test.go
> +	srv := httptest.NewTLSServer(rt2.TestPublicHandler())
```suggestion
	srv := httptest.NewServer(rt2.TestPublicHandler())
```

2021-06-02 10:14 UTC, bbrks commented on rest/replicator_test.go
> +		InsecureSkipVerify:  true,
```suggestion
```

2021-06-02 10:14 UTC, bbrks commented on db/blip_handler.go
> +				deletedIntFlag, err := change[3].(json.Number).Int64()
```suggestion
				deletedIntFlag, err := v.Int64()
```

2021-06-02 10:23 UTC, bbrks requested changes
maybe this too?

2021-06-02 10:23 UTC, bbrks commented on db/blip_handler.go
> +		if missing == nil && deletedFlags&changesDeletedFlagRevoked == 0 && deletedFlags&deletedFlags&changesDeletedFlagRemoved == 0 {
```suggestion
		if missing == nil && deletedFlags&changesDeletedFlagRevoked|changesDeletedFlagRemoved == 0 {
```

2021-06-02 13:27 UTC, bbrks approved these changes, later dismissed

2021-06-02 13:33 UTC, bbrks approved these changes

2021-06-02 23:40 UTC, adamcfraser approved these changes

2021-06-02 23:44 UTC, merged