CBG-1386: Handle pruning of history
couchbaselabs/sync_gateway pull request #5018
Opened 2021-06-02 14:04 UTC by JRascagneres

Adds pruning to grant history. Rules as follows:

 - If the history entries for a role / channel are not updated in 30 days then the entire history for that role / channel will be removed.
 - Grant Pairs are pruned to maintain a maximum of 10 entries and a minimum of 1 entry. Numbers in between are calculated in order to maintain grant history no larger than 1MB. 
 Note 1MB can be exceeded if an extreme number of channels / roles have history as each requires at least 1 entry.
 
The calculation for the second rule has a unit test.

2021-06-08 13:09 UTC, bbrks requested changes

2021-06-08 13:09 UTC, bbrks commented on auth/auth_test.go
> +			assert.Equal(t, CalculateMaxHistoryEntriesPerGrant(testCase.HistoryLengthInput), testCase.MaxEntriesExpectedOutput)
expected <--> actual

```suggestion
			assert.Equal(t, testCase.MaxEntriesExpectedOutput, CalculateMaxHistoryEntriesPerGrant(testCase.HistoryLengthInput))
```

2021-06-08 13:09 UTC, bbrks commented on auth/auth_test.go
> +		},
Include these so:
- We can see where the distribution is (these numbers are ballpark, they have a fair amount of leeway in them)
- The test fails if we change things to affect the distribution too significantly

```suggestion
		{
			Name:                     "Upper bound",
			HistoryLengthInput:       3600,
			MaxEntriesExpectedOutput: 1,
		},
		{
			Name:                     "Large history length",
			HistoryLengthInput:       3330,
			MaxEntriesExpectedOutput: 3,
		},
		{
			Name:                     "Median history length",
			HistoryLengthInput:       3075,
			MaxEntriesExpectedOutput: 5,
		},
		{
			Name:                     "Small history length",
			HistoryLengthInput:       2800,
			MaxEntriesExpectedOutput: 7,
		},
		{
			Name:                     "Lower bound",
			HistoryLengthInput:       2550,
			MaxEntriesExpectedOutput: 10,
		},
```

2021-06-08 13:18 UTC, JRascagneres commented on auth/role.go
> +		grantTime := time.Unix(0, grantHistory.UpdatedAt)
Switched to Unix

2021-06-08 13:20 UTC, JRascagneres commented on base/constants.go
> +	DefaultTimedSetHistoryPruneCap      = 10
Yeah woops, left this. 
I'll add a const for the max and min.

2021-06-09 18:49 UTC, bbrks requested changes
Looks good apart from the last change for log redaction

2021-06-09 18:49 UTC, bbrks commented on auth/auth.go
> +		base.Debugf(base.KeyCRUD, "rebuildChannels: Pruned principal history on %s for %s", base.UD(princName), base.UD(strings.Join(prunedHistory, ",")))
Would be better to redact each element individually, so each channel name gets a hash, which is already supported for string slices.

```suggestion
		base.Debugf(base.KeyCRUD, "rebuildChannels: Pruned principal history on %s for %s", base.UD(princName), base.UD(prunedHistory))
```

2021-06-09 19:07 UTC, bbrks submitted a review, later dismissed

2021-06-10 22:14 UTC, adamcfraser submitted a review, later dismissed
Looks good, just some minor nits about naming.

2021-06-10 22:14 UTC, adamcfraser commented on auth/auth.go
> +	const maximumHistoryBytes = 1024 * 1024 // 1MB
All three of these constants are the same units, but that's not evident from naming.  What do you think about maximumHistoryBytes, averageHistoryKeyBytes, and averageHistoryEntryBytes?

2021-06-12 00:13 UTC, adamcfraser approved these changes

2021-06-12 00:13 UTC, merged