CBG-1522 - Additional waiting for doc deletion for TestSGR2TombstoneConflictHandling
couchbaselabs/sync_gateway pull request #5064
Opened 2021-06-24 15:29 UTC by IsaacLambat

Added waiting when a doc gets deleted

2021-06-24 15:52 UTC, JRascagneres submitted a review, later dismissed
LGTM

2021-06-24 16:10 UTC, bbrks requested changes

2021-06-24 16:10 UTC, bbrks commented on rest/replicator_test.go
> +				requireTombstone(t, tb2, "docid2")
As discussed, I'm not sure this is adding any blocking - it's just doing an immediate assertion which will either pass or fail.

2021-06-25 14:44 UTC, bbrks approved these changes

2021-06-25 14:44 UTC, merged