CBG-1453 - Removed unused code from expvar and full test file
couchbaselabs/sync_gateway pull request #5068
Opened 2021-06-25 15:24 UTC by IsaacLambat

Removed most of the code from expvar.go as it was used nowhere except in the tests.
Removed all expvar.go unit tests due to them no longer being needed.

Removed creating expvar "syncgateway" as that expvar was never called anywhere.
Initialization of SyncGatewayStats is now done when it is declared.

2021-06-25 15:26 UTC, bbrks requested changes

2021-06-25 15:26 UTC, bbrks commented on base/expvar.go
> +var SyncGatewayStats = *NewSyncGatewayStats()
I guess whats left in this file can be moved to `stats.go` now?

2021-06-25 15:50 UTC, bbrks commented on base/stats.go
> +var SyncGatewayStats = *NewSyncGatewayStats()
@JRascagneres do we still need to do `expvar.Publish(StatsGroupKeySyncGateway, &SyncGatewayStats)` ? Or is that handled by the stats framework itself now?

2021-06-25 15:57 UTC, JRascagneres requested changes
As Ben mentioned you need the keep the expvar publish line. 
Would recommend having a quick look (once thats in) at just spinning up SGW and making sure you can see stats on :4986/expvar and :4986/_metrics

2021-06-29 17:10 UTC, JRascagneres approved these changes

2021-06-29 17:37 UTC, merged