CBG-1464 Support meta option in Attachment REST API to retrieve doc ID of the attachment blob
couchbaselabs/sync_gateway pull request #5111
Opened 2021-07-19 22:07 UTC by sarathkumarsivan

Changes to include meta option in Attachment REST API to retrieve doc ID of the attachment blob.

From Lithium on, the GET /{db}/{doc}/{attachment} request supports an optional meta boolean parameter in the query string. If it’s specified as true, the response will be just the key including metadata of the attachment blob instead of raw data.

2021-07-20 13:05 UTC, bbrks requested changes
Looks good, with 1 suggestion around the JSON response.

I've changed the base to CBG-1402 until #5088 is merged for easier reviewing, since this PR is stacked on top of those commits.

2021-07-20 17:20 UTC, bbrks commented
Just noticed the litecore failure looks suspicious:

```
Push & Pull Attachments
-----------------------------------------------------------------------------------------------------------------------
/home/tests/couchbase-lite-core/Replicator/tests/ReplicatorSGTest.cc:247
.......................................................................................................................

/home/tests/couchbase-lite-core/LiteCore/tests/../../Replicator/tests/ReplicatorAPITest.hh:328: FAILED:
  CHECK( asVector(_docPullErrors) == asVector(_expectedDocPullErrors) )
with expansion:
  { "att1" } == {  }

/home/tests/couchbase-lite-core/Replicator/tests/ReplicatorSGTest.cc:270: FAILED:
  REQUIRE( doc )
with expansion:
  false
```

2021-07-20 18:13 UTC, sarathkumarsivan commented on rest/doc_api.go
> +		h.writeRawJSONStatus(http.StatusOK, bytes)
I see what you mean, this looks more cleaner. Manual JSON marshal/rawJSON step has been removed in the latest revision.

2021-08-12 10:44 UTC, bbrks approved these changes
lgtm

2021-08-12 10:44 UTC, merged