Enable gocbv2 by default
couchbaselabs/sync_gateway pull request #5139
Opened 2021-08-04 05:59 UTC by adamcfraser

Enables gocb v2 by default for everything except DCP.  Testing the full suite in this mode caught a number of bugs in the collection implementation, particularly around standardizing error types.  Beyond bug fixes, created a new CouchbaseStore interface for functionality specific to a backing Couchbase Server, and not already on the bucket interface.

Includes a transcoder for gocb v2 that is backward compatible with the gocb v1 transcoder.  (Attempted to pull that out into a separate PR, but it had too many interdependencies with the rest of the fixes and refactoring in this PR).

2021-08-09 15:31 UTC, bbrks requested changes
LGTM. Can bump manifest, and couple of non-code nitpicks then should be good to merge if there are no more changes for this branch.

2021-08-09 15:31 UTC, bbrks commented on manifest/default.xml
> +  <project name="sg-bucket" path="godeps/src/github.com/couchbase/sg-bucket" remote="couchbase" revision="c9bd104d8aa3da23fdc843f55c713bad624f4e88"/>
Update for merged PR

```suggestion
  <project name="sg-bucket" path="godeps/src/github.com/couchbase/sg-bucket" remote="couchbase" revision="08f9bc2aa1cb5cb87b9a9bc0f803ddefbc73c5f8"/>
```

2021-08-11 23:00 UTC, adamcfraser commented
Addressed PR changes but also made a couple of non-trivial changes (GetIndexes(), socket closes).  @bbrks Can you give this one more pass before I merge?

2021-08-12 12:39 UTC, bbrks approved these changes
LGTM

2021-08-12 16:51 UTC, merged