CBG-1542 - Command line flags for persistent config
couchbaselabs/sync_gateway pull request #5160
Opened 2021-08-10 11:47 UTC by IsaacLambat

- [ ] http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-integration/961/

- All of persistent config has been made to CLI flags except use_tls_client as that is being removed
- Errors are returned if there is problems parsing the CLI flags (eg. invalid duration)
- Unit tests are done to make sure all the flags work (testing every flag, and every different config type), and error when they should.
- logRotationConfig.LocalTime has been made a bool*

2021-08-10 14:12 UTC, bbrks requested changes
General approach seems reasonable but it looks like it may not be working properly.
It seems to be overwriting my config file options even with no flags set.

```
> cat cnf_bootstrap.json
{
  "bootstrap": {
    "server": "couchbases://localhost",
    "config_update_frequency": "1m",
    "username": "Administrator",
    "password": "password",
    "server_tls_skip_verify": true
  },
  "api": {
    "https": {
      "use_tls_client": false
    }
  },
  "logging": {
    "log_file_path": "/tmp/sglog",
    "console": {
      "log_level": "debug",
      "log_keys": ["HTTP","Config","CRUD","DCP","Sync"]
    }
  }
}

> go build && ./sync_gateway cnf_bootstrap.json
2021-08-10T15:08:24.557+01:00 ==== Couchbase Sync Gateway/() CE ====
2021-08-10T15:08:24.557+01:00 [INF] Loading content from [cnf_bootstrap.json] ...
2021-08-10T15:08:24.559+01:00 [INF] Config: Starting in persistent mode using config group "default"
2021-08-10T15:08:24.559+01:00 [INF] Logging: Console disabled
2021-08-10T15:08:24.559+01:00 [INF] Logging: Files to /tmp/sglog
^C%
```

...

```
> git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
> go build && ./sync_gateway cnf_bootstrap.json
2021-08-10T15:09:09.569+01:00 ==== Couchbase Sync Gateway/() CE ====
2021-08-10T15:09:09.569+01:00 [INF] Loading content from [cnf_bootstrap.json] ...
2021-08-10T15:09:09.570+01:00 [INF] Config: Starting in persistent mode using config group "default"
2021-08-10T15:09:09.570+01:00 [INF] Logging: Console to stderr
2021-08-10T15:09:09.570+01:00 [INF] Logging: Files to /tmp/sglog
2021-08-10T15:09:09.571+01:00 [INF] Logging: Console level: debug
2021-08-10T15:09:09.571+01:00 [INF] Logging: Console keys: [Config CRUD DCP HTTP Sync]
2021-08-10T15:09:09.571+01:00 [INF] Logging: Redaction level: partial
2021-08-10T15:09:09.571+01:00 [INF] Configured process to allow 5000 open file descriptors
2021-08-10T15:09:09.571+01:00 [INF] Logging stats with frequency: 1m0s
2021-08-10T15:09:13.301+01:00 [INF] Config: Successfully connected to cluster
2021-08-10T15:09:13.421+01:00 [DBG] Config+: "sg_int_0_1628517367577724000" did not contain config in group "default"
2021-08-10T15:09:13.421+01:00 [INF] Config: Updating database "db1" for bucket "b1" with new config from bucket
2021-08-10T15:09:13.421+01:00 [INF] Opening db /db1 as bucket "b1", pool "default", server <couchbases://localhost>
2021-08-10T15:09:13.421+01:00 [INF] GoCBCustomSGTranscoder Opening Couchbase database b1 on <couchbases://localhost> as user "<ud>Administrator</ud>"
2021-08-10T15:09:14.403+01:00 [INF] Successfully opened bucket b1
2021-08-10T15:09:14.424+01:00 [INF] Set query timeouts for bucket b1 to cluster:1m15s, bucket:1m15s
2021-08-10T15:09:14.424+01:00 [INF] Initializing indexes with numReplicas: 0...
2021-08-10T15:09:14.676+01:00 [INF] Verifying index availability for bucket b1...
2021-08-10T15:09:14.684+01:00 [INF] Indexes ready for bucket b1.
2021-08-10T15:09:14.684+01:00 [INF] delta_sync enabled=false with rev_max_age_seconds=86400 for database db1
2021-08-10T15:09:14.686+01:00 [INF] Created background task: "CleanAgedItems" with interval 1m0s
...
```

2021-08-16 14:46 UTC, IsaacLambat commented on rest/config_flags.go
> +				panic(fmt.Sprintf("Error: Unknown type %v for flag %v\n", rval.Type(), f.Name))
Leaving as a panic as it should never get to that stage for a user (only a developer when adding new config options but not adding a case for a new/different type). 

Let me know if you still think I should change it to just an error.

2021-08-17 15:51 UTC, bbrks requested changes
The change to the mergo transformer looks good for handling struct pointers, and the general appraoch for flags is fine for now. 

I think we should add a test that ensures flags and StartupConfig are somewhat coupled, to catch scenarios in dev/unit-test time where we add a config option but forget to add a flag.

2021-08-17 15:51 UTC, bbrks commented on rest/config.go
> +	if config.Unsupported.HTTP2 != nil && config.Unsupported.HTTP2.Enabled != nil {
👍

2021-08-17 15:51 UTC, bbrks commented on rest/config_legacy_test.go
> +			expected: StartupConfig{API: APIConfig{ServerReadTimeout: base.NewConfigDuration(time.Second)}},
Doesn't match test case name any more - but looking at the test-case again it looks like we'd want a pointer to `0` to override the original value, as it's explicitly set?

I can't remember why this stopped working. Is it related to `D` inside `ConfigDuration` not being a pointer type?

2021-08-17 15:51 UTC, bbrks commented on rest/config_flags.go
> +	return map[string]configFlag{
I'm wondering how we can catch developer-time errors like adding a new config option but forgetting to update this map, or vice versa.

Is it possible for a test to count all of the fields (including children) in StartupConfig and ensure it matches the number of elements returned by this function? That at least gives us an early-warning if we forget to update flags.

2021-08-18 16:33 UTC, adamcfraser commented on rest/changes_api.go
> +		maxHeartbeat := h.server.config.Replicator.MaxHeartbeat
Can use .Value() here (or below).

2021-08-19 11:00 UTC, bbrks approved these changes, later dismissed

2021-08-19 11:04 UTC, bbrks approved these changes

2021-08-19 11:57 UTC, merged