CBG-1583 - Made config Group ID an EE-only feature
couchbaselabs/sync_gateway pull request #5166
Opened 2021-08-11 13:29 UTC by IsaacLambat

- [x] http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-integration/971/

Error message when setting config group ID: `customization of group_id is only supported in enterprise edition`
Uses US spelling of customisation

2021-08-11 13:44 UTC, JRascagneres submitted a review, later dismissed
Some nitpick comments on test but change looks good

2021-08-11 13:51 UTC, IsaacLambat commented on rest/config_test.go
> +		cfgGroupIDs string
Will do. Thought it was group IDs at first due to ticket name. Will change the ticket name and variable now

2021-08-11 13:53 UTC, JRascagneres commented on rest/config_test.go
> +			}
Fair enough. I think you could avoid that by adding a bootstrap server but I guess its possible future validation could break it.

2021-08-11 14:40 UTC, JRascagneres submitted a review, later dismissed

2021-08-11 16:49 UTC, IsaacLambat commented
Would it be best to warn and then switch Config Group ID to default if the user is on CE? As some EE only functionality does this. Some does not.

2021-08-11 17:27 UTC, JRascagneres commented
> Would it be best to warn and then switch Config Group ID to default if the user is on CE? As some EE only functionality does this and some does not?

I don't think so. The current functionality that does this still allows SGW to operate fine but without some 'improved' feature. Whereas if we skip this to default it could result in a SGW running with an unexpected config and its possible the customer doesn't see the warning log

2021-08-12 10:48 UTC, bbrks requested changes
minor change but otherwise looks good

2021-08-12 10:48 UTC, bbrks commented on rest/config.go
> +			errorMessages = multierror.Append(errorMessages, fmt.Errorf("customization of config_group_id is only supported in enterprise edition"))
JSON form of config name is incorrect

```suggestion
			errorMessages = multierror.Append(errorMessages, fmt.Errorf("customization of group_id is only supported in enterprise edition"))
```

2021-08-12 12:39 UTC, bbrks approved these changes
LGTM

2021-08-12 15:41 UTC, merged