CBG-1624: Allow per-database credential overrides from startup config
couchbaselabs/sync_gateway pull request #5236
Opened 2021-09-08 14:42 UTC by bbrks

CBG-1624

Allows per-database credentials to be set that override the bootstrap credentials.

### Config example:
```
{
  "bootstrap": {
    "username": "bob",
    "password": "secret"
  },
  "database_credentials": {
    "db1": {
      "username": "alice",
      "password": "hunter2"
    },
    "db2": {
      "x509_cert_path": "/tmp/foo",
      "x509_key_path": "/tmp/bar"
    }
  }
}
```

In this case, bootstrap to retrieve dbconfigs happens as bob, but then whenever we create or open a database matching the name in the config, we will use those credentials instead of the bootstrap ones.

## REST API Changes
- `GET /_config` now returns the `database_credentials` section of the config to reflect the config file on disk.
- `GET /_config?include_runtime=true` now shows per-database credentials inside each running database config to reflect the running state of each database.
- `GET /{db}/_config?include_runtime=false` has no change (the dbconfig stored in the bucket remains unchanged with per-db overrides)
- `GET /{db}/_config?include_runtime=true` now shows per-database credentials when set
- Redaction is applied to passwords on all of the above scenarios.

## [Integration Tests](http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-integration/build?delay=0sec)
- [ ] `xattrs=true` http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-integration/1094/

2021-09-17 20:52 UTC, adamcfraser requested changes

2021-09-17 20:52 UTC, adamcfraser commented on rest/config_startup.go
> +	X509KeyPath  string `json:"x509_key_path,omitempty"  help:"Key path (private key) for X.509 bucket auth"`
Just for clarification, on the omission of cacertpath in this config:
1. Are database configs always going to inherit cacertpath from the bootstrap config?
2. Does that apply even if some dbs are using x509 creds, and others are using basic auth?  (I think that's required for TLS support, just verifying)

2021-09-22 12:26 UTC, bbrks commented on rest/config_startup.go
> +	X509KeyPath  string `json:"x509_key_path,omitempty"  help:"Key path (private key) for X.509 bucket auth"`
TLDR: Yes

1. The Couchbase Server root certificate is cluster-scoped, so even when two databases have separate X.509 certs, they would still have to be signed by the same root cert associated with the bootstrap cluster.
2. If using mixed X.509/basic auth, same applies - X.509 certs will have to be signed by the root which is also used for TLS connection.

2021-09-22 16:20 UTC, adamcfraser approved these changes

2021-09-22 16:20 UTC, merged