CBG-1653: Include DB config defaults with runtime
couchbaselabs/sync_gateway pull request #5237
Opened 2021-09-09 15:29 UTC by JRascagneres

CBG-1653

- Implemented a `DefaultDbConfig()` which returns a `DbConfig` with all the default values populated (with the exception of unsupported options)
- The above involved adding a couple of consts for defaults which were not already constants. Allowed for easier creation of the default struct and ensured that if these are changed in future it will be reflected in both places without accidentally forgetting one.
- Created merge function which merges a db config with the defaults

Has a test to test that a few of the defaults are present in the config.

## [Integration Tests](http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-integration/build?delay=0sec)
- [ ] `xattrs=true` http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-integration/1104/

2021-09-10 13:05 UTC, bbrks requested changes
Looks OK. Just left a few comments around specific values.

2021-09-10 13:05 UTC, bbrks commented on rest/config_database.go
> +		DeprecatedRevCacheSize:    base.Uint32Ptr(db.DefaultRevisionCacheSize),
Remove deprecated options from defualts.

2021-09-10 13:05 UTC, bbrks commented on rest/config_database.go
> +		UseViews:                  nil,
```suggestion
		UseViews:                  base.BoolPtr(false),
```

2021-09-10 13:05 UTC, bbrks commented on rest/config_database.go
> +		SendWWWAuthenticateHeader: nil,
```suggestion
		SendWWWAuthenticateHeader: base.BoolPtr(true),
```

2021-09-10 14:41 UTC, bbrks approved these changes, later dismissed
LGTM

2021-09-15 16:57 UTC, adamcfraser commented
@JRascagneres Requires rebase

2021-09-16 20:32 UTC, adamcfraser approved these changes

2021-09-16 20:38 UTC, merged