CBG-1619: Wait for successful db startup before persisting config on db create
couchbaselabs/sync_gateway pull request #5239
Opened 2021-09-10 17:54 UTC by bbrks

CBG-1619

Ensures that the supplied per-database credentials in the startup config are valid by loading the database first, before persisting to the cluster.
- Unloads the database on a failed write to prevent cluster inconsistencies.
- Promoted locking up a level in handleCreateDB to avoid races between background config loop and a failed database creation/removal.

## Dependencies (if applicable)
- [ ] #5236 

## [Integration Tests](http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-integration/build?delay=0sec)
- [ ] `xattrs=true` http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-integration/1109/

2021-09-17 20:54 UTC, adamcfraser approved these changes, later dismissed

2021-09-17 20:54 UTC, adamcfraser commented
Looks good, pending merge of CBG-1624

2021-10-05 16:39 UTC, bbrks commented
I'm running into complexities around unwanted retry handling after these operations are swapped around. Still working through those before this PR is ready for review.

2021-10-08 15:03 UTC, bbrks reviewed
A couple of inline commentary-style comments describing changes.

2021-10-08 15:03 UTC, bbrks commented on base/bucket.go
> -			}
This `ErrAuthError`->`ErrFatalBucketConnection` handling was effectively pushed up a level to `ConnectToBucket`, to separately start treating auth errors as abortable in the retry loop. This means we can preserve the original error to use instead of losing all information about it.

2021-10-08 15:03 UTC, bbrks commented on rest/config.go
> +
Lock moved up to avoid the race condition where SG adds a running database before persisting, and the resulting background config poller sees the database was absent from the cluster before it's had a chance to be added, meaning the database would be removed.

This race was triggered reliably inside `TestConfigsIncludeDefaults` prior to the fix.

2021-10-09 00:05 UTC, adamcfraser requested changes
Posted a question about the handling when we fail to persist a database that already existed.

2021-10-09 00:05 UTC, adamcfraser commented on base/collection.go
> +		DesiredState:  gocb.ClusterStateOnline,
I think this is just a copy-paste from other places that we're using goCBv2FailFastRetryStrategy, but I don't think we need to specify the DesiredState here - the default is ClusterStateOnline.

2021-10-09 00:05 UTC, adamcfraser commented on rest/admin_api.go
> +			h.server._removeDatabase(dbName)
What happens in the case where the database already existed?  It looks like it would be removed from this node but continue to be running on other nodes, until the next time the config was updated.  Should we attempt to reload the database locally using the previously persisted config in that case?

2021-10-11 12:07 UTC, bbrks commented on rest/admin_api.go
> +			h.server._removeDatabase(dbName)
I could start an async load to avoid the potential wait time until next load, but I still think it makes sense to unload the user's database, and return the conflict/already exists error back to the user who initiated the request, given the "winning" persisted config is not theirs.

2021-10-11 12:12 UTC, bbrks commented on rest/admin_api.go
> +			h.server._removeDatabase(dbName)
I've pushed up a commit to address this case if you want to take a look at the proposed solution.

2021-10-14 18:22 UTC, adamcfraser approved these changes

2021-10-14 18:22 UTC, merged