CBG-1769: Import filter and sync function can be set and retrieved while db is offline
couchbaselabs/sync_gateway pull request #5330
Opened 2021-11-12 11:44 UTC by IsaacLambat

CBG-1769
- Made `/{db}/_config/import_filter` and `/{db}/_config/sync` endpoints available while the database is offline for `PUT`, `GET`, and `DELETE` methods
- Made tests to test all these methods on the endpoint while the database is offline

## [Integration Tests](http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-integration/build?delay=0sec)
- [x] `xattrs=true` http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-integration/1377 2 test failures seem unrelated and pass locally.

2021-11-15 13:31 UTC, bbrks requested changes
Would like to extend test to functional behaivour rather than just checking the config endpoints.

In addition, I think the current non-persistent test works but not for the reason we'd expect.

2021-11-15 13:31 UTC, bbrks commented on rest/admin_api_test.go
> +	importFilterBeforeOffline := string(resp.BodyBytes())
It would be nice to assert that this (and sync below) is equal to the one specified in the dbconfig.

I'm actually not sure the handler works in non-persistent config mode, even though this test is passing - becuase it's essentially asserting `"" == ""`

2021-11-15 13:31 UTC, bbrks commented on rest/admin_api_test.go
> +	assert.Equal(t, "", importFilterAfterOnline)
Would be nice to check the functional behaviour of the `import_filter` and `sync` function reverting to defaults after going offline, deleting, and bringing back online by writing a few docs into the bucket and have import run them through the default import filter and sync functions.

In order to test this, your sync and import filter functions would have to be set to disallow the document being written at the end of the test to ensure delete does revert back to default to allow the doc to be written/imported.

2021-11-15 16:11 UTC, IsaacLambat commented on rest/admin_api_test.go
> +	importFilterBeforeOffline := string(resp.BodyBytes())
Yes, the `import_filter` and `sync` endpoints do not work in non-persistent config mode. I have removed them from the test, and instead am just going to assert both offline and online `GET /db/_config` endpoints bodies match which includes the `import_filter` and `sync` functions as the test was originally.

2021-11-17 11:40 UTC, bbrks requested changes

2021-11-17 11:40 UTC, bbrks commented on rest/admin_api_test.go
> +	require.NoError(t, resp.Body.Close())
Use `assertResp` helper here

2021-11-18 11:17 UTC, bbrks approved these changes

2021-11-18 11:18 UTC, merged