CBG-1808: convert empty sync function to nil
couchbaselabs/sync_gateway pull request #5344
Opened 2021-11-24 16:52 UTC by cbbruno

CBG-1808

- converts sync func to nil if it is empty or blanks
- same for import filter
- done on validateVersion to work legacy or v3 configs
- added check in existing `TestInvalidJavascriptFunctions`

2021-11-24 17:11 UTC, bbrks approved these changes, later dismissed

2021-11-29 22:16 UTC, adamcfraser requested changes
Changes look fine, had a question about the need to close the response body.

2021-11-29 22:16 UTC, adamcfraser commented on rest/persistent_config_test.go
> +	_ = resp.Body.Close()
We have a lot of rest tester code that issues REST API requests (via SendRequest and SendAdminRequest) where the tests aren't explicitly closing the response body.  Is that actually required whenever bootstrapAdminRequest is invoked?  It would be nice to avoid this kind of noise in every test unless it's strictly needed.

2021-11-29 23:39 UTC, JRascagneres commented on rest/persistent_config_test.go
> +	_ = resp.Body.Close()
Yeah this is required with the `bootstrapAdminRequest` method. @bbrks work to improve the testing framework to work nicely with persistent config should mean this isn't required in the future. But as it stands with persistent config testing, this is required.

2021-11-30 00:00 UTC, adamcfraser commented on rest/persistent_config_test.go
> +	_ = resp.Body.Close()
Why is it the close required in this usage and not the case where we're using Handler.ServeHTTP for REST API testing?

2021-11-30 00:22 UTC, JRascagneres commented on rest/persistent_config_test.go
> +	_ = resp.Body.Close()
I was under the impression the underlying TestResponse would read the body and close the request for us. Perhaps I'm wrong about that.

2021-11-30 18:16 UTC, adamcfraser approved these changes

2021-11-30 18:16 UTC, merged