CBG-1824: NumPullReplActiveOneShot decrements on sub changes feed completion
couchbaselabs/sync_gateway pull request #5370
Opened 2021-12-09 14:55 UTC by IsaacLambat

CBG-1824

- `SubChangesOneShotActive` is decremented after the sub changes feed has finished which therefore decrements `NumPullReplActiveOneShot`
- Modified current `TestMultipleOutstandingChangesSubscriptions` to also test the pull stats work as intended
- Modified current `TestMultipleOutstandingChangesSubscriptions` to have require where appropriate 

## [Integration Tests](http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-integration/build?delay=0sec)
- [ ] `xattrs=true` http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-integration/1482

2022-01-10 18:37 UTC, adamcfraser requested changes, later dismissed

2022-01-10 18:37 UTC, adamcfraser commented on db/blip_handler.go
> +			defer bh.replicationStats.SubChangesOneShotActive.Add(-1)
Can you check whether moving the SubChangesContinuousActive decrement here would also work?  Would be nice to keep it all in one place if possible.

2022-01-11 18:31 UTC, bbrks commented
@IsaacLambat have you rebased to pick up the gofmt changes made in #5381  ?

2022-01-11 18:34 UTC, IsaacLambat commented
> @IsaacLambat have you rebased to pick up the gofmt changes made in #5381 ?

Not rebased so that will be the reason. Had an inkling that a rebase would fix the issue but didn't know about the gofmt change. Thanks

2022-01-14 16:28 UTC, bbrks approved these changes, later dismissed
Just a nitpick to update comment based on lastest defer changes - otherwise looks good.

2022-01-14 16:28 UTC, bbrks commented on db/blip_handler.go
> +		// Pull replication stats by type - Active continuous stats decremented in Close(), one shot after changes sent
Nitpick

```suggestion
		// Pull replication stats by type
```

2022-01-17 16:22 UTC, bbrks approved these changes
LGTM

2022-01-18 10:42 UTC, merged