CBG-1861: Updated KV upsert implementations to include UpsertOptions
couchbaselabs/sync_gateway pull request #5400
Opened 2022-01-10 14:33 UTC by IsaacLambat

CBG-1861

- Updated `sg-bucket` KV store upsert operations `Set` and `SetRaw` to include an `UpsertOptions` in order to implement GoCBv2's new `preserveExpiry`option. Done in PR https://github.com/couchbase/sg-bucket/pull/70 .
- Updated `LoggingBucket`, `LeakyBucket`, `CouchbaseBucketGoCB`, `Collection` implementations of these upsert operations to include the new upsert options parameter. Also updated `Walrus` in PR https://github.com/couchbaselabs/walrus/pull/62 .
- Changed all uses of the KV upsert operations to pass in a blank UpsertOptions.

## Dependencies
- [ ] Merge https://github.com/couchbase/sg-bucket/pull/70
- [ ] Merge https://github.com/couchbaselabs/walrus/pull/62
- [ ] Bump `sg-bucket` and `walrus` manifest commit hashes before merging

## [Integration Tests](http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-integration/build?delay=0sec)
- [ ] `xattrs=true` http://uberjenkins.sc.couchbase.com:8080/job/sync-gateway-integration/1532

2022-03-17 16:27 UTC, bbrks requested changes
One nitpick for test bucket usage but otherwise looks OK to me

2022-03-17 16:27 UTC, bbrks commented on base/bucket_gocb_test.go
> +		}
Would be nice to move this up out of the subtests for a couple of reasons:
- Only 1 test bucket for all sub tests (as long as doc IDs are unique)
- Earlier exit/skip for the non-supported CB version before we fall into the sub-tests

2022-03-18 12:33 UTC, bbrks approved these changes, later dismissed

2022-03-21 17:21 UTC, adamcfraser approved these changes

2022-03-21 17:21 UTC, merged