CBG-1884: Documented attachment endpoints
couchbaselabs/sync_gateway pull request #5413
Opened 2022-01-27 17:31 UTC by IsaacLambat

CBG-1884

Endpoints documented:
`GET HEAD PUT /{db}/{docid}/{attach}`

## Dependencies (if applicable)
- [ ] Merge after #5410

2022-02-01 16:10 UTC, bbrks requested changes

2022-02-01 16:10 UTC, bbrks commented on docs/api/api_docs.yaml
> +        The raw data of the associated attachment is returned (just as if you were accessing a static file). The `Content-Type` response header is the same content type set when the document attachme
```suggestion
        The raw data of the associated attachment is returned (just as if you were accessing a static file). The `Content-Type` response header is the same content type set when the document attachment was added to the database. The `Content-Disposition` response header to force attachment downloads will be set if the content type is considered unsafe to display in a browser (unless overriden by by database config option `serve_insecure_attachment_types`).
```

2022-02-01 16:10 UTC, bbrks commented on docs/api/api_docs.yaml
> +          description: Include the metadata of the attachment in the response body. Will cause `Content-Type=application/json` in the response header.
```suggestion
          description: Return only the metadata of the attachment in the response body.
```

2022-02-01 16:10 UTC, bbrks commented on docs/api/api_docs.yaml
> +        To remove an attachment from a document, simply update the `_attachments` dictionary of the document in the `PUT /{db}/{docid}` request.
```suggestion
        To remove an attachment from a document, omit the attachment in the `_attachments` object of the document in the `PUT /{db}/{docid}` request.
```

2022-02-01 16:10 UTC, bbrks commented on docs/api/api_docs.yaml
> +        If the attachment already exists, the data of the existing attachment will be replaced in the new revision. The revisions are for tracking document changes, not attachment changes.
Swap these two paragraps around to keep the high-level description at the top. Specifics around headers/size limits further down.

2022-02-01 16:10 UTC, bbrks commented on docs/api/api_docs.yaml
> +        If the attachment already exists, the data of the existing attachment will be replaced in the new revision. The revisions are for tracking document changes, not attachment changes.
> The revisions are for tracking document changes, not attachment changes.

I'm not really sure what this means. Attachment changes are included as part of a document change.

2022-02-01 16:10 UTC, bbrks commented on docs/api/api_docs.yaml
> +        The maximum content size of an attachment is 20MB. The `Content-Type` header of the request should be what the content type of the attachment is otherwise this will default to `application/oc
```suggestion
        The maximum content size of an attachment is 20MB. The `Content-Type` header of the request specifies the content type of the attachment.
```

Reword and default values are described already in the spec. I don't think there's a need to repeat them in a description.

2022-02-01 16:10 UTC, bbrks commented on docs/api/api_docs.yaml
> +          description: Used as the `rev` query parameter if it is not set.
Wording of this is ambiguous and exposes some unnecessary implementation detail.

```suggestion
          description: The existing document revision ID to modify. Required only when modifying an existing document.
        - name: If-Match
          schema:
            type: string
          in: header
          description: An alternative way of specifying the document revision ID.
```

2022-02-01 16:10 UTC, bbrks commented on docs/api/api_docs.yaml
> +          headers:
```suggestion
          headers:
            Content-Length:
              schema:
                type: string
                description: length of attachment in bytes
```

2022-02-01 16:10 UTC, bbrks commented on docs/api/api_docs.yaml
> +        - $ref: '#/components/parameters/rev'
Missing request parameters

```suggestion
        - $ref: '#/components/parameters/rev'
        - schema:
            type: boolean
            default: 'true'
          in: query
          name: content_encoding
          description: Set to false to disable the `Content-Encoding` response header.
        - schema:
            type: string
          in: header
          name: Range
          description: 'RFC-2616 bytes range header. E.g: bytes=123-456'
```

2022-02-01 16:10 UTC, bbrks commented on docs/api/api_docs.yaml
> +          headers:
Content-Length

2022-02-01 18:17 UTC, IsaacLambat commented on docs/api/api_docs.yaml
> +        If the attachment already exists, the data of the existing attachment will be replaced in the new revision. The revisions are for tracking document changes, not attachment changes.
I was trying to say that attachments don't get their own revision ID but rather the document does. Will remove this as it seems unnecessary.

2022-02-02 09:29 UTC, bbrks requested changes
Feel free to just apply these suggestions in GitHub - they were my incorrect suggestions to begin with 😄

2022-02-02 09:29 UTC, bbrks commented on docs/api/api_docs.yaml
> +                description: Length of the attachment in bytes
whoops, my suggestion was incorrectly indented

```suggestion
              description: Length of the attachment in bytes
```

2022-02-02 09:29 UTC, bbrks commented on docs/api/api_docs.yaml
> +          description: 'RFC-2616 bytes range header. For example, bytes=123-456.'
Again my bad w/ suggestion - I've seen the correct way of specifying an example:

```suggestion
          description: 'RFC-2616 bytes range header.'
          example: 'bytes=123-456'
```

2022-02-02 10:51 UTC, bbrks approved these changes

2022-02-02 10:57 UTC, merged