CBG-1981: Added trace logging, and removed password change from TestReplicatorRevocationsMultipleAlternateAccess
couchbaselabs/sync_gateway pull request #5475
Opened 2022-03-21 16:02 UTC by IsaacLambat

CBG-1981

- Added trace logging to `TestReplicatorRevocationsMultipleAlternateAccess`
- Removed unnecessary password change happening in test

2022-03-21 16:51 UTC, JRascagneres commented
Interesting, guess that auth 'issue' was the break?

2022-03-21 17:07 UTC, JRascagneres approved these changes

2022-03-21 17:12 UTC, bbrks commented
Was this test not _creating_ a user on `rt2` for the replicator to use?

2022-03-21 17:25 UTC, IsaacLambat commented
> Was this test not _creating_ a user on `rt2` for the replicator to use?
The test creates the user the replicator uses in the `initScenario` function

2022-03-23 14:19 UTC, bbrks requested changes
Test seems to be failing more in GH actions with this change

2022-03-23 14:33 UTC, IsaacLambat commented
Closing PR due to more time needed to investigate the root cause of the problem for whoever gets the ticket and to investigate why removing the password change causes the test to fail more often.

2022-03-23 14:33 UTC, closed without merging