[WIP] CBG-2016: Relax principal name restrictions
couchbaselabs/sync_gateway pull request #5506
Opened 2022-04-14 14:04 UTC by markspolakovs

CBG-2016

Especially with OIDC, customers may want to e.g. namespace their usernames. Up until now we only permitted a select few characters (alphanumeric and any of "_-+.@") in principal names. Extend this to any character except for a few problematic cases:

- Invalid UTF-8
- Strings consisting only of punctuation (i.e. no alpha-numerics)
- Slashes, colons, and commas

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [ ] `xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/000/

2022-04-19 13:29 UTC, bbrks requested changes

2022-04-19 13:29 UTC, bbrks commented on auth/role.go
> +	return kValidNameRegexp.MatchString(name)
I think It'll be a lot cheaper to do this (along with a utf8 rune check) in a single-pass of `name` given the type of checks were making.

I think it's worth doing given how often this is called - but feel free to benchmark to see if it's a valid assumption.

2022-04-19 13:29 UTC, bbrks commented on db/database_test.go
> -	assertHTTPError(t, err, 500)
It's probably worth keeping these bad user/role checks but we'll have the modify them to fit the new definition of "bad", otherwise we're really only testing the happy-path case for a channel mapper's validation.

2022-04-19 14:03 UTC, markspolakovs commented on auth/role.go
> +	return kValidNameRegexp.MatchString(name)
Indeed, good call:

```
$ benchstat orig.txt new-validString.txt
name                     old time/op  new time/op  delta
IsValidPrincipalName-12  1.07µs ± 0%  0.07µs ± 1%  -93.57%  (p=0.016 n=4+5)
```

2022-04-21 16:16 UTC, bbrks approved these changes

2022-04-21 16:16 UTC, merged