CBG-1736: Namespace ISGR checkpoints by Cluster UUID
couchbaselabs/sync_gateway pull request #5511
Opened 2022-04-20 15:37 UTC by bbrks

CBG-1736

- Generates a Cluster UUID which is stored in the SGRCluster doc.
- For newly created replications, prepends the cluster UUID into the checkpoint prefix.
  - Avoids edge replications with identical names from having conflicting remote checkpoints.

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [x] `xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/200/

2022-05-09 15:57 UTC, bbrks commented
@adamcfraser Can I get a review on this? I'll need to open a 3.0.1 backport for it, and want to get feedback soon

2022-05-10 16:21 UTC, adamcfraser requested changes

2022-05-10 16:21 UTC, adamcfraser commented on db/sg_replicate_cfg.go
> +		if replication.ClusterUUID == "" {
Is it possible to add a test to verify correct behaviour on CAS retry on concurrent update of the cluster (i.e. we don't end up with two replications with different cluster UUIDs)

2022-05-12 16:26 UTC, adamcfraser commented on db/sg_replicate_cfg.go
> +		if replication.ClusterUUID == "" {
As discussed, this isn't a blocker to merge this, as replications existing with different cluster UUIDs doesn't break the underlying functionality.

2022-05-12 16:27 UTC, adamcfraser approved these changes

2022-05-12 16:27 UTC, merged