CBG-1980: Fixed incorrect attachment stats being reported
couchbaselabs/sync_gateway pull request #5514
Opened 2022-04-22 11:01 UTC by IsaacLambat

CBG-1980

- All attachment compaction phases wait for the DCP client doneChannel to close before returning out the function causing a correct count to be returned that will not increment after the function has exited
- The DCP doneChannel is only closed after all the DCP workers have terminated
- Unit test to repro incorrect stats

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [ ] `xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/207/

2022-04-27 15:31 UTC, bbrks requested changes, later dismissed
Haven't done a proper review (I'll leave that to @JRascagneres who is more familiar with this/the task manager code) but wanted to note the wg usage:

2022-04-27 15:31 UTC, bbrks commented on base/dcp_client_worker.go
> +		wg.Add(1)
It's not safe to call Add inside the goroutine decrementing it because `wg.Wait()` might hit the case where the WaitGroup is 0 before these goroutines have started.

From the Go docs:
> Note that calls with a positive delta that occur when the counter is zero must happen before a Wait. Calls with a negative delta, or calls with a positive delta that start when the counter is greater than zero, may happen at any time. Typically this means the calls to Add should execute before the statement creating the goroutine or other event to be waited for.

2022-04-27 15:31 UTC, bbrks commented on db/attachment_compaction_test.go
> +	defer base.SetUpTestLogging(base.LevelInfo, base.KeyAll)()
Uptake SetUpTestLogging changes from `master`

2022-04-28 14:41 UTC, JRascagneres requested changes
Couple test changes but mostly fine

2022-04-28 14:41 UTC, JRascagneres commented on db/attachment_compaction_test.go
> +	attKeys := make([]string, 0, 11)
```suggestion
	attKeys := make([]string, 0, docsToCreate)
```

2022-04-28 14:41 UTC, JRascagneres commented on db/attachment_compaction_test.go
> +	time.Sleep(time.Second * 1)
Keep the sleep here for the test (unfortunately can't think of a better way)
but we should wait for the mark phase to return here.

2022-04-28 14:41 UTC, JRascagneres commented on db/attachment_compaction_test.go
> +	err, _ = base.RetryLoop("wait for marking to start", retryFunc, base.CreateSleeperFunc(1000, 1))
change to sweep

2022-04-29 16:14 UTC, JRascagneres approved these changes

2022-04-29 16:18 UTC, merged