CBG-2080: Stub new scopes/collections database config options
couchbaselabs/sync_gateway pull request #5554
Opened 2022-05-23 15:14 UTC by bbrks

CBG-2080

Allows the new `scopes` and `collections` database config options to be used. Currently not wired up to anything.

Basic config validation is implemented:
- zero or one scope
- at least one collection under a scope
- valid js functions if set

Changes:
- Defined new `scopes` and `collections` config fields in database config struct.
- Extracted js function validation logic into function and unit tested.

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [x] `xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/278
  - Flake: `--- FAIL: TestLogFlush/Default (20.14s)`

2022-05-24 14:07 UTC, markspolakovs approved these changes, later dismissed
LGTM, just a couple questions (but happy for this to go in as is if Isaac is too)

2022-05-24 14:07 UTC, markspolakovs commented on rest/config.go
> +			multiError = multiError.Append(fmt.Errorf("only one named scope is supported, but had %d (%v)", len(dbConfig.Scopes), dbConfig.Scopes))
How big do we expect `dbConfig.Scopes` to be? Would the `%v` make the error message too long to (easily) read?

2022-05-24 14:07 UTC, markspolakovs commented on rest/config.go
> +		if numScopes > 1 {
Nitpicking: could this be `if len(dbConfig.Scopes) > 1` which removes the need for the `numScopes` variable?

2022-05-24 14:09 UTC, markspolakovs commented on rest/config.go
> +		if numScopes > 1 {
Should the check be outside the loop, to only run it once?

2022-05-24 14:32 UTC, IsaacLambat requested changes
Would be good to not repeat the same error message multiple times when multiple scopes are defined while still bundling all the errors from the first scope as well (to save the user from restarting as you have done currently).

2022-05-24 14:32 UTC, IsaacLambat commented on rest/config.go
> +			multiError = multiError.Append(fmt.Errorf("only one named scope is supported, but had %d (%v)", len(dbConfig.Scopes), dbConfig.Scopes))
This would cause a lot of error spam if there are a few scopes defined. Would be good to get it so this only counts as one error regardless of the amount of scopes defined.

2022-05-24 14:53 UTC, bbrks commented on rest/config.go
> +			multiError = multiError.Append(fmt.Errorf("only one named scope is supported, but had %d (%v)", len(dbConfig.Scopes), dbConfig.Scopes))
Don't expect it to grow much more than 1 scope. It's explicitly defined by the database config, so not going to expand to all available scopes or anything.

2022-05-27 13:19 UTC, IsaacLambat approved these changes
LGTM!

2022-05-27 13:34 UTC, merged