CBG-2100 Skip test that requires couchbases
couchbaselabs/sync_gateway pull request #5570
Opened 2022-06-15 21:51 UTC by torcolvin

CBG-2100

Skip test so Jenkins can run with `couchbases://` protocol without errors.

2022-06-16 15:40 UTC, bbrks requested changes

2022-06-16 15:40 UTC, bbrks commented on rest/admin_api_auth_test.go
>  	rt := NewRestTester(t, nil)
This test can be made to work with either scheme. Preferable to skipping.

Potentially similar fix for below tests, although have not looked to see why those are failing.

```suggestion
	rt := NewRestTester(t, &RestTesterConfig{useTLSServer: base.ServerIsTLS(base.UnitTestUrl())})
```

2022-06-16 17:42 UTC, torcolvin commented on rest/admin_api_auth_test.go
>  	rt := NewRestTester(t, nil)
there were so many circumstances where RestTesterConfig is initialized, so I moved the logic to set TLS in NewRestTester. All integration tests seem to pass.

2022-06-21 11:47 UTC, bbrks submitted a review, later dismissed

2022-06-21 13:39 UTC, bbrks approved these changes

2022-06-21 13:51 UTC, merged