CBG-2081: OpenAPI specs/REST API stubs for collections
couchbaselabs/sync_gateway pull request #5574
Opened 2022-06-16 15:17 UTC by bbrks

CBG-2081

- update api specs for keyspace/collections changes
- db-> keyspace changes in REST API code
- stub per-collection sequences in in `GET /db/` response

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [ ] `xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/341/

2022-06-22 16:21 UTC, IsaacLambat approved these changes, later dismissed
LGTM

2022-06-24 21:34 UTC, adamcfraser requested changes
General approach looks good, some questions and suggestions.

2022-06-24 21:34 UTC, adamcfraser commented on docs/api/admin.yaml
>    '/{db}/_resync':
I think we're defining sync functions per collection.  If so, running resync per collection seems like something we'll want to do?

2022-06-24 21:34 UTC, adamcfraser commented on docs/api/admin.yaml
> -  '/{db}/_bulk_docs':
Is the plan to have 1.x replication only supported against a single collection?

2022-06-24 21:34 UTC, adamcfraser commented on rest/api.go
> +	SequenceNumber                uint64                       `json:"update_seq"`           // The last sequence written to the _default collection
Does this make sense to keep, given that the _default collection may not be included in the database?  At minimum it could be switched to omitempty.

2022-06-24 21:34 UTC, adamcfraser commented on rest/api.go
> +		// TODO: Get scope/collection sequences
Should be removed until we have real data to populate with - potentially could hardcode _default._default for now if needed for testing.

2022-06-24 21:34 UTC, adamcfraser commented on rest/handler.go
> +	if dbField != nil && *dbField == "" ||
I don't think there's a case where dbField is nil in the current implementation

2022-06-24 21:34 UTC, adamcfraser commented on rest/handler.go
> +		collectionField = &parts[1]
Stuck a comment in the design doc on this.  Using the default scope when it's omitted feels a bit off as long as the database is only associated with a single scope (that might be the default scope).  I'd expect [db.myCollection] to be targeting the scope associated with db.  I don't think that changes future support for multiple scopes per DB - in that case we would require the fully qualified keyspace.

2022-06-24 21:34 UTC, adamcfraser commented on rest/handler.go
> +	// FIXME: This will be quicker/zero alloc if we use base.safeCut...
Any reason not to fix this in this PR?

2022-06-24 21:34 UTC, adamcfraser commented on docs/api/admin.yaml
>    '/{db}/_changes':
It feels inconsistent from an API perspective to have _changes stay on db, but other multi-doc operations move to keyspace.  I understand that _changes will allow collection selection via parameters, but still seems a bit trickier to reason about as an API.

2022-06-29 20:45 UTC, adamcfraser approved these changes

2022-06-29 20:45 UTC, merged