CBG-2172: Improve reliability of TestAttachmentCompactIncorrectStat
couchbaselabs/sync_gateway pull request #5596
Opened 2022-06-28 13:21 UTC by markspolakovs

CBG-2172

`TestAttachmentCompactIncorrectStat` has been somewhat flakey. This PR attempts to address that in two ways:

- Increasing the number of docs to process, to make it more likely that the mark/sweeps won't process them all
- Increasing the retry loop timeouts to make the test more forgiving of slower systems

It also adds extra debug/trace logging to help debug further flake.

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [ ] `xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/349/

2022-06-28 14:27 UTC, IsaacLambat requested changes
Just a couple of small changes. Someone else can review it after just to make sure

2022-06-28 14:27 UTC, IsaacLambat commented on db/attachment_compaction.go
> +		base.WarnfCtx(db.Ctx, "[%s] Failed to start DCP feed! %v", compactionLoggingID, err)
Might be good to say it failed for attachment compaction

2022-06-28 14:27 UTC, IsaacLambat commented on db/attachment_compaction.go
> +	base.DebugfCtx(db.Ctx, base.KeyAll, "[%s] DCP client started.", compactionLoggingID)
The key should be set to `KeyDCP` so it can be filtered out

2022-06-28 14:30 UTC, markspolakovs commented on db/attachment_compaction.go
> +	base.DebugfCtx(db.Ctx, base.KeyAll, "[%s] DCP client started.", compactionLoggingID)
There's a couple other lines that use `KeyAll` - should all of them be changed to KeyDCP? eg

```go
base.InfofCtx(db.Ctx, base.KeyAll, "[%s] Starting DCP feed for cleanup phase of attachment compaction", compactionLoggingID)
```

2022-06-28 14:40 UTC, IsaacLambat commented on db/attachment_compaction.go
> +	base.DebugfCtx(db.Ctx, base.KeyAll, "[%s] DCP client started.", compactionLoggingID)
Actually, scratch what I said. The log line should not be filtered because it is more related to attachment compaction and could be helpful in the future.

2022-06-28 16:23 UTC, torcolvin submitted a review, later dismissed

2022-06-28 16:23 UTC, torcolvin commented on db/attachment_compaction_test.go
> +	err, _ = base.RetryLoop("wait for marking function to return", compactionFuncReturnedRetryFunc, base.CreateSleeperFunc(3_000, 10))
make these sleeper calls a constant for sleep?

2022-06-29 14:06 UTC, IsaacLambat approved these changes
LGTM

2022-06-29 14:17 UTC, merged