CBG-2157: Allow SG databases to be created for a single named collection
couchbaselabs/sync_gateway pull request #5606
Opened 2022-07-06 15:31 UTC by bbrks

CBG-2157

Allows a SG database to start up aginst a single named scope/collection and use the REST API to read and write documents in that keyspace instead of the default scope and collection.

- Validates that REST API keyspace usage is valid and matches running configuration.
- Exposes `DatabaseContext.Scopes[].Collections[]` for access in handlers (e.g. `getCollections`)
- Supports KV operations on the named collection.
- Persistent config still operates on default scope/collection.

Does not support:
- Query/Index/Views (CBG-2159 / CBG-2158)
- DCP (CBG-2182)

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [ ] `xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/369/

2022-07-06 23:00 UTC, adamcfraser requested changes
Generally looks fine - a few comments.

2022-07-06 23:00 UTC, adamcfraser commented on rest/handler.go
> +	if dbc := h.server.GetDbConfig(keyspaceDb); dbc != nil && len(dbc.Scopes) > 0 {
Why do we need to look up the set of scopes from the dbConfig, as opposed to checking the scopes defined on the dbContext?

2022-07-06 23:00 UTC, adamcfraser commented on rest/handler.go
> +			keyspaceScope = dbContext.BucketSpec.Scope
Similar question here - why BucketSpec.Scope as opposed to checking in dbContext.Scopes?  If the intention is to design with support for multiple Scopes on the dbContext, then should add a way to specify the 'default' scope (not to be confused with _default scope) for the database.

2022-07-06 23:00 UTC, adamcfraser commented on rest/handler.go
> +			if len(dbc.Scopes[*keyspaceScope].Collections) > 1 {
You're not doing an existence check here (like you are below with foundScope) - can probably just do this once.

2022-07-06 23:00 UTC, adamcfraser commented on db/blip_sync_context.go
> +	gotSubChanges                    bool            // nolint: structcheck // false structcheck positive due to https://github.com/golangci/golangci-lint/issues/826
Are these comments autogenerated by the linter?  They feel a bit messy.

2022-07-06 23:00 UTC, adamcfraser commented on db/database.go
> +	Datastore base.Bucket // Where data is stored for the collection - This should be changed to allow multiple collections to share the same underlying SDK connection once support for >1 collection is
Is this being used anywhere, or is databaseContext.Bucket still being used for SDK connections?

2022-07-06 23:00 UTC, adamcfraser commented on base/collection.go
> +	c := bucket.DefaultCollection()
I don't think bucket.DefaultCollection() is particularly lightweight - we'd be better off only allocating when we're actually using the default collection.
Given that bucket.DefaultCollection is just a helper function for bucket.Scope("_default").Collection("_default), maybe just write a helper function for bucketSpec to return scope and collection name that will do the appropriate substitution of default values?

2022-07-07 17:34 UTC, bbrks commented on db/blip_sync_context.go
> +	gotSubChanges                    bool            // nolint: structcheck // false structcheck positive due to https://github.com/golangci/golangci-lint/issues/826
These two fields are due to be removed by @IsaacLambat via some refactoring in #5590 - turns out those linter complaints were semi-legitimate.

2022-07-07 17:34 UTC, bbrks commented on db/database.go
> +	Datastore base.Bucket // Where data is stored for the collection - This should be changed to allow multiple collections to share the same underlying SDK connection once support for >1 collection is
`databaseContext.Bucket` is still being used, not this - I think this API needs to change to return something that is able to invoke things like `GetDocument()`, etc.

For now I'll make it store the one DatabaseContext reference before I move those APIs to something lower level.

2022-07-07 17:34 UTC, bbrks commented on rest/handler.go
> +			keyspaceScope = dbContext.BucketSpec.Scope
I've changed it to `dbContext.Scopes` and use the one scope that is running - but I don't think we should add the "default_scope" config option unless/until we actually support >1 scope

2022-07-07 21:47 UTC, adamcfraser approved these changes

2022-07-07 21:47 UTC, merged