CBG-2197: Avoid registering CBGT PIndex type for emptyAllDocsIndex codepath
couchbaselabs/sync_gateway pull request #5625
Opened 2022-07-12 10:59 UTC by bbrks

CBG-2197

Avoids concurrent map writes to the CBGT PIndex map coming from the TestBucketPool async bucket readier function calling `emptyAllDocsIndex` and creating a temporary DatabaseContext...

2022-07-12 15:39 UTC, bbrks commented
Assigning you @markspolakovs as you touched this last when you moved it into `NewDatabaseContext` - which _is_ where it belongs, but it caused this.

2022-07-12 15:46 UTC, markspolakovs approved these changes, later dismissed
The change makes sense, but seems like a bit of a smell - is there still a risk of concurrent map writes if NewDatabaseContext happens to be called concurrently by two callers that set it to `false` / how likely is that? (Also, adding an extra parameter to a commonly used method that's `false` 90% of the time doesn't seem quite right to me :D).

Approving nonetheless because it's not a strong objection, but something doesn't "feel right".

2022-07-12 15:49 UTC, bbrks commented
I agree, but couldn't come up with alternatives other than shoving the bool in DatabaseContextOptions, but I suppose that would be a lot cleaner, so I might do that instead.

I don't think there's a risk otherwise - as anything that calls NewDatabaseContext is holding a ServerContext lock, or is a unit test running sequentially.

2022-07-12 20:45 UTC, adamcfraser requested changes
My initial thought was that we should be making this change in the bucket pool utility (emptyAllDocsIndex) to run without a database context, instead of instantiating a database context.  The CBGT index creation isn't the only unnecessary work that's done during database context creation.  

Based on that, I was going to suggest writing something to execute the required query manually.

However, now I'm wondering how this is intended to behave, since queryAllDocs doesn't return documents that don't have sync metadata.  Do we want to ensure those are purged as well?

2022-07-13 14:43 UTC, bbrks commented
The `N1QLBucketEmptierFunc` called prior to `emptyAllDocsIndex` does a `DELETE FROM $_keyspace` using a primary index to ensure the bucket is empty. The purpose of `emptyAllDocsIndex` is to compact/purge tombstones.

Changing that to work without a database is more than I want to do at this point. I just want to fix the concurrent map race...

2022-07-14 00:08 UTC, adamcfraser approved these changes

2022-07-14 00:08 UTC, merged