CBG-2203 Report db read error on collection, for client to retry
couchbaselabs/sync_gateway pull request #5690
Opened 2022-08-10 18:13 UTC by torcolvin

I don't know how to test this without a leaky bucket, since I need `GetSpecial` to fail. I tried taking the database offline and setting `BucketOpTimeoutMs` be be a very small value but it still would hang for long periods of time.

## Pre-review checklist
- [x] Removed debug logging (`fmt.Print`, `log.Print`, ...)
- [x] Logging sensitive data? Make sure it's tagged (e.g. `base.UD(docID)`, `base.MD(dbName)`)
- [x] Updated relevant information in the API specifications (such as endpoint descriptions, schemas, ...) in `docs/api`

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [x] `xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/596/

2022-08-11 13:45 UTC, bbrks requested changes

2022-08-11 13:45 UTC, bbrks commented on db/blip_handler_collections.go
> +				return base.HTTPErrorf(status, errMsg)
Given the special handling of error codes on the Lite side - we probably need to change `status` to be a fixed `503` instead to give us the behaviour we want (the client reconnecting)
I don't know what clients would do if the error we returned to them was something else.

2022-08-11 16:04 UTC, torcolvin commented on db/blip_handler_collections.go
> +				return base.HTTPErrorf(status, errMsg)
Changed to 503.

2022-08-11 22:09 UTC, adamcfraser approved these changes

2022-08-11 22:10 UTC, adamcfraser commented
Looks good - reassigned to Ben to approve the change he requested related to 503.

2022-08-12 07:37 UTC, bbrks approved these changes

2022-08-12 07:37 UTC, merged