CBG-2315: Disallow changing scope after DB creation
couchbaselabs/sync_gateway pull request #5736
Opened 2022-09-02 10:05 UTC by markspolakovs

CBG-2315

Validate that the `scopes` property of the DB config cannot be changed after initial creation.

## Pre-review checklist
- [x] Removed debug logging (`fmt.Print`, `log.Print`, ...)
- [x] Logging sensitive data? Make sure it's tagged (e.g. `base.UD(docID)`, `base.MD(dbName)`)
- [x] Updated relevant information in the API specifications (such as endpoint descriptions, schemas, ...) in `docs/api`

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [ ] `xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/000/

2022-09-02 10:06 UTC, markspolakovs commented on rest/config.go
> +func (dbConfig *DbConfig) validateChanges(ctx context.Context, old *db.DatabaseContext) error {
I'm not sure about this accepting a `*DatabaseContext` - ideally it'd keep around a reference to the old `DbConfig` but that may require a more extensive refactor.

2022-09-02 16:55 UTC, bbrks requested changes

2022-09-02 16:55 UTC, bbrks commented on rest/config.go
> +	return nil
Would be nice if we can use logic that doesn't bake-in assumptions about what's a valid scope count.

2022-09-05 11:10 UTC, bbrks approved these changes

2022-09-05 11:10 UTC, merged