CBG-2400 Switch bucket pool to create a non default collection
couchbaselabs/sync_gateway pull request #5769
Opened 2022-09-19 19:04 UTC by torcolvin

- Use SG_TEST_USE_COLLECTION_POOL to switch between using non default collections by default. If this flag isn't set, tests requiring named collections will not run. This only applies when using GSI.
- Create a named collection on a bucket as well as the default collection. After storing the type of collection received by `base.GetTestBucket` and its variants, clean that collection by using primary index to drop all items.
- Some tests require using default collections (e.g. tests that read persistent config). There may be some tests that are writing to the wrong collection by accident.
- After slightly changing tbpClusterV2 interface, remove tbpClusterV1 which is only compatible with gocb/v1

This is intertwined with #5767, because GSI tests will not work robustly without that commit.

## Pre-review checklist
- [x] Removed debug logging (`fmt.Print`, `log.Print`, ...)
- [x] Logging sensitive data? Make sure it's tagged (e.g. `base.UD(docID)`, `base.MD(dbName)`)
- [x] Updated relevant information in the API specifications (such as endpoint descriptions, schemas, ...) in `docs/api`

## Dependencies (if applicable)
- [x] Link upstream PRs

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [ ] `xattrs=true,gsi=false` https://jenkins.sgwdev.com/job/SyncGateway-Integration/853/
- [ ] `xattrs=true,gsi=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/854/
- [ ] `xattrs=false,gsi=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/855/
- [ ] `xattrs=true,gsi=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/856/

2022-09-21 17:32 UTC, bbrks requested changes

2022-09-21 17:32 UTC, bbrks commented on rest/adminapitest/admin_api_test.go
> +	tb := base.GetTestBucketDefaultCollection(t)
These and the other FIXMEs I'm not immediately sure of the answer to - but is probably something we need to figure out?

- It's either something the test is doing that doesn't support collections, in which case we can remove the fixme
- Something the bucket/collection pool approach doesn't solve, in which case we'll have to figure out where that gap is and how to close it
- or some other weirdness that needs investigation (in which case we could file tickets?)

FIXMEs are almost certainly never going to be revisited without a means of tracking/reminding.

2022-09-21 17:32 UTC, bbrks commented on rest/blip_api_collections_test.go
>  	base.TestRequiresCollections(t)
Unrelated but CBG-2203 (and the blocking LeakyBucket enhancements) I believe are done but there's nothing tracking the work to enable the subtest and it wasn't revisited as part of those tickets.

Do we need another ticket for test coverage of this case now it's possible to write a test for?

2022-09-23 16:11 UTC, torcolvin commented on rest/adminapitest/admin_api_test.go
> +	tb := base.GetTestBucketDefaultCollection(t)
These all rely subtly on persistent config and I'm going to change these to be changed in CBG-2266.

2022-09-23 16:34 UTC, torcolvin commented on rest/blip_api_collections_test.go
>  	base.TestRequiresCollections(t)
I'm going to look at this now.

2022-09-23 16:43 UTC, bbrks approved these changes

2022-09-23 16:59 UTC, merged