CBG-2381
couchbaselabs/sync_gateway pull request #5824
Opened 2022-10-18 16:16 UTC by mohammed-madi

CBG-2381

Describe your PR here...
- Sync function exceptions were logging the body of the document in the warning message, which can have a size of up to 20 MB.
- Sync function exceptions now only log the document ID and the rev ID, i.e. 
`2022-10-18T16:59:54.403+01:00 [WRN] db:db c:#002 Sync fn exception: ReferenceError: 'doc1' is not defined; doc_id = doc1, rev_id = 1-cd809becc169215072fd567eebd8b8de -- db.(*Database).getChannelsAndAccess() at crud.go:2250`

## Pre-review checklist
- [ ] Removed debug logging (`fmt.Print`, `log.Print`, ...)
- [ ] Logging sensitive data? Make sure it's tagged (e.g. `base.UD(docID)`, `base.MD(dbName)`) (Tagged as Metadata)

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [ ] `xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/984/

2022-10-18 16:20 UTC, bbrks requested changes
minor tweaks for formatting/redaction tagging but otherwise fine

2022-10-18 16:20 UTC, bbrks commented on db/crud.go
> +			base.WarnfCtx(ctx, "Sync fn exception: %+v; doc_id = %s, rev_id = %s", err, base.MD(doc.ID), base.MD(doc.CurrentRev))
```suggestion
			base.WarnfCtx(ctx, "Sync fn exception: %+v; doc %q / %q", err, base.UD(doc.ID), base.MD(doc.CurrentRev))
```

- Document IDs are user data (determined by customers/users) so should be tagged by `UD`
- Rev IDs are generated metadata so can be tagged `MD`
- Somewhat consistent logging for doc ID/rev ID pairs suggested (see logging above)

2022-10-18 16:46 UTC, mohammed-madi commented
Updated PR description with new output format after requested changes were commited

2022-10-20 09:56 UTC, bbrks approved these changes

2022-10-20 09:57 UTC, merged