Namespace sequence metadata keys
couchbaselabs/sync_gateway pull request #6029
Opened 2023-01-20 05:17 UTC by adamcfraser

Adds infrastructure for namespacing metadata keys, and implements for _sync:seq and unusedSeq documents.  Defines a factory type for generating metadata keys (MetadataKeys) that is initialized when a databaseContext is created, and passed to consumers associated with that database.

CBG-0000

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [ ] `GSI=true,xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/000/

2023-01-20 15:12 UTC, bbrks requested changes
Approach looks good. Just nitpicks below.

2023-01-20 15:12 UTC, bbrks commented on base/constants_syncdocs.go
> +// formatMetadataKey formats key into the form _sync:[metaKey]
```suggestion
// formatDefaultMetadataKey formats key into the form _sync:[metaKey]
```

2023-01-20 15:12 UTC, bbrks commented on db/database.go
> +	dbContext.MetadataKeys = metaKeys
I don't think `dbContext.MetadataID` needs to exist given it's being stored in `MetadataKeys` - unless I'm overlooking something not yet implemented that requires it be separate.

2023-01-20 15:12 UTC, bbrks commented on base/dcp_test.go
> +		{"db specific meta keys", NewMetadataKeys("dbname")},
Could give us ever so slightly more coverage of the function used by `NewDatabaseContext`

```suggestion
		{"default meta keys", NewMetadataKeys("")},
		{"db specific meta keys", NewMetadataKeys("dbname")},
```

2023-02-24 03:11 UTC, adamcfraser commented
Rebase was relatively painful, needed to move to new branch/PR:
https://github.com/couchbase/sync_gateway/pull/6112

2023-02-24 03:11 UTC, closed without merging