CBG-2595 use metadata specific indexes
couchbaselabs/sync_gateway pull request #6103
Opened 2023-02-21 16:18 UTC by torcolvin

I added `rest/integrationtest` that doesn't initialize any indexes so that we can catch bugs like we saw before where we weren't creating indexes for metadata storage with a non default collection. This test could probably be expanded to test other scenarios but I wasn't sure which were good ideas.

## Pre-review checklist
- [x] Removed debug logging (`fmt.Print`, `log.Print`, ...)
- [x] Logging sensitive data? Make sure it's tagged (e.g. `base.UD(docID)`, `base.MD(dbName)`)
- [x] Updated relevant information in the API specifications (such as endpoint descriptions, schemas, ...) in `docs/api`

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [x] `GSI=true,xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/1518/

2023-02-21 18:29 UTC, bbrks requested changes

2023-02-21 18:29 UTC, bbrks commented on base/util_testing.go
> +	} else if len(dataStoreNames) == 0 {
Do you want this check first, otherwise any non-zero `count` would always be `> 0` and only give first error

2023-02-21 18:29 UTC, bbrks commented on rest/integrationtest/integration_test.go
> +		require.Equal(t, users, responseUsers)
Is there anything in these tests that we wouldn't expect to work in views (with the exception of `requireNoIndexes`)

Anything index/GSI-specific we need to assert on?

2023-02-21 18:29 UTC, bbrks commented on rest/integrationtest/main_test.go
> +func TestMain(m *testing.M) {
If this package is mainly to to avoid upfront creation of indexes, perhaps copy `db/indexestest`'s naming convention

Otherwise almost all of our tests would fit the `integrationtest` criteria.

2023-02-21 18:29 UTC, bbrks commented on base/util_testing.go
> +		tb.t.Fatalf("You are requesting more datastores %d than are available on this test instance %d", dataStoreNames, count)
Parameters are wrong way around (and missing `len()` for `%d`)

```suggestion
		tb.t.Fatalf("You are requesting more datastores %d than are available on this test instance %d", count, len(dataStoreNames))
```

2023-02-21 18:29 UTC, bbrks commented on db/indexes.go
> +	base.InfofCtx(ctx, base.KeyAll, "Initializing indexes for with numReplicas: %d...", options.NumReplicas)
missing datastore name or accidental `for `?

2023-02-21 18:29 UTC, bbrks commented on rest/server_context.go
> +			if err := initDataStore(bucket.DefaultDataStore(), db.IndexesMetadataOnly); err != nil {
As mentioned in Slack - don't think this is fully working. The metadata-only default collection gets a full set of indexes.

2023-02-21 19:51 UTC, torcolvin commented on rest/integrationtest/integration_test.go
> +		require.Equal(t, users, responseUsers)
Works on walrus/views, but I added some actual index asserts to catch bug you pointed out.

2023-02-22 15:00 UTC, bbrks requested changes
Can we roll back the unrelated changes to context logging in this PR and revisit separately?

I don't want to hold up this PR as it's required for RC1, and looks basically good to merge, but there's further work to do on the context logging (see inline comment)

2023-02-22 15:00 UTC, bbrks commented on base/logging_context.go
>  	}
I don't want to hold up the functional changes we're aiming to get completed by Friday, so I think we should back these changes out for now and move forwards with the index changes in this PR.

It feels unrelated/scope creep to this PR and has issues with the current implementation. Doesn't seem to be consistently applied, resulting in even related logs looking like this:

```
2023-02-22T14:40:59.796Z [INF] col:b1.foo.bar Verifying index availability...
2023-02-22T14:40:59.814Z [INF] b:b1.bar Indexes not ready - retrying...
2023-02-22T14:40:59.919Z [INF] b:b1.bar Indexes not ready - retrying...
2023-02-22T14:41:00.124Z [INF] b:b1.bar Indexes not ready - retrying...
2023-02-22T14:41:00.527Z [INF] b:b1.bar Indexes not ready - retrying...
2023-02-22T14:41:01.333Z [INF] b:b1.bar Indexes not ready - retrying...
...
2023-02-22T14:41:02.943Z [INF] b:b1.bar Index sg_access_x1 is online
2023-02-22T14:41:02.943Z [INF] b:b1.bar Index sg_allDocs_x1 is online
2023-02-22T14:41:02.943Z [INF] b:b1.bar Index sg_channels_x1 is online
2023-02-22T14:41:02.943Z [INF] b:b1.bar Index sg_roleAccess_x1 is online
2023-02-22T14:41:02.943Z [INF] b:b1.bar Index sg_tombstones_x1 is online
2023-02-22T14:41:02.943Z [INF] col:b1.foo.bar Indexes ready
2023-02-22T14:41:02.943Z [INF] col:b1 Initializing indexes with numReplicas: 0...
```

Open questions around context logging which should end up being answered in a ticket before we actually make the changes:
- Is bucket (and possibly scope) already implied by `db` context logging?
- Should `col:` be fully qualified, or compact assuming `db` is present and above is true. We've hashed this out a few times in Slack and always settled on non-qualified, it seems we're changing it in this PR to now be fully qualified?

2023-02-22 15:10 UTC, torcolvin commented on base/logging_context.go
>  	}
I agree these are good questions, and should probably we elucidated. There are exceptional cases that we are finding.

In this case, we are creating indexes before we have a db, so we don't know the bucket, except via the database, implicitly. In this case the database hasn't been created.

For the DBRegistry, we are going to see the same problems of not having a bucket. Additionally, the logging is actually different for test code and not test code. I don't think we generally see the `b:` logging outside of tests, except in the situation I just described.

2023-02-22 15:19 UTC, bbrks approved these changes

2023-02-22 15:22 UTC, merged