CBG-2733 make tests pass without xattrs
couchbaselabs/sync_gateway pull request #6122
Opened 2023-03-01 14:44 UTC by torcolvin

- Some changes to rest/indextest for account of different test names
- Changed the db/indexes_test.go to use defer to clean up failed tests, and actually drop all indexes if they actually create indexes that aren't accounted for by the db setup. I'd like to move these tests to /db/indexestest because they are costly to run and also have propensity to kill the indexing service, and at least they'd be isolated from other db tests.
- change test bucket pool to create indexes on `_default._default` as metadata only if using default collection. This holds true for `db` package, but if someone creates `NewRestTesterDefaultCollection`, then `server_context.go` will create all indexes on the default bucket anyway in test.

## Pre-review checklist
- [x] Removed debug logging (`fmt.Print`, `log.Print`, ...)
- [x] Logging sensitive data? Make sure it's tagged (e.g. `base.UD(docID)`, `base.MD(dbName)`)
- [x] Updated relevant information in the API specifications (such as endpoint descriptions, schemas, ...) in `docs/api`

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [x] `GSI=true,xattrs=true,default_collection=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/1562/
- [x] `GSI=true,xattrs=false,default_collection=false` https://jenkins.sgwdev.com/job/SyncGateway-Integration/1563/
- [x] `GSI=true,xattrs=true,default_collection=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/1564/
- [x] `GSI=true,xattrs=false,default_collection=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/1565/

2023-03-01 15:01 UTC, adamcfraser requested changes

2023-03-01 15:01 UTC, adamcfraser commented on db/indexes_test.go
> +					UseXattrs:   base.TestUseXattrs(),
The UseXattrs here doesn't match line 82.  Is that intentional?  Would it be better to move this defer below line 78 and just reuse `options`?

2023-03-01 15:01 UTC, adamcfraser commented on db/indexes_test.go
> +			if sgIndex.simpleName != indexNames[IndexTombstones] {
I don't think we should be looking for specific index names here - if we add another index with the same characteristics (xattrs only), this test will start failing and need additional index-specific handling.  

Why doesn't shouldCreate already evaluate whether IndexTombstones is going to be created?  It's doing a check for i.IsXattrOnly() in there.

2023-03-01 15:01 UTC, adamcfraser commented on db/indexes_test.go
> +			if sgIndex.simpleName != indexNames[IndexTombstones] {
Is the underlying problem is that the initial cleanup using removeObsoleteIndexes on line 139 isn't properly removing the tombstone index?

2023-03-01 15:29 UTC, torcolvin commented on db/indexes_test.go
> +			if sgIndex.simpleName != indexNames[IndexTombstones] {
I'm going to change this to see if it's an xattr only index.

2023-03-01 15:30 UTC, torcolvin commented on db/indexes_test.go
> +					UseXattrs:   base.TestUseXattrs(),
This will go away if I can drop indexes between tests, but basically it is restoring the state to what the bucket pool expects.

2023-03-02 17:35 UTC, adamcfraser approved these changes

2023-03-02 17:35 UTC, merged