CBG-1971: TestReplicationConcurrentPush flaky test fix
couchbaselabs/sync_gateway pull request #6173
Opened 2023-04-04 15:36 UTC by gregns1

CBG-1971

Test was flaking on waiting for nodes to be assigned. But also did a few runs where that wasn't included and notcied that it also failed on asserting for the number of docs pushed on the second replicator (rep_DEF). After digging into the losg I noticed that in all cases where it failed for this reaon I saw a log line:
`[INF] Replicate: t:TestReplicationConcurrentPush c:sgr-mgr- db:activedb Initializing replication <ud>rep_ABC</ud>`
But no corresponding log line for the second created replications (rep_DEF). When looking into the code I noticed this is called when refreshing the sgreplicate config. So I think there was a race between the first and second replication getting added to be included on this 'refresh' before asserting on replication stats.  So I added a wait for condition on the active replicator count on sg replicate. 

## Pre-review checklist
- [ ] Removed debug logging (`fmt.Print`, `log.Print`, ...)
- [ ] Logging sensitive data? Make sure it's tagged (e.g. `base.UD(docID)`, `base.MD(dbName)`)
- [ ] Updated relevant information in the API specifications (such as endpoint descriptions, schemas, ...) in `docs/api`

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [ ] `GSI=true,xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/000/

2023-04-06 13:59 UTC, bbrks requested changes
I'm not convinced that we're not just avoiding a real-world race condition here that we'd like to handle better (with CAS retry/update callback)

2023-04-06 13:59 UTC, bbrks commented on db/sg_replicate_cfg.go
> +	return m.activeReplicators
I think we need a lock to read values from this map (`m.activeReplicatorsLock`) and given the function returns the full map, we have no control over the locking.

We'll either need to make a full copy of the map, or given the use case, maybe a method specifically for retrieving `NumActiveReplicators()` which holds the lock whilst calling `len()`

2023-04-06 13:59 UTC, bbrks commented on rest/replicatortest/replicator_test.go
> -	activeRT.CreateReplication("rep_DEF", remoteURLString, db.ActiveReplicatorTypePush, []string{"DEF"}, true, db.ConflictResolverDefault)
Is there actually a bug here where we're not able to create two replications at the same time?

I'd expect the CAS retry in `sgReplicateManager.updateCluster` ensures that both could be created, even if concurrently, as it's something the REST API could potentially allow to happen in the real world.

2023-04-06 15:24 UTC, gregns1 commented on rest/replicatortest/replicator_test.go
> -	activeRT.CreateReplication("rep_DEF", remoteURLString, db.ActiveReplicatorTypePush, []string{"DEF"}, true, db.ConflictResolverDefault)
So my analysis of the problem (I could be wrong) was that we can create two at the same time, but the changes to sg replicate config come through on a channel `cfgEvents` and we have a race where sometimes where only the first replication is picked up and takes time to initialise. Then by the time the second replication is processed as a cfg change and goes through the refresh config/initialise replication process the test is already asserting against the stats for that replication. I think in real world for customers the replication will initialise eventually. Also think that this test isn't really a problem when running against server I think its more flaking for walrus and I put that down to the added latency when communicating with server helping in the context of the test?

2023-04-06 15:24 UTC, gregns1 commented on db/sg_replicate_cfg.go
> +	return m.activeReplicators
Good point will change this!

2023-04-13 16:26 UTC, bbrks commented on rest/replicatortest/replicator_test.go
> -	activeRT.CreateReplication("rep_DEF", remoteURLString, db.ActiveReplicatorTypePush, []string{"DEF"}, true, db.ConflictResolverDefault)
The thing that makes me uncertain of that is that we don't see any logging associated with `rep_DEF` in the entire test (which runs for ~20 seconds)

https://mobile.jenkins.couchbase.com/job/sgw-unix-build/26219/consoleFull 

It's almost like DEF never even gets created (or at least assigned to a node)

2023-04-20 17:19 UTC, bbrks approved these changes
I'm OK with this fix after in-person discussion.

2023-04-20 17:20 UTC, merged