Add 3.1 release manifest
couchbaselabs/sync_gateway pull request #6174
Opened 2023-04-06 13:10 UTC by torcolvin

Should I also add a file for 

manifest/3.1/3.1.0.xml with duplicate contents of 3.1.xml or leave that to the inevitable 3.1.1 point release?

I was going to merge this change into the release branch AND master.

2023-04-06 13:27 UTC, bbrks commented
- `3.1.0.xml` comes only when we have a new `3.1.x` release (otherwise you'd end up with 2 `3.1.0` manifests)
- Nothing reads the branch version of `product-config.json` - `master` is the source of truth for what versions to build. Changing this isn't nessesary.
- We can get the `3.1.0.xml` into the release branch for our weird Jenkins jobs that depend on the release branch - but the build team's jobs read the `master` version.

2023-04-06 14:39 UTC, torcolvin commented
> * Nothing reads the branch version of `product-config.json` - `master` is the source of truth for what versions to build. Changing this isn't nessesary.

Do you prefer to have release branch match master? Is it correct in theory that none of this needs to be done on the release branch?

2023-04-06 16:36 UTC, bbrks requested changes
A couple of things (these are in the doc)

2023-04-06 16:36 UTC, bbrks commented on manifest/3.1.xml
> +   <project name="sync_gateway" path="sync_gateway" remote="couchbase" />
We need to let them know where to find 3.1.0 in SG's repo here:

```suggestion
   <project name="sync_gateway" path="sync_gateway" remote="couchbase" revision="release/3.1.0"/>
```

2023-04-06 16:36 UTC, bbrks commented on manifest/product-config.json
The `manifest/default.xml` entry (starting line 4) needs updating to `"release": "3.2.0",` now

2023-04-06 16:36 UTC, bbrks commented on manifest/default.xml
Also need to make this change in `base/version.go` (`ProductAPIVersionMinor = "2"`)

2023-04-06 16:36 UTC, bbrks commented on manifest/product-config.json
> +            "start_build": 1
`"start_build"` needs to be `+1` of the current build numebr of 3.1.0 to ensure any subsequent builds get assigned the next build number.

At time of writing the latest build is `585`: 
http://latestbuilds.service.couchbase.com/builds/latestbuilds/sync_gateway/3.1.0/

2023-04-11 13:14 UTC, bbrks requested changes
the revision was added in the wrong place in the manifest

2023-04-11 13:14 UTC, bbrks commented on manifest/3.1.xml
> +   <project name="sync_gateway" path="sync_gateway" remote="couchbase" />
this wasn't fixed

2023-04-11 13:14 UTC, bbrks commented on manifest/3.1.xml
> +  <remote fetch="https://github.com/couchbase/" name="couchbase" revision="release/3.1.0"/>
remotes don't have revisions

```suggestion
  <remote fetch="https://github.com/couchbase/" name="couchbase"/>
```

2023-04-11 13:45 UTC, bbrks approved these changes

2023-04-11 13:45 UTC, merged