CBG-2807 allow CORS on a per database level
couchbaselabs/sync_gateway pull request #6179
Opened 2023-04-11 17:48 UTC by torcolvin

Possible additions for testing:

- dynamically change CORS in with an updated config
- test base CORS in bootstrap config with override in server config?

## Pre-review checklist
- [x] Removed debug logging (`fmt.Print`, `log.Print`, ...)
- [x] Logging sensitive data? Make sure it's tagged (e.g. `base.UD(docID)`, `base.MD(dbName)`)
- [x] Updated relevant information in the API specifications (such as endpoint descriptions, schemas, ...) in `docs/api`

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [ ] `GSI=true,xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/000/

2023-04-11 21:07 UTC, adamcfraser requested changes

2023-04-11 21:07 UTC, adamcfraser commented on rest/handler.go
> +func (h *handler) _validateAndWriteHeaders(method handlerMethod, accessPermissions []Permission, responsePermissions []Permission) error {
We typically reserve the leading underscore for methods that require the caller to hold a mutex.  That doesn't seem to be the case here.

2023-04-11 21:07 UTC, adamcfraser commented on rest/handler.go
> +		// Now that we know the DB, add CORS headers to the response:
Should we bypass this functionality if err is non-nil?  Wouldn't adding the CORS headers in the error case leak information about db existence if auth fails below?  (tests for this case would be recommended)

2023-04-13 18:25 UTC, torcolvin commented on rest/handler.go
> +		// Now that we know the DB, add CORS headers to the response:
nope, I think this is OK based on testing.

2023-04-14 17:07 UTC, adamcfraser requested changes

2023-04-14 17:07 UTC, adamcfraser commented on rest/handler.go
> +		// Now that we know the DB, add CORS headers to the response:
Which test covers this case?  The case I'm thinking of is:
- database 'abc' has db-specific CORS config enabled
- database 'def' does not exist
- user bob doesn't have access to abc
- if user bob makes a request to abc, doesn't he get CORS response headers that he does not see for the same request to def?

2023-04-14 17:07 UTC, adamcfraser commented on rest/api_test.go
> +	response := rt.SendRequestWithHeaders("GET", "/db/", "", reqHeaders)
Why is this 'db' and not {{.db}}? If there's a reason, maybe stick a comment in the test.

2023-04-14 17:07 UTC, adamcfraser commented on rest/routing.go
> +					response.Header().Add("Access-Control-Max-Age", strconv.Itoa(cors.MaxAge))
This looks like it's always going to be the server-config level setting, and doesn't get updated later when we call AddResponseHeaders in invoke.  Is that the intended behaviour?

2023-04-14 19:32 UTC, torcolvin commented on rest/routing.go
> +					response.Header().Add("Access-Control-Max-Age", strconv.Itoa(cors.MaxAge))
Added `TestCorsNoMux` for this, it's intended behavior for when we don't match anything on `mux.Router`.

2023-04-14 19:34 UTC, torcolvin commented on rest/api_test.go
> +	response := rt.SendRequestWithHeaders("GET", "/db/", "", reqHeaders)
Code was written before the templating existed, I added it here.

2023-04-14 19:55 UTC, adamcfraser commented on rest/routing.go
> +					response.Header().Add("Access-Control-Max-Age", strconv.Itoa(cors.MaxAge))
My question was for the case where we *do* match something on mux.Router, I don't think Access-Control-Max-Age gets updated to the db-specific value?

2023-04-14 20:42 UTC, adamcfraser approved these changes

2023-04-14 23:53 UTC, adamcfraser requested changes
It looks like TestCORSOriginPerDatabase is failing with the latest changes, since it attempts to make requests as the GUEST user, and GUEST is disabled (so it's falling back to the server-level CORS config).

2023-04-17 14:13 UTC, torcolvin commented on rest/routing.go
> +					response.Header().Add("Access-Control-Max-Age", strconv.Itoa(cors.MaxAge))
I wrote some validation so you can only set Max-Age on bootstrap to clarify this.

2023-04-17 18:29 UTC, adamcfraser requested changes
Fixes look good - two minor questions.

2023-04-17 18:29 UTC, adamcfraser commented on rest/handler.go
> +		if h.privs != adminPrivs {
Should this include `&& h.privs != metricPrivs`?  Usage seems inconsistent below (existing line 369 below looks like it should be doing the same), but I think it's a no-op there because dbcontext will always be nil for metrics calls.  For this case, it feels like we shouldn't be setting CORS (even the server config CORS) on the metrics endpoint.

2023-04-17 18:29 UTC, adamcfraser commented on docs/api/components/schemas.yaml
> +        max_age:
Can we remove this from the API definition, since we don't support it being set at the database level?

2023-04-17 18:40 UTC, adamcfraser approved these changes

2023-04-17 18:50 UTC, merged