Speed up tests by reducing sleep/wait loop
couchbaselabs/sync_gateway pull request #6198
Opened 2023-04-19 21:12 UTC by torcolvin

Reduces test time by about 4 minutes and avoids cpu spin in javascript code.

Create a parameter for UserFunctionTimeout to be able to modify in test.

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [x] `GSI=true,xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/1716/

2023-04-19 21:57 UTC, snej approved these changes, later dismissed

2023-04-19 21:59 UTC, adamcfraser requested changes

2023-04-19 21:59 UTC, adamcfraser commented on db/database.go
> +		UserFunctionTimeout: 60 * time.Second,
It's preferable to leave this defined as a constant and reference it here (i.e. change existing constant to DefaultUserFunctionTimeout).

2023-04-19 21:59 UTC, adamcfraser commented on rest/functionsapitest/graphql_queries_test.go
> +	timeout := 2 * time.Second
Even 2 seconds seems like a long wait for a single unit test.  Is this length of time needed?

2023-04-20 17:17 UTC, bbrks approved these changes

2023-04-27 15:59 UTC, adamcfraser approved these changes

2023-04-27 15:59 UTC, merged