Feature/v8 build tag
couchbaselabs/sync_gateway pull request #6201
Opened 2023-04-20 13:55 UTC by torcolvin

Add a build tag to enable v8 or otto only.

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [ ] `GSI=true,xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/1718/

2023-04-20 19:57 UTC, snej commented
I'm not clear on what all these code changes do. Are you trying to do the equivalent of `#ifdef`-ing all the V8-dependent code so it's possible to build without V8?

2023-04-20 20:01 UTC, torcolvin commented
> I'm not clear on what all these code changes do. Are you trying to do the equivalent of `#ifdef`-ing all the V8-dependent code so it's possible to build without V8?

Yeah, the idea is to build without V8 for beryllium and and with V8 for elixir. We also know it won't compile on windows at all, so this would allow us to merge to master.

2023-04-21 20:10 UTC, snej commented on js/underscore-umd-min.js
> + * Copyright 2023-Present Couchbase, Inc.
We can't claim copyright on this -- it's a 3rd party JS library.

2023-04-21 20:11 UTC, snej requested changes

2023-04-21 20:11 UTC, snej commented on js/underscore-umd.js
> + * Copyright 2023-Present Couchbase, Inc.
We can't claim copyright on this -- it's a 3rd party JS library.

2023-04-24 20:56 UTC, snej approved these changes

2023-04-24 20:57 UTC, merged