CBG-2938: Ignore Cbgt EOF feed errors when intentionally stopped
couchbaselabs/sync_gateway pull request #6235
Opened 2023-05-11 08:55 UTC by bbrks

CBG-2938

- Changed `CbgtContext.StopHeartbeatListener` to `CbgtContext.Stop`
- Made event handler context cancellable from `Stop`
- Made `OnFeedError` callback check context for cancellation before logging about EOF

## Pre-review checklist
- [x] Removed debug logging (`fmt.Print`, `log.Print`, ...)
- [x] Logging sensitive data? Make sure it's tagged (e.g. `base.UD(docID)`, `base.MD(dbName)`)
- [x] Updated relevant information in the API specifications (such as endpoint descriptions, schemas, ...) in `docs/api`

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [ ] `GSI=true,xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/1776/

2023-05-11 14:03 UTC, torcolvin reviewed
LGTM otherwise

2023-05-11 14:03 UTC, torcolvin commented on db/import_listener.go
> +			il.cbgtContext.Stop()
does Stop() stop both?

2023-05-11 14:03 UTC, torcolvin commented on base/dcp_sharded.go
> +			if meh.ctx.Err() != context.Canceled {
slightly prefer errors.Is in case that error gets wrapped

2023-05-11 14:42 UTC, bbrks commented on db/import_listener.go
> +			il.cbgtContext.Stop()
yep

2023-05-11 14:57 UTC, bbrks commented on base/dcp_sharded.go
> +			if meh.ctx.Err() != context.Canceled {
I'm ok switching this to `!errors.Is(meh.ctx.Err(), context.Canceled)` as it does still work, but errors from `context.Err()` _can't_ be wrapped.

`context` (in 1.20+) has its own way of "wrapping" that still results in `Err()` only returning one of:
- `nil`
- `context.Canceled`
- `context.DeadlineExceeded`

And `errors.Is` still doesn't really support `Err()` as you'd expect it to.

example:
https://go.dev/play/p/XE9rdrP7F9A

2023-05-11 15:12 UTC, torcolvin commented on base/dcp_sharded.go
> +			if meh.ctx.Err() != context.Canceled {
This to leave as is fine, it was just a automatic reaction to seeing an error comparison.

2023-05-11 15:27 UTC, adamcfraser requested changes

2023-05-11 15:27 UTC, adamcfraser commented on base/dcp_sharded.go
> +func (c *CbgtContext) Stop() {
I agree it makes sense to have a more generic CbgtContext.Stop(), but if we're doing that, the rest of the 'on stop' code from importListener.Stop should get moved there as well.

2023-05-12 20:20 UTC, adamcfraser approved these changes

2023-05-12 20:20 UTC, merged