pass context through change listener functions
couchbaselabs/sync_gateway pull request #6331
Opened 2023-07-11 16:27 UTC by torcolvin

This adds database level logging for change feed/cache and collection logging for the change waiter.

## Pre-review checklist
- [x] Removed debug logging (`fmt.Print`, `log.Print`, ...)
- [x] Logging sensitive data? Make sure it's tagged (e.g. `base.UD(docID)`, `base.MD(dbName)`)
- [x] Updated relevant information in the API specifications (such as endpoint descriptions, schemas, ...) in `docs/api`

https://github.com/couchbase/sg-bucket/pull/92
https://github.com/couchbaselabs/walrus/pull/80

## Dependencies (if applicable)
- [x] Link upstream PRs
- [ ] Update Go module dependencies when merged

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [ ] `GSI=true,xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/000/

2023-07-12 23:07 UTC, adamcfraser requested changes
Generally looks good, but I'm not convinced we need to pass the context per-event (see comment on the sg-bucket PR).  If you think there's a good reason to do so (as opposed to using a context associated with the changeListener/importListener), let me know.

2023-07-17 20:41 UTC, torcolvin commented
> Generally looks good, but I'm not convinced we need to pass the context per-event (see comment on the sg-bucket PR). If you think there's a good reason to do so (as opposed to using a context associated with the changeListener/importListener), let me know.

You are right, I simplified the code here and the upstream PRs.

2023-07-19 16:12 UTC, adamcfraser commented
@torcolvin LGTM - I've merged the dependencies, once those are updated can merge.

2023-07-19 16:12 UTC, adamcfraser approved these changes, later dismissed

2023-07-19 16:28 UTC, adamcfraser approved these changes

2023-07-19 19:21 UTC, merged