Initial implementation of per-db console log settings
couchbaselabs/sync_gateway pull request #6348
Opened 2023-07-31 15:14 UTC by bbrks

CBG-0000

Stores a reference to the database log configuration inside the database-scoped log context, so that we're able to look it up when we log to determine _how_ to log, for a particular database.

This allows databases to define their own console log level and log keys, which will be used if the log is associated with a database, instead of the node-level settings.

Neither of the two settings takes precedence. They're additive (either node OR db log level/key are checked when writing a log line, if either match, it will be logged).

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [ ] `GSI=true,xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/000/

2023-08-10 11:15 UTC, JRascagneres approved these changes, later dismissed

2023-08-11 18:50 UTC, adamcfraser reviewed
Approach seems reasonable - added a question about whether background context makes sense in some cases.

2023-08-11 18:50 UTC, adamcfraser commented on base/logger_external.go
> +	if consoleLogger != nil && consoleLogger.shouldLog(context.Background(), LevelDebug, KeyWalrus) {
Does it make sense to pass context.Background() to shouldLog when we don't have an actual context?   shouldLogDatabaseContext looks like it exits earliest if the context is nil - would it be preferable to leave as nil?

2023-08-15 14:29 UTC, IsaacLambat requested changes
The Rest API documentation needs changing (`docs/api/components/schemas.yaml L1129`)

2023-08-15 15:34 UTC, IsaacLambat approved these changes

2023-08-21 09:43 UTC, merged