CBG-3207: Implementation of persisted form of HLV.
couchbaselabs/sync_gateway pull request #6358
Opened 2023-08-03 13:26 UTC by gregns1

CBG-3207

Converts the in memory representation of HLV in #6345 to correct format for persistence. 

Note: This replies upon #6345 being merged first and rebased upon top of that. Not ready for a review till this has happened and will stay in draft mode till then. 

## Pre-review checklist
- [ ] Removed debug logging (`fmt.Print`, `log.Print`, ...)
- [ ] Logging sensitive data? Make sure it's tagged (e.g. `base.UD(docID)`, `base.MD(dbName)`)
- [ ] Updated relevant information in the API specifications (such as endpoint descriptions, schemas, ...) in `docs/api`

## Dependencies (if applicable)
- [x] Link upstream PRs -> https://github.com/couchbase/sync_gateway/pull/6345
- [ ] Update Go module dependencies when merged

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [ ] `GSI=true,xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/000/

2023-08-04 18:57 UTC, adamcfraser requested changes

2023-08-04 18:57 UTC, adamcfraser commented on db/hybrid_logical_vector.go
> +		encodedValue, err := base.HexToBase64(hlv.SourceID)
I don't think we want to make any assumption about the format of non-server SourceIDs (i.e. that they are hex values).  Replicating peers *should* be defining a storage-optimized sourceID value, but I think it's going to be that peer's responsibility to do so, and SG shouldn't do any additional formatting.

2023-08-04 18:57 UTC, adamcfraser commented on db/hybrid_logical_vector.go
> +		persistedSRC = "m_" + persistedSRC
I don't think we want/need the 'm_' prefix - as above, replicating peers should be defining their own sourceID, and I don't think the m_ prefix is required.

2023-08-04 18:57 UTC, adamcfraser commented on db/hybrid_logical_vector.go
> +		encodedValue, err := base.HexToBase64(hlv.SourceID)
More generally, I think it makes sense for the in-memory storage of the sourceIDs to match the format used during persistence, to simplify triaging issues where we're comparing log output to persisted HLVs.

I understand this makes it more work to get from a sourceID back to a bucket UUID, but that seems like the less common comparison of the two.

2023-08-16 13:18 UTC, bbrks submitted a review, later dismissed
Looks alright to me. Will leave @adamcfraser to final approval/merge

2023-08-17 22:30 UTC, adamcfraser requested changes
Approach looks good - one question about omitempty handling for non-required fields.

2023-08-17 22:30 UTC, adamcfraser commented on db/hybrid_logical_vector.go
> +	cvCasByteArray := base.Uint64CASToLittleEndianHex(hlv.CurrentVersionCAS)
Since cvCas is omitempty, do we want to do a zero check here first before converting to a non-empty string?

2023-08-21 15:09 UTC, adamcfraser approved these changes

2023-08-21 15:09 UTC, merged