Avoid a data race on writing db.PurgeInterval during test
couchbaselabs/sync_gateway pull request #6363
Opened 2023-08-08 14:26 UTC by torcolvin

allow specifying PurgeInterval in DatabaseContextOptions to override the value we might return from the server.

Since this value is re-read each time, remove it from DatabaseContext struct

fixes:

```
WARNING: DATA RACE
19:22:08 Read at 0x00c000135d40 by goroutine 28379:
19:22:08   github.com/couchbase/sync_gateway/db.(*Database).Compact()
19:22:08       /Users/couchbase/workspace/sgw-unix-build/3.2.0/community/sync_gateway/db/database.go:1419 +0x128
19:22:08   github.com/couchbase/sync_gateway/db.(*DatabaseContext).StartOnlineProcesses.func9()
19:22:08       /Users/couchbase/workspace/sgw-unix-build/3.2.0/community/sync_gateway/db/database.go:2349 +0x58
19:22:08   github.com/couchbase/sync_gateway/db.NewBackgroundTask.func1()
19:22:08       /Users/couchbase/workspace/sgw-unix-build/3.2.0/community/sync_gateway/db/utils.go:45 +0x194
19:22:08 
19:22:08 Previous write at 0x00c000135d40 by goroutine 28336:
19:22:08   github.com/couchbase/sync_gateway/db.TestImportCompactPanic()
19:22:08       /Users/couchbase/workspace/sgw-unix-build/3.2.0/community/sync_gateway/db/database_test.go:2995 +0x154
19:22:08   testing.tRunner()
19:22:08       /Users/couchbase/cbdeps/go1.20.3/src/testing/testing.go:1576 +0x188
19:22:08   testing.(*T).Run.func1()
19:22:08       /Users/couchbase/cbdeps/go1.20.3/src/testing/testing.go:1629 +0x40
19:22:08 
19:22:08 Goroutine 28379 (running) created at:
19:22:08   github.com/couchbase/sync_gateway/db.NewBackgroundTask()
19:22:08       /Users/couchbase/workspace/sgw-unix-build/3.2.0/community/sync_gateway/db/utils.go:37 +0x360
19:22:08   github.com/couchbase/sync_gateway/db.(*DatabaseContext).StartOnlineProcesses()
19:22:08       /Users/couchbase/workspace/sgw-unix-build/3.2.0/community/sync_gateway/db/database.go:2348 +0x1a64
19:22:08   github.com/couchbase/sync_gateway/db.setupTestDBWithOptionsAndImport()
19:22:08       /Users/couchbase/workspace/sgw-unix-build/3.2.0/community/sync_gateway/db/database_test.go:67 +0x144
19:22:08   github.com/couchbase/sync_gateway/db.TestImportCompactPanic()
19:22:08       /Users/couchbase/workspace/sgw-unix-build/3.2.0/community/sync_gateway/db/database_test.go:2991 +0xd0
19:22:08   testing.tRunner()
19:22:08       /Users/couchbase/cbdeps/go1.20.3/src/testing/testing.go:1576 +0x188
19:22:08   testing.(*T).Run.func1()
19:22:08       /Users/couchbase/cbdeps/go1.20.3/src/testing/testing.go:1629 +0x40
19:22:08 
19:22:08 Goroutine 28336 (running) created at:
19:22:08   testing.(*T).Run()
19:22:08       /Users/couchbase/cbdeps/go1.20.3/src/testing/testing.go:1629 +0x5e4
19:22:08   testing.runTests.func1()
19:22:08       /Users/couchbase/cbdeps/go1.20.3/src/testing/testing.go:2036 +0x80
19:22:08   testing.tRunner()
19:22:08       /Users/couchbase/cbdeps/go1.20.3/src/testing/testing.go:1576 +0x188
19:22:08   testing.runTests()
19:22:08       /Users/couchbase/cbdeps/go1.20.3/src/testing/testing.go:2034 +0x700
19:22:08   testing.(*M).Run()
19:22:08       /Users/couchbase/cbdeps/go1.20.3/src/testing/testing.go:1906 +0x950
19:22:08   github.com/couchbase/sync_gateway/base.TestBucketPoolMain()
19:22:08       /Users/couchbase/workspace/sgw-unix-build/3.2.0/community/sync_gateway/base/main_test_bucket_pool.go:705 +0x374
19:22:08   github.com/couchbase/sync_gateway/db.TestBucketPoolWithIndexes()
19:22:08       /Users/couchbase/workspace/sgw-unix-build/3.2.0/community/sync_gateway/db/util_testing.go:490 +0x350
19:22:08   github.com/couchbase/sync_gateway/db.TestMain()
19:22:08       /Users/couchbase/workspace/sgw-unix-build/3.2.0/community/sync_gateway/db/main_test.go:21 +0x308
19:22:08   main.main()
19:22:08       _testmain.go:661 +0x304
19:22:08 ==================
```

## Pre-review checklist
- [x] Removed debug logging (`fmt.Print`, `log.Print`, ...)
- [x] Logging sensitive data? Make sure it's tagged (e.g. `base.UD(docID)`, `base.MD(dbName)`)
- [x] Updated relevant information in the API specifications (such as endpoint descriptions, schemas, ...) in `docs/api`

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [ ] `GSI=true,xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/1958/

2023-08-16 13:25 UTC, bbrks requested changes
Have a question about the `DbConfig` change specifically, otherwise I agree with this change.

2023-08-16 13:25 UTC, bbrks commented on rest/config.go
> +	MetadataPurgeIntervalOverride *time.Duration
I'm not overly keen on putting this in a Customer-facing config struct given it's to set a test value.

Is there a reason why the RestTester-based tests couldn't this? I guess maybe it might still trigger the race detector?

```go
zero := time.Duration(0)
rt.GetDatabase().Options.PurgeInterval = &zero
```

2023-08-21 13:45 UTC, torcolvin commented on rest/config.go
> +	MetadataPurgeIntervalOverride *time.Duration
I changed this here.

2023-08-22 18:44 UTC, bbrks approved these changes

2023-08-23 18:42 UTC, merged