CBG-3352 lock on load, and when determining invalid
couchbaselabs/sync_gateway pull request #6390
Opened 2023-09-05 18:08 UTC by torcolvin

I think the lock in `loadForDoc` is mostly harmless - the function cost is minimal, though there's an allocation if you need to do `body.ShallowCopy`, but it's once per cache value.

I don't know that this is better (maybe I should write a benchmark for this?) but we could make the `valid` struct an atomic so access is a single CPU instruction. I assumed the slowness was in the `Unmarshal`  rather than other parts of the code.

The tests that hit the data race are `TestRemovingUserXattr` and `TestUserXattrAvoidRevisionIDGeneration`.

2023-09-05 19:06 UTC, adamcfraser requested changes

2023-09-05 19:06 UTC, adamcfraser commented on db/revision_cache_lru.go
> +	value.lock.RLock()
This is the check that has performance implications, particularly on systems with a large number of cores, where acquiring a read lock can require scheduling work across cores.  We've seen this in our performance testing in the past, which is how we ended up with the design that attempts to keep the value immutable.  
As discussed, the invalidation flag breaks this immutability so we're going to need to change something.  I don't think switching back to acquiring a read lock on value is the ideal approach, as invalidation is an uncommon use case, and we'd be taking on that cost on every rev cache read.

2023-09-06 16:09 UTC, adamcfraser approved these changes

2023-09-06 16:09 UTC, adamcfraser commented
Looks good - thanks!

2023-09-06 16:09 UTC, merged

2023-09-06 16:17 UTC, bbrks requested changes
Suggestion for alternative method of removal

2023-09-06 16:17 UTC, bbrks commented on db/revision_cache_lru.go
> +	rc.removeValue(value)
`getValue` does a non-zero amount of work to update the LRU, even though we're about to remove the entry, as well as aquiring the revcache lock in both get and remove.

Maybe it's better to implement a remove method that only requires key?

You could essentially do:

```go
key := IDAndRev{DocID: docID, RevID: revID}
rc.lock.Lock()
defer rc.lock.Unlock()
if element := rc.cache[key]; element != nil {
	rc.lruList.Remove(element)
}
delete(rc.cache, key)
```