CBG-3379 add missing context logging
couchbaselabs/sync_gateway pull request #6408
Opened 2023-09-11 13:12 UTC by torcolvin

- add contexts through functions
- does not include any places needed to make modifications to sg-bucket (will come in a separate PR)

Performed a search on context.Background() and context.TODO() and followed them through.

There are a few cases I didn't change:

- generally things should come from context.Background() in the start of main, but there were some cases we use logging in init
- there are a few cases we intentionally reset context during replication and ISGR, but these will need to be tagged with a database

I think the way to review this is to see where I've changed `context.Background()` to something that is passed in. Sometimes this could be a problem 

## Pre-review checklist
- [x] Removed debug logging (`fmt.Print`, `log.Print`, ...)
- [x] Logging sensitive data? Make sure it's tagged (e.g. `base.UD(docID)`, `base.MD(dbName)`)
- [x] Updated relevant information in the API specifications (such as endpoint descriptions, schemas, ...) in `docs/api`

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [x] `GSI=true,xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/2002

2023-09-12 13:56 UTC, bbrks requested changes
Looks good - some comments inline for specifics about:
- Consistency on interface methods (all or none?)
- Structs that have embedded contexts AND parameterised context
- `bh.loggingCtx` 3.1.0 regression for default collection

2023-09-12 13:56 UTC, bbrks commented on base/collection_gocb.go
> +		WarnfCtx(ctx, "Unable to obtain gocbcore.Agent while retrieving expiry:%v", err)
Arguably this should be a wrapped error rather than a log but agree with TODO for now to coordinate other sg-bucket API changes.

2023-09-12 13:56 UTC, bbrks commented on db/change_cache.go
> +	return c.channelCache.Remove(ctx, collectionID, docIDs, startTime)
Is there a pattern/rule to follow for usage of parameter context vs. `c.logCtx`? Usage-dependent?

Having context defined only in some methods makes me wonder how we're going to maintain this with any consistency going forwards.

2023-09-12 13:56 UTC, bbrks commented on db/channel_cache.go
> +	MaxCacheSize(context.Context) int
Shouldn't we make context consistent across the full interface? Even if the current implementation doesn't actually use context in all methods?

2023-09-12 13:56 UTC, bbrks commented on db/blip_handler.go
> +		seq, err := bh.collection.LastSequence(bh.loggingCtx)
As mentioned via Slack - What looks like a 3.1.0 regression - `bh.loggingCtx` isn't being set properly for default collection replications, resulting in us losing context ID for a lot of logging called via BLIP.

2023-09-12 18:29 UTC, torcolvin commented on db/change_cache.go
> +	return c.channelCache.Remove(ctx, collectionID, docIDs, startTime)
I largely didn't change the existing code - but I think writing new code we should try to pass a context in. There are some places this is impractical:

- DCP related code (especially but not limited to cbgt) with specific callbacks we have to match interfaces with

I was thinking in main branch we have the opportunity to clean this up but not for log streaming.

2023-09-13 16:41 UTC, bbrks submitted a review, later dismissed

2023-09-13 16:42 UTC, bbrks approved these changes

2023-09-13 17:03 UTC, merged