CBG-3356: Add current version to ChangeEntry
couchbaselabs/sync_gateway pull request #6575
Opened 2023-11-14 14:47 UTC by gregns1

CBG-3356

- Add CV to change entry 
- Populated when constructing the change entry from log entries retrieved from the channel cache 
- Test that check that changes are correctly populated  
- NOTE: each test has to check for changes before adding doc, this has the intention of 'activating' channel cache. Needed as backfill for channel cache is not yet implemented for CV  

## Pre-review checklist
- [ ] Removed debug logging (`fmt.Print`, `log.Print`, ...)
- [ ] Logging sensitive data? Make sure it's tagged (e.g. `base.UD(docID)`, `base.MD(dbName)`)
- [ ] Updated relevant information in the API specifications (such as endpoint descriptions, schemas, ...) in `docs/api`

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [ ] `GSI=true,xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/000/

2023-11-29 15:47 UTC, bbrks requested changes
A couple of questions about reducing amount of changes due to the function signature change to `Put()` - I think we might be able to get away without it

2023-11-29 15:47 UTC, bbrks commented on db/crud.go
> +	return newRevID, currentVersion, doc, err
If this value is computable from everything in `doc` do we need a new return value from this method?

Places that care about `currentVersion` could call a method like `doc.CurrentVersion()` that just returns `SourceAndVersion{SourceID: doc.HLV.SourceID, Version: doc.HLV.Version}` ?

2023-11-29 15:47 UTC, bbrks commented on db/changes.go
> +	}
The method on `Document` I mentioned in previous comment would also be of use here.

2023-12-04 12:38 UTC, bbrks submitted a review, later dismissed
I don't know if the CV on the changes feed needs formatting or if JSON is fine, the original issue doesn't specify - so will just approve with the assumption it's correct.

2023-12-04 12:38 UTC, bbrks commented on rest/changes_test.go
> +func TestCVPopulationOnChangesViaAPI(t *testing.T) {
Could we get tests to cover CV on the doc ID changes feed and revocation feeds? I see the code is changed for those as well (`makeChangeEntry` for normal/revoked and `createChangesEntry` for doc IDs) but no coverage.

2023-12-05 11:28 UTC, gregns1 commented on rest/changes_test.go
> +func TestCVPopulationOnChangesViaAPI(t *testing.T) {
I have updated the test I have for doc ID changes feed to actually use this feed. I made a mistake and it wasn't actually using this code path. Should be fixed now in TestCVPopulationOnDocIDChanges. Really good spot! 

With regards to the revocation feed codepath, until Adam's changes for the channel indexes are merged I can't test that codepath. Revocation feed bypass the channel cache -> https://github.com/couchbase/sync_gateway/blob/be6b7047ac1b6d8ee953c3ff8b6de595cead7194/db/changes.go#L199 and force the query, at which we don't populate the CV off the query yet.

2023-12-07 15:00 UTC, bbrks approved these changes

2023-12-07 15:31 UTC, merged