CBG-3354 Channel query support for current version
couchbaselabs/sync_gateway pull request #6625
Opened 2023-12-22 21:37 UTC by adamcfraser

Adds current version to marshalled _sync.rev property for use with existing indexes.

New struct RevAndVersion handles marshal/unmarshal of the rev property, and supports rev only (string) and rev/src/version (map).

New structs SyncDataJSON and SyncDataAlias are used to encapsulate this handling at the persistence/marshalling layer.  This avoids changes to use of SyncData.CurrentRev, and also avoids potential errors by not duplicating cv in SyncData.

CBG-3354

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [ ] `GSI=true,xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/000/

2024-01-05 13:29 UTC, bbrks requested changes
Looks good - see inline for a few test assertion-related comments

2024-01-05 13:29 UTC, bbrks commented on db/database_test.go
> +			entries, err = collection.getChangesInChannelFromQuery(ctx, testCase.channelName, 0, 100, 0, false)
```suggestion
			entries, err = collection.getChangesInChannelFromQuery(ctx, testCase.channelName, 0, 100, 0, false)
			require.NoError(t, err)
```

2024-01-05 13:29 UTC, bbrks commented on db/database_test.go
> +			assert.Equal(t, 2, len(entries))
```suggestion
			require.Len(t, entries, 2)
```

2024-01-05 13:29 UTC, bbrks commented on db/document_test.go
> +			//require.Equal(t, test.expectedCombinedVersion, newSyncData.RevAndVersion)
I suppose this assertion could be checked if you unmarshal into SyncDataJSON but given the roundtrip I'm not too fussed if we don't

2024-01-05 13:29 UTC, bbrks commented on db/import_test.go
>  	assert.NoError(t, err, "Error Getting Xattr")
```suggestion
	require.NoError(t, err, "Error Getting Xattr")
```

2024-01-05 13:29 UTC, bbrks commented on db/import_test.go
> +	assert.True(t, syncData.CurrentRev != "")
```suggestion
	require.True(t, syncData.CurrentRev != "")
```

2024-01-05 13:29 UTC, bbrks commented on db/import_test.go
>  	assert.True(t, generation == expectedRevGeneration)
```suggestion
	assert.Equal(t, generation, expectedRevGeneration)
```

2024-01-05 13:29 UTC, bbrks commented on db/util_testing.go
> +// requireCurrentVersion fetches the document by key, and validates that cv matches.
```suggestion
// GetDocumentCurrentVersion returns the current version of the document by key
```

2024-01-09 01:09 UTC, adamcfraser commented
Thanks for catching these - have made all the suggested changes.

2024-01-09 08:35 UTC, bbrks approved these changes

2024-01-09 08:35 UTC, merged