implement body.Close checker
couchbaselabs/sync_gateway pull request #6646
Opened 2024-01-17 17:52 UTC by torcolvin

There were no production code that was missing body.Close() but there was a lot missing in tests. This is a small resource leak.

## Pre-review checklist
- [x] Removed debug logging (`fmt.Print`, `log.Print`, ...)
- [x] Logging sensitive data? Make sure it's tagged (e.g. `base.UD(docID)`, `base.MD(dbName)`)
- [x] Updated relevant information in the API specifications (such as endpoint descriptions, schemas, ...) in `docs/api`

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [ ] `GSI=true,xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/2263/

2024-01-17 19:09 UTC, adamcfraser approved these changes, later dismissed

2024-01-18 10:25 UTC, bbrks requested changes
I'm OK with adding this, just a couple of specific comments inline.

2024-01-18 10:25 UTC, bbrks commented on rest/utilities_testing_user.go
> +		assert.NoError(t, resp.Body.Close())
Is it possible for the code outside the retry loop to read the body after it has already been closed? (47-51)

I think we can also drop the outer Body.Close() if we ensure the unclosed body doesn't leak out of the retry loop.

2024-01-18 10:25 UTC, bbrks commented on rest/oidc_api_test.go
> +			defer func() { assert.NoError(t, response.Body.Close()) }()
Doesn't each response body need closing? The defer will only get one of the 3 here

2024-01-19 11:54 UTC, bbrks approved these changes

2024-01-19 12:25 UTC, merged