Fix linter error
couchbaselabs/sync_gateway pull request #6762
Opened 2024-04-09 16:14 UTC by bbrks

```sh
$ golangci-lint run --config .golangci-strict.yml db
db/crud.go:1086:2: ineffectual assignment to generation (ineffassign)
    generation++
    ^ 
```

Filed https://issues.couchbase.com/browse/CBG-3893 to properly fix.

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
-  n/a

2024-04-09 16:18 UTC, bbrks commented
Needs further investigation to properly fix.

2024-04-11 22:33 UTC, adamcfraser requested changes

2024-04-11 22:33 UTC, adamcfraser commented on db/crud.go
> +	newGeneration++
I thought we needed to (also?) do this inside the loop to account for CAS retry.

2024-04-17 15:08 UTC, bbrks commented
Filed https://issues.couchbase.com/browse/CBG-3893 to properly fix.

2024-04-17 15:27 UTC, torcolvin approved these changes

2024-04-17 22:45 UTC, merged