CBG-3839: handle rollback of the _sync:seq document in the bucket
couchbaselabs/sync_gateway pull request #6837
Opened 2024-05-21 08:43 UTC by gregns1

CBG-3839

- After incoming the sync:se doc in incrementSequence function we can check if the result is less then we are expecting, thus determine the _sync:sequence must’ve been rolled back. 
- Added function _fixSyncSeqRollback for this to handle this
- Need the minimum correction stop be the sequence batch size as when having multiple nodes you can have overlapping sequence batches
- Have testing for single and multi node handling

## Pre-review checklist
- [ ] Removed debug logging (`fmt.Print`, `log.Print`, ...)
- [ ] Logging sensitive data? Make sure it's tagged (e.g. `base.UD(docID)`, `base.MD(dbName)`)
- [ ] Updated relevant information in the API specifications (such as endpoint descriptions, schemas, ...) in `docs/api`

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [ ] `GSI=true,xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/000/

2024-05-22 12:36 UTC, bbrks requested changes

2024-05-22 12:36 UTC, bbrks commented on db/sequence_allocator.go
> +		base.WarnfCtx(ctx, "rollback of _sync:seq document detected")
Is it going to be useful to know the values we passed in and got back?

2024-05-22 12:36 UTC, bbrks commented on db/sequence_allocator.go
> +			return 0, 0, err
I think this case needs to unlock the mutex like above

2024-05-22 12:36 UTC, bbrks commented on db/sequence_allocator.go
> +		correctionIncrValue := (s.max + s.sequenceBatchSize) - max
Does the logic inside `_fixSyncSeqRollback` do this already?

2024-05-23 00:11 UTC, adamcfraser requested changes

2024-05-23 00:11 UTC, adamcfraser commented on db/sequence_allocator.go
> +		incrValue += s.sequenceBatchSize - incrValue
This would be simpler as incrValue = s.sequenceBatchSize?

2024-05-23 00:11 UTC, adamcfraser commented on db/sequence_allocator.go
> +		base.WarnfCtx(ctx, "rollback of _sync:seq document detected")
As with Ben's comment earlier, we should include the sequence values (max, s.max, batchSize) in the warning message.

2024-05-23 00:11 UTC, adamcfraser commented on db/sequence_allocator.go
> +	// we must have correction value of at least the sequence batch size else we risk overlapping batches between nodes
I don't think there's a situation where we would end up with overlapping batches (and batch size isn't intended to handle that, batch size should just be a performance consideration on this node).  Can you clarify what's meant here?

2024-05-31 16:23 UTC, bbrks requested changes
Still need to review logic inside `_fixSyncSeqRollback` but the initial things I saw

2024-05-31 16:23 UTC, bbrks commented on db/sequence_allocator.go
> +	//minimum number that _sync:seq will be corrected by in event of a rollback
Might be worth adding the commentary about how we settled on this number for future reference.

```suggestion
	// minimum number that _sync:seq will be corrected by in event of a rollback
	// assumes a SG cluster size of 50 nodes each allocating a full batch size of 10
	// if this value is too low and this correction has potential to allocate sequences that other nodes have already reserved a batch for
```

2024-05-31 16:23 UTC, bbrks commented on db/database.go
> +	dbContext.sequences.nodes = clust.Nodes
Don't think we need this any more?

2024-05-31 16:23 UTC, bbrks commented on db/sequence_allocator.go
> +	return actualVal <= expectedVal
This seems like it should be `<` but I think I also need a closer look at the code inside `_fixSyncSeqRollback` as well - don't have time for a complete review of that today.

2024-06-03 07:41 UTC, gregns1 commented on db/database.go
> +	dbContext.sequences.nodes = clust.Nodes
Apologies missed removing this

2024-06-13 16:23 UTC, adamcfraser requested changes
I think there is some simplification of fixSyncSeqRollback possible.

2024-06-13 16:23 UTC, adamcfraser commented on db/sequence_allocator.go
> +	// assumes a SG cluster size of 50 nodes each allocating a full batch size of 10
```suggestion
	// Accounts for a maximum SG cluster size of 50 nodes, each allocating a full batch size of 10
```

2024-06-13 16:23 UTC, adamcfraser commented on db/sequence_allocator.go
> +		base.ErrorfCtx(ctx, "rollback of _sync:seq document detected. Allocated to %d but expected value of at least %d", allocatedToSeq, expectedValue)
This should be logged at warn - error should be reserved for non-recoverable scenarios.

2024-06-13 16:23 UTC, adamcfraser commented on db/sequence_allocator.go
> +	expectedValue := s.max + s.sequenceBatchSize
```suggestion
	minimumExpectedValue := s.max + s.sequenceBatchSize
```

2024-06-13 16:23 UTC, adamcfraser commented on db/sequence_allocator.go
> +		correctionIncrValue := (expectedValue - max) + syncSeqCorrectionValue
It feels like these four lines (332-335) should be moved into fixSyncSeqRollback (and the same for other uses).

2024-06-13 16:23 UTC, adamcfraser commented on db/sequence_allocator.go
> +	cas, err := s.datastore.Get(s.metaKeys.SyncSeqKey(), &result)
It looks like the retry flow here is:
1. Get _sync:seq value + cas
2. If value < targetValue, WriteCas to update
  2.1. On cas failure, return to 1
3. On success, incr(batchsize)

Can we move initial Get inside the worker to simplify this function, and to ensure we only do 3 in one place?

2024-06-13 16:23 UTC, adamcfraser commented on db/sequence_allocator.go
> +func shouldRetrySyncSeqCorrection(expectedVal, actualVal uint64) bool {
I think a separate function for "actual < expected" is overkill and makes the calling code harder to read.

2024-06-13 16:23 UTC, adamcfraser commented on db/sequence_allocator.go
> +		allocatedToSeq, err = s.incrementSequence(s.sequenceBatchSize)
As mentioned above, seems like this could be moved inside the loop to avoid duplication with line 454.

2024-06-18 07:03 UTC, adamcfraser approved these changes

2024-06-18 07:04 UTC, merged