Support n1ql for LeakyDataStore
couchbaselabs/sync_gateway pull request #6879
Opened 2024-06-07 19:04 UTC by torcolvin

TestResyncErrorScenarios was a dead test (skipped because it requires an unsupported flag) and is already duplicated in rest/adminapitest

 
## Pre-review checklist
- [x] Removed debug logging (`fmt.Print`, `log.Print`, ...)
- [x] Logging sensitive data? Make sure it's tagged (e.g. `base.UD(docID)`, `base.MD(dbName)`)
- [x] Updated relevant information in the API specifications (such as endpoint descriptions, schemas, ...) in `docs/api`

## Dependencies (if applicable)
- [x] Link upstream PRs
- [x] Update Go module dependencies when merged

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [x] `GSI=true,xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/2493/

2024-06-10 15:41 UTC, gregns1 commented
LGTM - will let @adamcfraser have a look over it though

2024-06-10 22:12 UTC, adamcfraser requested changes

2024-06-10 22:12 UTC, adamcfraser commented on base/collection_n1ql_common.go
> +	IsErrNoResults(context.Context, error) bool
I don't know if it makes sense to add context to this API, just for warn logging in the leaky bucket conversion step.  Given that we wouldn't have been able to get to the point where we would need to check this (i.e. have results from executeQuery) for a non-N1QL data store, it doesn't seem needed?

2024-06-13 21:15 UTC, adamcfraser approved these changes

2024-06-13 21:15 UTC, merged