CBG-3867 ban empty replications or replication id on REST calls
couchbaselabs/sync_gateway pull request #6895
Opened 2024-06-13 17:23 UTC by torcolvin

allow them for legacy config reading, but print a warning.

This is a follow on to https://github.com/couchbase/sync_gateway/commit/84997a0d39241fafcc926c86771750f2ad60febd

I could potentially remove the call in `PutReplications` because that will now be hit earlier `dbConfig.validate`

## Pre-review checklist
- [x] Removed debug logging (`fmt.Print`, `log.Print`, ...)
- [x] Logging sensitive data? Make sure it's tagged (e.g. `base.UD(docID)`, `base.MD(dbName)`)
- [x] Updated relevant information in the API specifications (such as endpoint descriptions, schemas, ...) in `docs/api`

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [x] `GSI=true,xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/2515/ (unrelated known flake)

2024-06-13 21:00 UTC, adamcfraser requested changes

2024-06-13 21:00 UTC, adamcfraser commented on rest/admin_api.go
> +		isUpsert := true
Create db shouldn't be considered an upsert - are we using the wrong terminology for the legacy case?

2024-06-13 21:00 UTC, adamcfraser commented on rest/config.go
> +	err := dbConfig.validate(ctx, validateOIDCConfig, isUpsert)
At this point for a POST _config we've already performed a merge between the incoming request and the existing db config.  It seems like if there's an existing replication in the config with id="", and we're making an upsert unrelated to replications, we're going to reject that update here.  Given that, do we think this is the right place to be performing the empty replication ID check?  Or is there something in the handling for existing replications I'm overlooking.

2024-06-13 21:00 UTC, adamcfraser commented on rest/config.go
> +func (dbConfig *DbConfig) validate(ctx context.Context, validateOIDCConfig bool, isUpsert bool) error {
I don't like adding the conditional 'isUpsert' parameter here - previously this function's usage was clear - pass a fully populated dbconfig, and find out if it's valid.  Conditional handling based on the type of update makes that quite a bit harder to reason about for me.

If the more correct name for the parameter is 'isLegacyConfig' that might be an improvement?

2024-06-18 21:40 UTC, torcolvin commented on rest/config.go
> +func (dbConfig *DbConfig) validate(ctx context.Context, validateOIDCConfig bool, isUpsert bool) error {
I changed the name of this to be `validateReplications` to indicate whether we want to validateReplications. It does make it narrower but hopefully easier to understand when we want to do it.

2024-06-18 21:44 UTC, torcolvin commented
Added a feature to not overwrite the replications from a dbConfig, since overwriting them would mean that the replications in CfgSG get updated every time the database gets reloaded, despite updates to /db/_replication/.

I added warning code to `sgReplicateManager` to find existing replications that are affected and provided instructions for fixing. The "easy" case of just missing ID will be correctable using REST api, but the case of missing keys has to be updated by editing the cluster doc directly. That's why I moved the validation to `sgReplicateManager` since this where we know the name of the document.

2024-06-25 21:08 UTC, adamcfraser reviewed
Looks good - one nit on the logging.

2024-06-25 21:08 UTC, adamcfraser commented on db/sg_replicate_cfg.go
> +			base.WarnfCtx(ctx, "An ISGR replication with an empty `id` exists. To fix this, update the replication using PUT /%s/_replication/%s. %s", m.dbContext.Name, replicationID, resetCheckpointMsg)
I think avoiding back-ticks in log lines would be preferred, and we decided at one point to try to standardize on ID.
```suggestion
			base.WarnfCtx(ctx, "An ISGR replication with an empty ID exists. To fix this, update the replication using PUT /%s/_replication/%s. %s", m.dbContext.Name, replicationID, resetCheckpointMsg)
```

2024-06-25 22:40 UTC, adamcfraser approved these changes

2024-06-26 01:34 UTC, merged