CBG-4317 uptake fix for TLS without certs for import feed
couchbaselabs/sync_gateway pull request #7192
Opened 2024-11-12 00:34 UTC by torcolvin

CBG-4317 use cbgt patch from MB-64126 to allow sharded import feed to function

2024-11-12 12:37 UTC, bbrks commented
@torcolvin Is there an integration test run for this PR to validate the new test works with Couchbase Server?

2024-11-14 01:14 UTC, adamcfraser requested changes

2024-11-14 01:14 UTC, adamcfraser commented on base/dcp_sharded.go
> +	removeCbgtRootCertsForBucket(c.sourceUUID)
If multiple databases are using the same bucket, this looks like it's going to delete the shared credentials for all when the  import listener is stopped for any one of the databases using that bucket.

2024-12-02 17:12 UTC, bbrks commented
@torcolvin will need a rebase onto latest `release/anemone` (sorry!)

2024-12-03 00:48 UTC, adamcfraser approved these changes

2024-12-03 00:48 UTC, merged