CBG-4331: legacy rev handling for version 4 replication protocol
couchbaselabs/sync_gateway pull request #7239
Opened 2024-12-11 16:10 UTC by gregns1

CBG-4331

- Add check for vector rev in propose changes handling, if no vector present fall into legacy rev handling 
- When failing to parse hlv out of known revs AND we're in protocol version 4 then we can assume we have received a legacy rev, then pass down boolean unto sendRevision to build out the history for a legacy rev message 
- Handling for legacy rev messages in processRev when in protocol version 4.
- Test coverage using blip tester, adding custom handlers when necessary to force a legacy rev response

## Pre-review checklist
- [ ] Removed debug logging (`fmt.Print`, `log.Print`, ...)
- [ ] Logging sensitive data? Make sure it's tagged (e.g. `base.UD(docID)`, `base.MD(dbName)`)
- [ ] Updated relevant information in the API specifications (such as endpoint descriptions, schemas, ...) in `docs/api`

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [ ] `GSI=true,xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/000/

2024-12-12 01:00 UTC, adamcfraser requested changes
Changes look good - made a comment about one use case that I thought the tests could include.

2024-12-12 01:00 UTC, adamcfraser commented on rest/blip_legacy_revid_test.go
> +func TestProposeChangesHandlingWithExistingRevs(t *testing.T) {
We don't have a case here where the current rev on SGW matches the legacy rev (where we'd expect to return ProposedRev_Exists).  Is that challenging to test today?  For the purposes of testing it would be probably be ok if the SGW write has an HLV, if that's needed (i.e. the legacy rev is matching the revTreeID generated for a SGW 4.0 update).

2024-12-13 08:24 UTC, adamcfraser submitted a review, later dismissed

2024-12-13 08:24 UTC, adamcfraser commented on db/blip_sync_context.go
> +							base.DebugfCtx(ctx, base.KeySync, "Invalid known rev format for hlv on doc: %s falling back to full body replication.", base.MD(docID))
doc IDs are user data, and should get UD()

2024-12-13 10:56 UTC, bbrks approved these changes

2024-12-13 11:08 UTC, merged